// Test entry only: exposes the real stores, hosts and dialogs to the DOM regression runner.
export { OpenSpecPanelView } from './OpenSpecPanel'
export { SpecTab } from './SpecTab'
export { SPEC_STORIES } from './fixture'
export { archiveChange, confirmArchive, useSpecConfirm } from './specActs'
export { SpecActsConfirm } from './SpecActsConfirm'
export { useSpec } from '../specStore'
export { useTasks } from '../tasksStore'
export { useWorkspace } from '@/store/workspace'
export { useApplyDialog } from './applyStore'
export { getSnapshot as noticeSnapshot, clearNotices } from '@/chrome/notices'
export { useSpecRuns, followSpecRuns } from './specRuns'
export { readChange, readArtifact, invalidateSpecData, retainSpecProjects, useSpecData } from './specData'
