// GENERATED FILE — DO NOT EDIT.
//
// Every type below comes from a `#[derive(TS)]` type in `crates/cide-ipc`, concatenated in
// type-name order. Regenerate with `cargo xtask codegen`.
//
// CI runs `cargo xtask codegen --check`, so a Rust field rename that never reached this
// file fails the build instead of surfacing as an `undefined` in the webview at runtime.

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A live attachment of a webview sink to a session.
 */
export type AttachmentId = string;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Orientation of a split. `Row` places children left/right, `Col` top/bottom.
 */
export type Axis = "row" | "col";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One binding, in the layered keymap.
 */
export type Binding = { 
/**
 * A chord: `ctrl+p`, or a multi-stroke sequence like `ctrl+k ctrl+s`.
 *
 * Multi-stroke is why the frontend runs its own prefix state machine — CodeMirror's
 * `KeyBinding.key` parser handles single chords only.
 */
key: string, 
/**
 * The command id, e.g. `pane.split.right`. A leading `-` **removes** a binding
 * contributed by an earlier layer, which is how a user disables a default.
 */
command: string, 
/**
 * Context expression, e.g. `terminalFocused && !overlayOpen`. `None` means always.
 */
when: string | null, 
/**
 * Opaque payload handed to the command.
 */
args: unknown, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything a freshly opened window needs in one round trip.
 *
 * One call rather than several: a window that has to make four requests before it can
 * paint will show three intermediate states, and on a slow IPC path that is visible.
 */
export type Bootstrap = { window: WindowLabel, role: WindowRole, workspace: Workspace, keymap: Array<ResolvedBinding>, commands: Array<Command>, capabilities: Capabilities, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Head, upstream and the divergence counts the status bar shows.
 */
export type BranchInfo = { 
/**
 * Branch short name, or an abbreviated oid when detached.
 */
head: string, detached: boolean, 
/**
 * `origin/main`, when the branch has one.
 */
upstream: string | null, ahead: number, behind: number, 
/**
 * `merge`, `rebase`, `cherry-pick`, `revert`, `bisect` — whatever `.git` says is
 * half-finished. The panel refuses to commit changelists while one is running.
 */
operation: string | null, 
/**
 * No commits yet: `HEAD` points at an unborn branch.
 */
unborn: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What this build can actually do, so the frontend never offers a dead control.
 */
export type Capabilities = { version: string, 
/**
 * `claude --version`, or `None` when the binary is not on `PATH`.
 */
claudeVersion: string | null, 
/**
 * False until the LSP phase; the status bar's diagnostics counts stay a placeholder
 * and `getDiagnostics` answers empty rather than pretending.
 */
diagnostics: boolean, 
/**
 * Whether the IDE-integration MCP server is running for this project.
 */
ideProtocol: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One changed path.
 *
 * Carries *both* sides — `index` is HEAD→index, `worktree` is index→workdir — because the
 * tri-state checkbox in the commit tree is a function of the pair, and collapsing them to
 * one status is what makes a partially-staged file render as a lie.
 */
export type ChangeEntry = { path: string, 
/**
 * The pre-rename path, when git found a rename.
 */
origPath: string | null, index: FileState, worktree: FileState, 
/**
 * True when the index differs from HEAD for this path.
 */
staged: boolean, 
/**
 * libgit2 called at least one side binary. Hunk and line staging are refused.
 */
binary: boolean, 
/**
 * A gitlink. Its own changes appear under its own `RepoInfo`, not here.
 */
submodule: boolean, 
/**
 * The changelist that owns this path. Untracked and ignored entries carry the
 * changelist they *would* join if staged, which is always the active one.
 */
changelist: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One changelist and the changes currently in it.
 */
export type ChangelistView = { id: string, name: string, comment: string, 
/**
 * Exactly one changelist per repo is active; new changes land in it.
 */
active: boolean, changes: Array<ChangeEntry>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The whole tree, one entry per repository, roots before their submodules.
 */
export type ChangesTree = { repos: Array<RepoChanges>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Environment toggles passed to `claude` children, and how many of them come back on launch.
 *
 * The three environment toggles default off. [`Self::resume_all_on_launch`] does not, which
 * is why this has a hand-written [`Default`] rather than a derived one — a derive would give
 * it `false` silently, and it did: the field was added with a `true` written into a `Default`
 * impl that did not exist, the edit was a no-op, and only a test asserting the default caught
 * it.
 */
export type ClaudeSettings = { 
/**
 * `CLAUDE_CODE_DISABLE_MOUSE=1`. Worth offering because xterm.js has no
 * shift-to-bypass gesture for mouse capture, so a TUI that grabs the mouse takes
 * selection with it.
 */
disableMouse: boolean, 
/**
 * `CLAUDE_CODE_ALT_SCREEN_FULL_REPAINT=1`.
 */
altScreenFullRepaint: boolean, 
/**
 * `CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN=1`.
 */
disableAlternateScreen: boolean, 
/**
 * Resume **every** Claude pane on launch, rather than only the project's console.
 *
 * The plan shipped the cautious answer — one eager pane, the rest showing a Resume
 * splash — on the reasoning that "reopening a six-pane project should not silently fork
 * six agents at once", and named this flag as the way out. It is the way out.
 *
 * Two things make the caution smaller than it reads. Resuming is not forking: `--resume`
 * continues a conversation that already exists and starts no new one, and it sends no
 * prompt, so nothing is spent until the user types. What it does cost is one `claude`
 * process per pane at launch, which is the honest reason someone might turn this off.
 *
 * Default **on**, because the splash is a screen asking a question whose answer is
 * always yes: a pane restored into a saved layout is a pane the user left open.
 */
resumeAllOnLaunch: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A command the palette can run and a key can be bound to.
 */
export type Command = { 
/**
 * Stable id, e.g. `pane.split.right`. Never localised, never renamed casually — user
 * keymaps refer to it.
 */
id: string, 
/**
 * Shown in the palette, e.g. `Split pane right`.
 */
title: string, 
/**
 * Right-aligned group in the palette, e.g. `Window`, `Claude`, `Terminal`.
 */
group: string, 
/**
 * Context in which the command is applicable, same grammar as `Binding::when`.
 */
when: string | null, 
/**
 * Why this command cannot run *in any context*, or `None` when it can.
 *
 * Distinct from [`when`](Self::when), and the distinction is the whole reason this
 * field exists. A `when` clause says "not right now, because of where you are" — focus
 * a Claude pane and the command works. This says "not in this build, whatever you do":
 * the capability it needs does not exist yet. The palette draws these rows greyed with
 * the reason instead of hiding them, because a user who is looking for *Restart Claude
 * session* and finds nothing concludes the app cannot do it and stops looking; a
 * disabled row with a reason tells them what is actually true.
 *
 * The alternative was to delete such commands from the registry until they work. That
 * loses twice: the id stops being reserved (so a keymap.json naming it becomes an
 * error rather than a no-op), and nothing anywhere records that the gap exists — which
 * is how ~35 dead entries came to be listed in the first place.
 *
 * Nothing may bind a key to one of these; `cide_core::commands` has a test.
 */
unavailable: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitOutcome = { oid: string, summary: string, files: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `git.commit` was asked to do.
 */
export type CommitRequest = { message: string, amend: boolean, 
/**
 * Which changelist to commit. `None` means the active one.
 */
changelist: string | null, 
/**
 * Restrict the commit to these paths and parts. `None` commits every change in the
 * changelist whole.
 */
selections: Array<PathSelection> | null, 
/**
 * Commit even though the index changed outside cide — the "overwrite" half of the
 * guard bar. Never defaulted to true anywhere.
 */
force: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the user answered a diff that Claude Code is blocked on.
 *
 * The three outcomes are the protocol's, and the difference between them is what gets
 * written to disk — so this is one of the few wire types where a wrong mapping destroys
 * work rather than degrading a view.
 */
export type DiffAnswer = { "kind": "acceptedEdited", contents: string, } | { "kind": "acceptedAsIs" } | { "kind": "rejected" };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiffHunkView = { 
/**
 * Index into [`FileDiff::hunks`]. Named explicitly so a [`LineRef`] is readable in a
 * log line without the surrounding array.
 */
index: number, 
/**
 * The `@@ -a,b +c,d @@ section` line as libgit2 rendered it.
 */
header: string, oldStart: number, oldLines: number, newStart: number, newLines: number, lines: Array<DiffLineView>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of a hunk.
 *
 * `no_newline` is the `\ No newline at end of file` marker, folded onto the line it
 * annotates rather than modelled as a line of its own. Keeping it as a separate row would
 * put a phantom entry in the middle of the indices a [`LineRef`] uses, and every off-by-one
 * there is a mis-staged line.
 */
export type DiffLineView = { origin: LineOrigin, 
/**
 * Without the leading `+`/`-`/` ` and without the trailing newline.
 */
content: string, oldLineno: number | null, newLineno: number | null, noNewline: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a diff came from, which decides what happens when the user answers it.
 */
export type DiffOrigin = { "kind": "git", 
/**
 * Which repository the path belongs to. A `RepoId` is a uuid derived from the
 * canonical work tree, **not** a path — `cmd/git.rs::repo_root` resolves it, and a
 * path passed where an id belongs is a `NoSuchRepo` on every button in the panel.
 */
repo: RepoId, 
/**
 * Repo-relative and slash-separated, the way `cide_ipc::git` spells every path.
 */
path: string, 
/**
 * Which pair of trees the tab was opened on.
 *
 * Load-bearing rather than decorative: `cide_git::stage::stage` re-derives the diff
 * with `Unstaged`, `unstage` with `Staged`, and `commit` with `Combined`. A
 * [`crate::git::Selection`] names *positions in a diff*, so one made against the
 * wrong side is refused by the `rev` check — and would name different lines if the
 * check were skipped. The pane may switch sides while it is open; this is where it
 * starts, which is all a saved layout has any business remembering.
 */
side: DiffSide, } | { "kind": "claudeMcp", requestId: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which pair of trees a diff compares.
 */
export type DiffSide = "staged" | "unstaged" | "combined";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a diff tab is *about*. Never what it contains.
 *
 * This struct is persisted: it lives in `TabKind::Diff`, inside `Workspace`, which
 * `cide-core::persist` debounces to `workspace.json`. So it carries identity and nothing
 * else — no original text, no proposal, no patch. That is the same rule that keeps
 * `new_file_contents` out of a Claude diff (the pane calls `claude_diff_content` when it
 * mounts) and it is why [`DiffOrigin::Git`] carries a *fetch key* rather than a diff: the
 * pane calls `git_diff_file` when it mounts.
 *
 * Two reasons, and the second is the one that bites. A saved layout would hold megabytes of
 * file text that nobody reads back; and, worse, it would hold a *stale* copy — the working
 * tree moves while the tab is open, so a diff written to disk at 10:00 and restored at
 * 14:00 describes a file that no longer exists in that form. A key re-reads; a copy lies.
 */
export type DiffSpec = { title: string, 
/**
 * The left-hand side's path.
 *
 * Absolute for a `ClaudeMcp` diff, which names files on disk. **Repo-relative** for a
 * `Git` one, because that is how git spells a path and how the fetch key in
 * [`DiffOrigin::Git`] spells it — a `PathBuf` here is the display label for a pair of
 * paths, not a handle anything opens.
 */
oldPath: string, newPath: string, origin: DiffOrigin, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified rows, or the two sides beside each other.
 *
 * Stored rather than held in the pane, because a diff pane is opened and closed constantly
 * — every file in the git panel is a new tab — and a mode that resets with the pane is a
 * mode nobody can stay in. It lives under `editor` rather than `git` because both diff
 * surfaces read it: the git pane and Claude's `openDiff` proposal are the same question
 * asked about different documents.
 *
 * **Unified is the default and that is deliberate.** It is what the pane has always shown,
 * it is the shape the per-line staging selection is expressed in (one row is one
 * `hunk:line`), and it is the only one that survives a narrow pane — see `DIFF_SPLIT_MIN_PX`
 * in `ui/src/panes/GitDiffPane.tsx`, which falls back to it rather than offering a split
 * nobody can read.
 */
export type DiffView = "unified" | "split";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which way to move when navigating between panes with the keyboard.
 */
export type Direction = "left" | "right" | "up" | "down";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enough of a pane's old position to rebuild the split that detaching collapsed.
 *
 * Detaching a pane removes its leaf and folds the parent split into whatever was on the
 * other side. Everything that split knew — its axis, its divider position, which half the
 * pane occupied — is gone with it, and a re-dock that does not remember it can only guess.
 * The guess is visible: a pane that was 70/30 coming back as 50/50 resizes a terminal, and
 * a reflowed `claude` TUI redraws its whole transcript.
 *
 * What is stored is the *sibling node*, not a path from the root. A path indexes positions
 * and every position shifts when any other pane in the tab is closed or split; a node id
 * either still exists or plainly does not, which is exactly the question re-docking needs
 * answered. Storing the sibling also handles the case a pane id alone cannot: the pane may
 * have been split against a whole subtree, and re-entering "beside" some leaf inside that
 * subtree would nest it one level too deep.
 */
export type DockAnchor = { 
/**
 * The node left behind when the split collapsed. The pane goes back beside *this*.
 */
sibling: DockSibling, 
/**
 * The id of the collapsed split, reinstated rather than minted afresh so that anything
 * keyed on the divider — a drag in flight, a ratio the frontend is animating — refers to
 * the same divider it did before the detach.
 */
split: SplitId, axis: Axis, 
/**
 * Which half of the split the detached pane occupied, in the same sense as the `side`
 * passed to a split: `Before` means it was child `a`.
 */
side: Side, 
/**
 * The collapsed split's ratio — the fraction that went to child `a`, so it is read
 * together with `side` rather than being "the pane's share".
 */
ratio: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One node of a pane tree, named by whichever id it carries.
 *
 * A leaf is its pane and an interior node is its split; both id spaces are UUIDs minted
 * once, so a lookup answers "still there" or "gone" with no ambiguity in between.
 */
export type DockSibling = { "kind": "pane", pane: PaneId, } | { "kind": "split", split: SplitId, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditorSettings = { 
/**
 * Point size for the editor's mono face.
 *
 * `f32`, not `u8`, and the type is the fix rather than a refinement of it: the design
 * mock specifies **12.5px**, `tokens.css` ships that, and an integer cannot hold the
 * project's own default. The two defaults here were 13 and 12 — neither the mock's number
 * nor each other's — which went unnoticed for exactly as long as nothing read them.
 *
 * Clamped where a patch lands, not here: see [`clamp_font_size`].
 */
fontSize: number, tabSize: number, insertSpaces: boolean, showMinimap: boolean, wordWrap: boolean, trimTrailingWhitespaceOnSave: boolean, 
/**
 * How a diff is laid out. See [`DiffView`].
 */
diffView: DiffView, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A per-file diff, and the only thing a [`Selection`] is meaningful against.
 */
export type FileDiff = { path: string, oldPath: string | null, side: DiffSide, status: FileState, binary: boolean, 
/**
 * Unix mode bits, e.g. 33188 (0o100644). Zero when the side does not exist.
 */
oldMode: number, newMode: number, hunks: Array<DiffHunkView>, 
/**
 * Hash of the exact patch text this diff was derived from.
 *
 * A selection carries it back, and staging refuses a mismatch. Without it, a user who
 * checks three lines while Claude is mid-edit stages three *different* lines — the
 * panel's selection would be applied to a diff it never saw.
 */
rev: string, 
/**
 * False when the file cannot be partially staged at all — binary, a submodule, a
 * symlink or a deletion. The UI hides the per-hunk affordances rather than offering a
 * control that will be refused.
 */
partialOk: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A text file as the editor loads it. (M9)
 *
 * The text is the file's bytes verbatim, line endings included. Normalising here would be
 * the convenient thing and the wrong one: CodeMirror normalises again on `EditorState`
 * creation, so the only place that can tell a CRLF file from an LF one is the side holding
 * the original — and if that is not the editor, every save rewrites every line.
 */
export type FileDoc = { path: string, text: string, 
/**
 * False when the file's mode bits carry no write permission at all.
 *
 * This is exactly `Permissions::readonly()` inverted, and that is a narrower question
 * than "can this process write it": it reads the mode and nothing else, so a file
 * owned by another user with mode 0644, or any file on a read-only mount, still comes
 * back `true`. Purely advisory — the write is attempted regardless and reports its own
 * failure — but it catches the common `chmod -w` case early rather than letting the
 * user type for ten minutes into something that will not save.
 */
writable: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened to one file on one side of the index.
 */
export type FileState = "unmodified" | "added" | "modified" | "deleted" | "renamed" | "copied" | "typeChange" | "untracked" | "ignored" | "conflicted";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One coalesced burst of filesystem change.
 *
 * Bursts, not events: a `cargo build` produces tens of thousands of inotify events in a
 * second and the file tree needs to hear about it once. The watcher holds paths until the
 * tree has been quiet for its debounce window, so `touch`ing 5000 files is one of these.
 */
export type FsChange = { 
/**
 * Paths that changed, already filtered through the walk's ignore matchers.
 */
paths: Array<string>, 
/**
 * The burst was larger than the watcher will hold, so `paths` is a prefix rather than
 * the whole story and the receiver should re-read what it cares about. Reporting the
 * truncation is the point: silently dropping the tail is how a stale tree happens.
 */
truncated: boolean, 
/**
 * A watched git file changed — `HEAD`, `index`, or a ref. The branch readout and the
 * git panel refresh on this; nothing else needs to.
 */
git: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a project's index is doing, and how it is watching.
 */
export type FsStatus = { 
/**
 * True between `fs.index` starting and the walk finishing. The picker is usable the
 * whole time — this only tells the UI whether its counts are still climbing.
 */
indexing: boolean, files: number, dirs: number, 
/**
 * `treeCount` at the moment the status was taken, so a caller that is only sizing a
 * scrollbar does not need a second round trip.
 */
rows: number, watch: WatchStatus, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal geometry, in cells and in cell pixels.
 *
 * The pixel fields must be real. Passing zeroes is the usual shortcut and it breaks any
 * program that asks the terminal for its cell size — sixel and inline-image output, and
 * pixel-resolution mouse reporting.
 */
export type Geometry = { cols: number, rows: number, cellWidth: number, cellHeight: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Errors crossing the IPC boundary from `cide-git`.
 *
 * Every variant is a tag the frontend branches on. `IndexChangedExternally` in particular
 * is not an error the user should see as a failure — it is the guard bar, and the UI needs
 * to tell it apart from a genuine libgit2 failure without matching on prose.
 */
export type GitError = { "kind": "notARepository", "detail": { path: string, } } | { "kind": "noSuchRepo", "detail": { repo: RepoId, } } | { "kind": "bare", "detail": { path: string, } } | { "kind": "noSuchProject", "detail": { project: string, } } | { "kind": "indexChangedExternally", "detail": { expected: string, actual: string, } } | { "kind": "staleSelection", "detail": { path: string, } } | { "kind": "partialRefused", "detail": { path: string, reason: PartialRefusal, } } | { "kind": "noSuchChange", "detail": { path: string, } } | { "kind": "patchRejected", "detail": { detail: string, patch: string, } } | { "kind": "conflicted", "detail": { paths: Array<string>, } } | { "kind": "operationInProgress", "detail": { operation: string, } } | { "kind": "nothingToCommit" } | { "kind": "unborn" } | { "kind": "noSuchChangelist", "detail": { id: string, } } | { "kind": "defaultChangelist" } | { "kind": "duplicateChangelist", "detail": { name: string, } } | { "kind": "noSuchShelf", "detail": { id: string, } } | { "kind": "noSuchStash", "detail": { index: number, } } | { "kind": "push", "detail": { output: string, } } | { "kind": "io", "detail": { detail: string, } } | { "kind": "git", "detail": { detail: string, } } | { "kind": "sidecar", "detail": { path: string, detail: string, } };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One rung of the Linux graphics ladder.
 *
 * The whole point of surfacing these is that the failures they work around are invisible:
 * WebGL context creation succeeds on a software rasteriser, `WEBGL_debug_renderer_info` is
 * masked on Linux, and a DMABUF failure presents as a window that never paints. No probe
 * can pick the right rung, so the user gets the switch and the cost of each one.
 */
export type GraphicsRung = { 
/**
 * The environment variable, e.g. `WEBKIT_DISABLE_DMABUF_RENDERER`.
 */
variable: string, label: string, 
/**
 * What turning it on costs. Shown next to the switch, because every rung costs
 * something and a switch with no stated price gets flipped for no reason.
 */
cost: string, 
/**
 * What the user has asked for. `None` is "leave it to the launcher's heuristic".
 */
setting: boolean | null, 
/**
 * Whether this process actually has the variable set — read from our own environment,
 * not inferred from the setting.
 */
active: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Linux rendering workarounds, applied before the webview is created.
 *
 * Each is off by default and each costs something; see `docs/adr/0006`. `disable_dmabuf`
 * is the exception the app cannot start without on a stock KDE Wayland desktop, so
 * `cide-app::graphics` applies it unconditionally unless the environment already has an
 * opinion — this struct is the user-facing override for the machines that heuristic gets
 * wrong.
 */
export type GraphicsSettings = { disableDmabufRenderer: boolean | null, disableCompositingMode: boolean | null, disableNvidiaExplicitSync: boolean | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The ladder, plus whether the automatic heuristic is still in charge.
 */
export type GraphicsStatus = { rungs: Array<GraphicsRung>, 
/**
 * False once the user has set any rung explicitly.
 *
 * Taking an explicit choice as "you are driving now" is what lets a rung be turned
 * *off* at all: the launcher's defaults are applied with set-if-unset semantics, so
 * there is no value this side could write that means "and do not apply the default
 * either". Overriding one rung therefore stands the whole heuristic down, and the
 * screen says so rather than leaving the user to discover it.
 */
automatic: boolean, 
/**
 * True when `CIDE_NO_GRAPHICS_WORKAROUNDS` was set in the launching environment, which
 * disables the lot regardless of what is stored here.
 */
suppressedByEnv: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a non-interactive run produced no answer at all.
 *
 * A tagged enum rather than a string, so the frontend branches on a variant: "the binary is
 * not installed" wants an install hint, "it timed out" wants a retry, and "it printed
 * something we could not read" wants a bug report with the head of what it printed.
 */
export type HeadlessError = { "kind": "notInstalled", detail: string, } | { "kind": "noProject", project: string, } | { "kind": "timedOut", seconds: bigint, } | { "kind": "exited", code: number | null, 
/**
 * The tail of stderr, truncated — enough to name the cause, not enough to paste a
 * user's whole environment into a toast.
 */
stderr: string, } | { "kind": "malformed", detail: string, head: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One non-interactive request.
 */
export type HeadlessRequest = { 
/**
 * The whole prompt, including any diff or selection it embeds.
 *
 * Delivered to the child on **stdin**, never as argv. A commit-message prompt carries a
 * staged diff, which routinely runs to tens of kilobytes and can pass `ARG_MAX`; and a
 * prompt beginning with `-` would be parsed as a flag. Both failures are silent in
 * different ways, and stdin has neither.
 */
prompt: string, 
/**
 * A model alias (`opus`, `sonnet`, `haiku`) or a full name. `None` uses the user's own
 * default, which is the right choice for a feature they did not ask to configure.
 */
model?: string, 
/**
 * A JSON Schema for structured output, passed through as `--json-schema`.
 *
 * When set, [`HeadlessResult::structured`] carries the parsed object; `text` still
 * carries whatever the CLI printed, so a caller that gets malformed structure can show
 * something rather than nothing.
 */
jsonSchema?: unknown, 
/**
 * A hard ceiling on what this one call may spend, as `--max-budget-usd`.
 *
 * Worth setting on anything triggered by a keystroke: a palette one-shot that goes
 * looping is a bill the user never agreed to and no UI in this app would show them.
 */
maxBudgetUsd?: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one non-interactive run produced.
 *
 * A flat mirror of the CLI's terminal `result` frame rather than an enum over success and
 * failure. The CLI reports its own verdict in `is_error` *and still fills in the rest* —
 * a run that stopped on `error_max_turns` has partial text, a cost and a duration worth
 * showing — so splitting the shape by outcome would throw away the fields that make the
 * failure explicable.
 */
export type HeadlessResult = { 
/**
 * The `result` field: the final assistant text.
 */
text: string, 
/**
 * `text` parsed as JSON, when a schema was requested and the output parses.
 */
structured: unknown, 
/**
 * The CLI's own verdict, not ours. A `false` here with a non-zero exit status is
 * possible and is treated as failure by [`cide_claude::headless`].
 */
isError: boolean, 
/**
 * `success`, `error_max_turns`, `error_during_execution`, … Passed through verbatim:
 * the set is not documented and a release may add to it.
 */
subtype: string, 
/**
 * The uuid the CLI minted for this run.
 *
 * Reported **even with `--no-session-persistence`**, which this lane always passes —
 * verified against 2.1.226 by `cide-claude`'s `real_headless` test, which originally
 * asserted the opposite and failed. The flag governs whether the transcript reaches
 * disk, not whether the run has an id. So this is not evidence that a one-shot is
 * resumable, and nothing should offer to resume it.
 *
 * `Option` because the field is not guaranteed to be in the frame, not because it is
 * expected to be absent.
 */
session: string | null, costUsd: number | null, durationMs: bigint | null, numTurns: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of the mandatory boot-time IPC probe.
 *
 * Tauri's fast path (`ipc:` custom protocol) degrades *silently*: if WebKitGTK is older
 * than 2.40 or a CSP rule blocks the scheme, `ipc-protocol.js` catches the fetch
 * rejection, sets `customProtocolIpcFailed = true` permanently and falls back to string
 * `postMessage`. Throughput collapses with no crash and no Rust-side signal, so the
 * frontend has to tell us which path it actually got.
 */
export type IpcHealth = { 
/**
 * False means we are on the slow `postMessage` path.
 */
customProtocol: boolean, 
/**
 * Measured throughput of the raw-`Response` pull path.
 */
mibPerSec: number, 
/**
 * Reported by the webview, e.g. "2.52.3".
 */
webkitVersion: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Two or more commands competing for one keystroke in one context.
 *
 * A wire mirror of `cide_core::keymap::Conflict` rather than that type itself, because
 * `ts-rs` exports per crate and `cargo xtask codegen` only reads `cide-ipc`'s bindings —
 * a `#[derive(TS)]` in `cide-core` lands in `crates/cide-core/bindings` and never reaches
 * `ui/src/ipc/generated.ts`. The domain type stays the domain's; this one is the wire's.
 */
export type KeymapConflict = { 
/**
 * The normalised keystroke, e.g. `ctrl+shift+p`.
 */
key: string, 
/**
 * The competing command ids in resolution order. The **last** one wins.
 */
commands: Array<string>, 
/**
 * The shared `when` clause, `None` when all of them are unconditional. Bindings whose
 * contexts differ are not in conflict — that is how one key means two things in a
 * terminal and in an editor.
 */
when: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which layer a resolved binding came from. Surfaced in Settings → Keymap so a user can
 * see at a glance what they have overridden.
 */
export type KeymapLayer = "default" | "platform" | "user";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something in `keymap.json` that resolution recovered from rather than rejecting.
 *
 * Flattened to one message from `cide_core::keymap::KeymapDiagnostic`'s variants on
 * purpose: the screen renders a line of prose either way, and exporting an internal enum to
 * the wire would freeze its variant names as a contract.
 */
export type KeymapProblem = { key: string, command: string, message: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything Settings → Keymap draws.
 */
export type KeymapReport = { 
/**
 * Every binding after layering defaults → platform → user, each remembering its layer.
 */
bindings: Array<ResolvedBinding>, 
/**
 * Keystrokes more than one command answers to. Reported, never resolved: which should
 * win is a judgement only the user can make.
 */
conflicts: Array<KeymapConflict>, 
/**
 * Lines in the user's file that did not do what they look like they do.
 */
problems: Array<KeymapProblem>, 
/**
 * Where the overrides file lives, so the screen can name it. It need not exist — a
 * fresh install has no overrides, which is not an error.
 */
path: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LayoutNode = { "kind": "leaf", pane: PaneId, } | { "kind": "split", id: SplitId, axis: Axis, a: LayoutNode, b: LayoutNode, 
/**
 * Fraction given to `a`, clamped to [`MIN_RATIO`, `MAX_RATIO`].
 */
ratio: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LineOrigin = "context" | "addition" | "deletion";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of one hunk of a [`FileDiff`].
 */
export type LineRef = { hunk: number, 
/**
 * Index into [`DiffHunkView::lines`].
 */
line: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Pane = { id: PaneId, kind: PaneKind, role: PaneRole, 
/**
 * `None` for panes with no process, such as a diff view.
 */
session: SessionId | null, 
/**
 * e.g. `cide : claude`, `cide : bash`, `cide : claude — diff`.
 */
title: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One leaf in a tab's pane tree.
 */
export type PaneId = string;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a pane is showing.
 */
export type PaneKind = "claude" | "shell" | "diff" | "editor";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What should happen to one pane on launch.
 *
 * Advice, not instruction: the frontend owns spawning, because only the frontend knows a
 * pane's size, and a child spawned before its slot is laid out draws a ruined first frame.
 */
export type PaneRestore = { 
/**
 * The window this pane appears in, so a window can keep the entries that are its own.
 */
window: WindowLabel, project: ProjectId, 
/**
 * The tab holding the pane — for a detached pane, the tab it re-docks into.
 */
tab: TabId, pane: PaneId, kind: PaneKind, 
/**
 * Where the session must be spawned for `restore` to hold. Claude Code files a
 * transcript under the directory it was started in, so resuming from elsewhere finds
 * nothing.
 */
cwd: string, restore: SessionRestore, 
/**
 * Whether to spawn on launch rather than waiting to be asked.
 *
 * True for exactly one pane per project: the one bound to its primary session. Every
 * other Claude pane renders a splash with a resume affordance, because reopening a
 * six-pane project must not silently start six agents at once.
 */
eager: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a pane may be closed.
 *
 * The pinned Claude tab's first pane is `Primary`: closing *or detaching* it returns
 * `Err(PanePrimary)` however many panes the tab holds, so the project console can never
 * lose its conversation — not by accident, and not by splitting first.
 */
export type PaneRole = "primary" | "auxiliary";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tab's pane layout.
 *
 * Pane *data* lives in a side map rather than inside the leaves, so looking a pane up by
 * id does not mean walking the tree, and `LayoutNode` stays small enough to clone freely
 * during a rebalance.
 *
 * Invariant, asserted in `cide-core` tests: the set of leaf ids equals the key set of
 * `panes`, exactly.
 */
export type PaneTree = { root: LayoutNode, focused: PaneId, 
/**
 * Maximizing is **not** a tree mutation — it is a flag the renderer honours by giving
 * one pane the whole grid area and hiding its siblings. That keeps restore exact and
 * costs no terminal reflow.
 */
maximized: PaneId | null, panes: { [key in PaneId]: Pane }, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a partial selection was refused.
 *
 * These are the cases where synthesizing a unified diff is *silently* wrong rather than
 * loudly wrong, which is why each one is a distinct tag: the frontend has to be able to
 * explain the refusal, and "patch failed" explains nothing.
 */
export type PartialRefusal = "binary" | "submodule" | "typeChange" | "deletion" | "rename" | "noNewlineOrdering" | "empty";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which gesture put the paths on the tree's clipboard.
 *
 * Two variants and not three: there is no "duplicate". A duplicate is a [`PasteMode::Copy`]
 * whose destination happens to be the source's own parent, and the collision rule already
 * answers it with `main copy.rs`.
 */
export type PasteMode = "copy" | "cut";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one pasted path became.
 *
 * One of these per *source*, not per file on disk: pasting a directory of 4000 files is one
 * entry describing the directory. The counts inside it are what the panel says afterwards.
 */
export type PastedEntry = { source: string, 
/**
 * Where it landed. Never a path that was overwritten — see `renamed`.
 */
dest: string, 
/**
 * The destination took a *different* name because the one it wanted was taken.
 *
 * Reported rather than left for the user to notice, because the other reading of a paste
 * that quietly produced `main copy.rs` is that it did nothing: the row the user was
 * looking at is still there, still holding the older file.
 */
renamed: boolean, 
/**
 * Entries inside a copied directory that are neither a file, a directory nor a symlink —
 * fifos, sockets, devices — and were left behind.
 *
 * Copying them is either meaningless (a socket) or a hang (reading a fifo waits for a
 * writer that never comes), and refusing a whole paste over one stray `.sock` in a project
 * would be the worse answer. Counted so the panel can say so.
 */
skipped: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file and the part of it an operation applies to.
 */
export type PathSelection = { path: string, selection: Selection, 
/**
 * [`FileDiff::rev`] of the diff the selection was made against. `None` skips the
 * staleness check, which is only correct for `Whole`.
 */
rev: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One frame of picker results.
 *
 * A frame, not "the results": the file index streams in while the user is already typing,
 * so the honest answer to a query is always "here is the best 200 of what I have seen so
 * far, and I am still reading". `matched`/`total` are the two numbers behind the mock's
 * `6 of 2,418` counter, and they keep climbing during the walk.
 */
export type PickerFrame = { 
/**
 * At most the `limit` the caller asked for, capped in Rust at 200. A keystroke must
 * never ship 100k rows over IPC — the overlay draws about twelve.
 */
items: Array<PickerRow>, 
/**
 * `matched_item_count()`: how many candidates the query matches.
 */
matched: number, 
/**
 * `item_count()`: how many candidates exist so far.
 */
total: number, 
/**
 * The matcher is still working — either the walk is still injecting, or the query is
 * still being scored. The overlay polls again while this is true.
 */
running: boolean, 
/**
 * Echoed so a frame that arrives after the user has typed on can be discarded rather
 * than painted under the new query.
 */
query: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A candidate supplied by the caller, for the one-shot ranking the command palette uses.
 *
 * The file picker never sends these — its candidates come from the walk and stay in Rust.
 */
export type PickerItem = { text: string, value: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ranked candidate.
 */
export type PickerRow = { 
/**
 * What was matched and what is drawn — for files, the path relative to its root.
 */
text: string, 
/**
 * What selecting the row means: an absolute path, or a command id. Carried separately
 * because the row the user reads is never the thing the caller needs to act on.
 */
value: string, 
/**
 * Offsets in `text` that the query matched, for the highlight in the overlay.
 *
 * These count **chars**, which is what the matcher works in — not bytes, and not the
 * UTF-16 units a JS string is indexed by. Those three agree for every path made of BMP
 * characters and diverge for an emoji, so highlight against `Array.from(text)` rather
 * than `text[i]`.
 */
indices: Array<number>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One opened project: a header tab, or a whole window in `PerProject` mode.
 */
export type Project = { id: ProjectId, name: string, 
/**
 * Display form of the primary root, e.g. `~/work/cide`.
 */
displayPath: string, 
/**
 * CSS colour for the header tab's dot, e.g. `var(--accent)`.
 */
dot: string, 
/**
 * A project may hold several roots and nested submodules. Never empty; `roots[0]` is
 * the primary root and supplies `display_path`.
 */
roots: Array<ProjectRoot>, 
/**
 * `tabs[0]` is **always** the pinned Claude console. Enforced in `cide-core`.
 */
tabs: Array<Tab>, activeTab: TabId, 
/**
 * Panes torn out into their own windows.
 *
 * A detached pane cannot stay in its tab's `panes` map: the tree invariant is that the
 * leaf set and the key set are equal, and its leaf is gone. It has not stopped
 * belonging to the project though — its session is still running, and `WindowRole::
 * DetachedPane` records where it re-docks — so it waits here rather than being
 * destroyed and rebuilt, which would lose the binding to its conversation.
 */
detached: { [key in PaneId]: Pane }, 
/**
 * Where each entry of `detached` sat in its tab's tree, so re-docking can put it back
 * exactly rather than merely nearby.
 *
 * A **second map keyed the same way** rather than a field on the `detached` value: that
 * map's value type is the wire shape the detached-pane window renders (`App.tsx` reads
 * `project.detached[pane]` and expects a `Pane`), and wrapping it in a record would make
 * every reader of a torn-out pane reach through a field that only re-docking cares
 * about. The two are inserted and removed together in `cide-core::workspace`, and
 * `validate` refuses an anchor whose pane is not detached.
 *
 * Sparse by design: an entry is absent for a pane detached by an older build, and a
 * present entry can still go stale — the sibling it names may have been closed while the
 * pane was out. Re-docking checks before it trusts one.
 */
dockAnchors: { [key in PaneId]: DockAnchor }, 
/**
 * Immortal while the project is open. For a Claude pane this id *is* the value passed
 * to `claude --session-id`, so restoring a workspace needs no extra bookkeeping to map
 * a pane back to its conversation.
 */
primarySession: SessionId, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One opened project (a header tab, or a window in `PerProject` mode).
 */
export type ProjectId = string;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One root directory within a project.
 */
export type ProjectRoot = { path: string, 
/**
 * `None` when the root is not inside a git repository.
 */
repo: RepoId | null, 
/**
 * Shown as the top-level tree row when a project has more than one root.
 */
label: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What cide does about the proxy variables in a child's environment.
 *
 * Three states rather than a bool, because "do not proxy" and "do not interfere" are
 * different answers and a corporate laptop needs both. A single on/off switch would have to
 * pick one of them to be its off position: off-as-inherit leaves a user whose profile
 * exports `HTTP_PROXY` with no way to run a pane without it, and off-as-direct silently
 * breaks every pane the moment the app ships to somebody who does export one.
 */
export type ProxyMode = "inherit" | "manual" | "direct";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Proxy configuration, applied to every child cide spawns — `$SHELL` panes and `claude`
 * alike.
 *
 * # This is where a password can end up
 *
 * `http://user:hunter2@proxy.corp:3128` is a legal and common value, and this struct is
 * serialized into `workspace.json` in plain text, which is the only way a proxy that needs
 * credentials can work at all without a keyring cide does not have. What is *not* acceptable
 * is that value leaking sideways into a log the user then pastes into a bug report, so
 * [`Debug`] is implemented by hand and redacts the userinfo. That is deliberately at the
 * type level rather than at each call site: `tracing::debug!(?settings)` anywhere in the app
 * would otherwise print the password, and there is no way to review every future call site.
 *
 * The alternative that lost was storing the credentials separately in the OS keyring. It is
 * the right answer and it is a milestone of its own — Secret Service over zbus, a fallback
 * for machines with no keyring daemon, and a migration for the value already on disk.
 * Redacted `Debug` is what makes the plain-text version defensible in the meantime.
 */
export type ProxySettings = { mode: ProxyMode, 
/**
 * `HTTP_PROXY`/`http_proxy`. Empty means the variable is not set.
 */
http: string, 
/**
 * `HTTPS_PROXY`/`https_proxy`. Empty **falls back to [`Self::http`]**, because one
 * CONNECT proxy for both schemes is the overwhelmingly common shape and asking for it
 * twice is how one of the two ends up stale.
 */
https: string, 
/**
 * `ALL_PROXY`/`all_proxy`, usually a SOCKS URL.
 *
 * No fallback from [`Self::http`], unlike `https`: `ALL_PROXY` covers protocols beyond
 * HTTP, and quietly pointing them at an HTTP CONNECT proxy the user only meant for web
 * traffic changes behaviour they did not ask for.
 */
all: string, 
/**
 * Extra `NO_PROXY` entries, comma separated — the corporate intranet, a registry mirror.
 *
 * `localhost`, `127.0.0.1` and `::1` are always prepended and cannot be removed. cide's
 * IDE integration is an MCP server on loopback (`CLAUDE_CODE_SSE_PORT`), and a proxy
 * that swallows loopback turns the headline feature — inline diffs, @-mentions, the
 * editor selection — off with no error anywhere. Users do not think to exempt a port
 * they were never told about.
 */
noProxy: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `git.push`, including whatever the transport said.
 */
export type PushOutcome = { remote: string, refspec: string, 
/**
 * True when the push went through the `git` binary because a credential helper is
 * configured — libgit2 cannot drive an interactive helper.
 */
shelledOut: boolean, 
/**
 * stderr of the `git push`, or libgit2's progress text. This is where "Everything
 * up-to-date" and the remote's own messages live, and users read them.
 */
output: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether closing may proceed, and what it would cost.
 *
 * Both lists are empty in the common case, and that is the case where no dialog should
 * appear at all. A confirmation that fires whenever a process exists is one users learn to
 * dismiss without reading, which is worse than none.
 *
 * The two lists are separate because the two risks are not the same risk, and the
 * confirmation has to word them differently:
 *
 * * `unsaved` is **destruction**. Those edits exist nowhere else; closing loses them.
 *   Always reported, whatever the settings say — see `Settings::
 *   confirm_close_with_live_session`, which is about sessions and has no authority here.
 * * `blocking` is **interruption**. A `Busy` or `AwaitingPermission` session loses its
 *   turn, not its transcript: the conversation resumes with `claude --resume`. This list
 *   is governed by that setting, and is empty when the user has turned it off.
 */
export type QuitDecision = { blocking: Array<SessionSummary>, unsaved: Array<UnsavedTab>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A [`RecentProject`] as the frontend sees it: the record, plus whether it is still there.
 *
 * `exists` is deliberately **not** a field of `RecentProject`, because it is not a property
 * of the record — it is a fact about the filesystem at the moment the list was asked for, and
 * a directory can be deleted, renamed or unmounted a second later. Persisting it would write
 * an answer that is stale before it is read; the alternative that lost was a
 * `#[serde(skip)] exists` on the record itself, which reads as though the file stored it.
 *
 * A missing directory is still listed. The user's mental model is "the projects I worked on",
 * and silently dropping one is indistinguishable from the app forgetting it — so the entry
 * stays, the UI disables it with the reason, and nothing pretends to open a folder that is
 * gone.
 */
export type RecentEntry = { project: RecentProject, exists: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A project the user opened once, remembered after it closed.
 *
 * **Not part of [`Workspace`]**, and that is the whole point of the type. `workspace.json`
 * holds what is *open*; closing a project removes it from there, which is exactly the moment
 * a "recent projects" list has to start knowing about it. So this is persisted on its own, in
 * `recent.json` beside it — see `cide_core::persist::recent_path`.
 *
 * Identity is [`Self::path`], the primary root. A project can hold several roots, but the
 * gesture being remembered is "the folder I opened", and reopening the primary root is what
 * `open_project` deduplicates against.
 */
export type RecentProject = { path: string, name: string, 
/**
 * Display form of [`Self::path`], e.g. `~/work/cide`.
 *
 * Recomputed on read rather than trusted from the file, for the same reason
 * `refresh_display_paths` exists: the `$HOME` that wrote the entry is not necessarily the
 * one reading it.
 */
displayPath: string, 
/**
 * Milliseconds since the Unix epoch, at the last open. Sorts the list.
 */
openedAt: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Everything the commit tool window draws for one repository.
 */
export type RepoChanges = { repo: RepoInfo, branch: BranchInfo, 
/**
 * The default list is first; the rest keep their creation order.
 */
changelists: Array<ChangelistView>, unversioned: Array<ChangeEntry>, ignored: Array<ChangeEntry>, conflicts: Array<ChangeEntry>, 
/**
 * The index no longer matches what cide last wrote to it — someone ran `git add` in a
 * pane. Drives the non-blocking "staging changed outside cide" bar; committing while
 * this is true needs an explicit override.
 */
indexChangedExternally: boolean, 
/**
 * IDEA's "use Git staging area instead" toggle. In this mode the index is the truth
 * and cide never rebuilds it from a changelist.
 */
useStagingArea: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One git repository root within a (possibly multi-root) project.
 */
export type RepoId = string;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One git repository visible inside a project.
 *
 * A project may hold several roots, and each root may contain submodules; both arrive here
 * as separate `RepoInfo`s. Submodules are not opaque entries — they are repositories with
 * their own changes, which is the only way a monorepo user can see what is actually dirty.
 */
export type RepoInfo = { 
/**
 * Derived from the canonical work-tree path, so it is stable across restarts and
 * across the two processes that might compute it.
 */
id: RepoId, root: string, 
/**
 * The last path component, or the submodule's name — what the tree row shows.
 */
name: string, 
/**
 * The containing repository, when this one is a submodule.
 */
parent: RepoId | null, isSubmodule: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A binding after layering, as sent to the frontend.
 */
export type ResolvedBinding = { key: string, command: string, when: string | null, args: unknown, layer: KeymapLayer, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One page of a running or finished search.
 *
 * A page, not a result set. The walk is still running while the user reads the first hits,
 * so the panel asks repeatedly from an advancing `offset` and appends — the same poll shape
 * as [`PickerFrame`], and for the same reason: pushing an event per batch would put an
 * unbounded number of them on the IPC channel during a walk of a large repository.
 */
export type SearchFrame = { 
/**
 * The query these hits answer. A frame whose query is not the one on screen is dropped
 * rather than painted.
 */
query: SearchQuery, 
/**
 * Hits `[offset, offset + hits.len())` of the full list, in walk order. Every hit from
 * one file is contiguous, which is what lets the panel group by file without sorting.
 */
hits: Array<SearchHit>, 
/**
 * Where `hits[0]` sits in the full list. Echoed so a frame that arrives out of order
 * cannot be appended twice.
 */
offset: number, 
/**
 * Hits found so far. Keeps climbing while `running`.
 */
total: number, 
/**
 * Files with at least one hit so far — the second figure in the panel's readout.
 */
files: number, 
/**
 * Files opened and scanned so far. The only honest progress figure during a walk whose
 * size is not known in advance.
 */
scanned: number, 
/**
 * The walk is still going. The panel polls again while this is true.
 */
running: boolean, 
/**
 * The hit cap stopped the search early, so the counts are floors rather than totals.
 */
truncated: boolean, 
/**
 * An unusable pattern — an unbalanced `(` in regex mode, almost always.
 *
 * Carried on the frame instead of rejecting the command: half of every regex is
 * unparsable while it is being typed, and a rejected promise per keystroke would turn
 * ordinary typing into a stream of errors in the log.
 */
error: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One matching line.
 */
export type SearchHit = { 
/**
 * Absolute. What opening the hit acts on.
 */
path: string, 
/**
 * Relative to its root, prefixed with the root label in a multi-root project — the same
 * string the file picker draws, so one file is named the same in both surfaces.
 */
rel: string, 
/**
 * 1-based, as every editor and every compiler diagnostic counts lines.
 */
line: number, 
/**
 * The line's text, without its terminator, clipped to a few hundred bytes. A minified
 * bundle has single lines of megabytes and none of them belongs on the IPC channel.
 */
text: string, 
/**
 * Byte offset of the match **within `text`**.
 *
 * Bytes, not chars and not the UTF-16 units a JS string is indexed by: bytes are what
 * the engine works in, and the three agree only for ASCII. `ui/src/sidebar/SearchModel.ts`
 * splits the line with a `TextEncoder` rather than `String.prototype.slice`, which is
 * what makes the highlight land in the right place on a line with an emoji in it.
 */
start: number, 
/**
 * Exclusive end of the match, in the same units as [`Self::start`].
 */
end: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the pattern is interpreted.
 */
export type SearchMode = "literal" | "regex";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user typed, and the toggles beside the input.
 *
 * Echoed back on every [`SearchFrame`] whole, rather than only the pattern string: toggling
 * case-sensitivity without touching the text changes the answer, and a frontend that
 * compared pattern strings alone would paint the old results under the new toggle.
 */
export type SearchQuery = { pattern: string, mode: SearchMode, caseSensitive: boolean, 
/**
 * Wrap the pattern in `\b…\b`. On a literal made only of punctuation this can never
 * match, which is what `grep -w` does with the same input.
 */
wholeWord: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of one file an operation touches.
 */
export type Selection = { "kind": "whole" } | { "kind": "hunks", hunks: Array<number>, } | { "kind": "lines", lines: Array<LineRef>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the registry can still say about a session whose pane was not there to hear it die.
 *
 * This is the answer to the *rehydration* question — a pane host evicted and re-created after
 * its child had already gone, so the `cide://session-state` event fired before anything was
 * listening. That path used to ask `session_has_exited`, which answers a `bool`, and so the
 * `— exited —` marker on it never carried a number: the code existed in this process the whole
 * time and was simply never on the wire.
 *
 * Four variants because [`cide_pty`] genuinely has four states here and collapsing any two of
 * them loses the code again:
 *
 * * `Running` — the child is alive. The pane was rehydrated over a session that outlived it,
 *   which is the ordinary case and the reason the question is asked at all.
 * * `Reaping` — `has_exited()` is true but `exit_status()` is still `None`. EOF on the pty
 *   master and the reaper's `wait()` are two events on two threads, and this is the window
 *   between them. The code exists and is milliseconds away on `cide://session-state`, so the
 *   caller must decline to mark and let the event do it.
 * * `Exited` — reaped, with the status `wait()` returned.
 * * `Unknown` — the registry has never held this id. A `SessionId` restored from
 *   `workspace.json` after a restart is exactly this: the process that owned it died with the
 *   app and no code survives anywhere. **This is the only answer for which a bare
 *   `— exited —` is the truth**, and it is why this is a variant rather than an error —
 *   `NoSuchSession` would make the one honest case indistinguishable from a failed call.
 */
export type SessionExit = { "kind": "running" } | { "kind": "reaping" } | { "kind": "exited", code: number, } | { "kind": "unknown" };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A PTY-backed session. For Claude panes this is the `--session-id` uuid.
 */
export type SessionId = string;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a pane's conversation can be picked up where it left off.
 */
export type SessionRestore = { "kind": "resumable", session: SessionId, } | { "kind": "fresh" };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of a session, driven by Claude Code hooks with a PTY-quiet fallback.
 *
 * "Live session" for the close-confirm setting means `Busy | AwaitingPermission` —
 * not "the process exists", which would warn constantly.
 */
export type SessionState = { "state": "spawning" } | { "state": "splash" } | { "state": "idle" } | { "state": "busy" } | { "state": "awaitingPermission" } | { "state": "awaitingInput" } | { "state": "exited", code: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A session that would be interrupted by closing something.
 *
 * Carries enough to name it on screen without a second round trip. A dialog that says "3
 * sessions are busy" and cannot say *which* leaves the user no way to decide, so the pane
 * title and project name travel with the answer.
 */
export type SessionSummary = { session: SessionId, project: ProjectId, projectName: string, paneTitle: string, state: SessionState, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Settings = { 
/**
 * *Stack projects in the header* vs *One window per project*.
 */
windowMode: WindowMode, theme: Theme, 
/**
 * "Each project keeps its own Claude tab — pinned, cannot be closed, only its panes
 * can." Off would mean a project with no console tab, which the rest of the model
 * does not currently allow; the toggle exists in the mock and is honoured as
 * read-only-true until there is a coherent meaning for false.
 */
eachProjectKeepsClaudeTab: boolean, 
/**
 * "Reopen the last project on launch — restores its tab strip and pane layout."
 */
reopenLastProject: boolean, 
/**
 * "Keep sessions running when a project window is closed."
 *
 * Deliberately *not* worded as the mock's "keep a project running when its window is
 * closed — live Claude sessions survive in the background". cide runs no background
 * daemon: quitting the app quits its Claude sessions, and the workspace is restored on
 * relaunch via `claude --resume`. Promising background survival would be a lie.
 */
keepSessionsOnWindowClose: boolean, 
/**
 * "Confirm before closing a project with a live session." *Live* means a session is
 * `Busy` or `AwaitingPermission` — not merely that a process exists, which would warn
 * constantly.
 *
 * Read by `cide_app::cmd::app::app_quit_requested`, and by nothing else. Its whole
 * authority is over the `blocking` half of `QuitDecision`: off, and a close no longer
 * asks about an agent mid-turn.
 *
 * It governs **sessions only**, and specifically not unsaved file tabs, which are
 * reported whatever it says. The two are different kinds of loss. Interrupting a turn
 * costs the turn — the conversation is keyed by `SessionId` and resumes with
 * `claude --resume` — so a user may reasonably decide they do not want to be asked.
 * Discarding an unsaved buffer costs the work outright, with nothing to resume from,
 * and a toggle whose label says "live session" must not quietly turn that guard off
 * too. If unsaved edits ever need their own toggle, that is a second field with its own
 * wording, not a second meaning stapled to this one.
 */
confirmCloseWithLiveSession: boolean, editor: EditorSettings, terminal: TerminalSettings, graphics: GraphicsSettings, claude: ClaudeSettings, proxy: ProxySettings, sidebar: SidebarSettings, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A partial update to [`crate::Settings`]. `None` means "leave this alone".
 *
 * Patching is per *top-level* field: a caller changing one editor option sends the whole
 * [`EditorSettings`] it currently holds. Per-leaf patching would need a parallel type for
 * every group and buy very little — two windows editing two different editor options in the
 * same 500 ms debounce is not a case worth a type hierarchy, and the loser sees the winner's
 * value arrive on the next snapshot rather than being told nothing happened.
 *
 * `window_mode` is deliberately absent. It is stored in `Settings`, but changing it is not
 * a stored-preference edit — it redistributes every open project across OS windows, which
 * means opening and closing real windows. That work already exists as `window.set_mode`,
 * and having two commands that can move the same field would leave the desktop agreeing
 * with the workspace only when the user happened to use the right one. The radio cards call
 * `window.set_mode`.
 */
export type SettingsPatch = { theme?: Theme, eachProjectKeepsClaudeTab?: boolean, reopenLastProject?: boolean, keepSessionsOnWindowClose?: boolean, confirmCloseWithLiveSession?: boolean, editor?: EditorSettings, terminal?: TerminalSettings, graphics?: GraphicsSettings, claude?: ClaudeSettings, 
/**
 * Proxy configuration. Sent whole like every other group, which for this one also means
 * the URLs — credentials included — cross the IPC boundary on every keystroke-debounced
 * save. That is the same trip `settings.get` already makes in the other direction, and
 * the boundary is in-process; see [`crate::settings::ProxySettings`] for what is done
 * about the value once it is at rest.
 */
proxy?: ProxySettings, 
/**
 * Both sidebar widths, sent together.
 *
 * Per the rule above: a patch is per top-level field, so the splitter that just moved
 * the explorer sends the git width it currently holds alongside it. That is not a
 * theoretical loss of the other panel's value — the splitter reads both out of the same
 * settings snapshot it renders from, so "currently holds" is the mirror's value and not
 * a stale local copy.
 */
sidebar?: SidebarSettings, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsSection = "appearance" | "projectsAndWindows" | "keymap" | "claudeSessions" | "editor" | "git" | "terminal";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One shelved patch. Ours, not git's — see `cide-git::shelf` for why they are separate.
 */
export type ShelfEntry = { id: string, name: string, 
/**
 * Unix seconds.
 */
created: bigint, files: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which half of a new split the freshly created pane occupies.
 */
export type Side = "before" | "after";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How wide the user left each sidebar panel.
 *
 * **Two widths, not one.** The mock gives the explorer 252px and the git panel 420px, and
 * that difference is a property of the content, not a stylistic accident: the explorer
 * draws one truncatable name per row, while the git panel draws a path *and* an
 * added/removed figure *and* a stage checkbox on the same line. Sharing a single number
 * would mean every switch between the two views resized the workspace under the user, and
 * whichever panel they had not tuned would be the wrong width — so the resize would feel
 * like it had been forgotten rather than remembered.
 *
 * Only these two, because only these two are tokens: `--w-sidebar-files` also sizes the
 * search and problems panels (they are the explorer's column with different rows in it),
 * which is a decision `tokens.css` already made and this type follows rather than reopens.
 */
export type SidebarSettings = { 
/**
 * `--w-sidebar-files`: the explorer, and with it search and problems.
 */
filesWidth: number, 
/**
 * `--w-sidebar-git`.
 */
gitWidth: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One interior node of a pane tree; carries the split ratio.
 */
export type SplitId = string;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a newly split pane should contain.
 *
 * This enum *is* the multiplexing model: "one session but splittable" resolves as one
 * **primary** session plus panes that each declare what they want.
 */
export type SplitIntent = { "kind": "newClaude" } | { "kind": "forkPrimary" } | { "kind": "mirror", session: SessionId, } | { "kind": "shell" };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a split produced.
 *
 * The resolved intent travels back with the pane id because the caller may not know it: a
 * `None` intent asks the domain for the tab's default, and the frontend still has to spawn
 * the right thing afterwards. Returning only the id would leave it guessing — and guessing
 * `NewClaude` where the domain said `ForkPrimary` starts a fresh conversation where the
 * user asked to branch an existing one.
 */
export type SplitOutcome = { pane: PaneId, intent: SplitIntent, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of `git stash list`.
 */
export type StashEntry = { index: number, message: string, oid: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A workspace tab.
 *
 * **Every** tab carries a `PaneTree`, including file tabs. That is what makes "split the
 * editor right" and "promote this pane to a full tab" the same code path instead of two.
 */
export type Tab = { id: TabId, kind: TabKind, tree: PaneTree, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One workspace tab inside a project.
 */
export type TabId = string;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TabKind = { "kind": "claudeHome" } | { "kind": "claudeFull", title: string, } | { "kind": "file", path: string, dirty: boolean, } | { "kind": "diff", spec: DiffSpec, 
/**
 * A **preview** tab: the one slot a single click in the git panel is allowed to
 * re-point at another file. VS Code's preview tab, and taken deliberately.
 *
 * > *"Only when diff is already opened one click should change current diff to
 * > selected file."*
 *
 * "Change *the* current diff" needs an answer to "which one", and the answer has to
 * survive several diff tabs being open at once. Two candidates lost. *The active
 * tab* means a diff the user opened on purpose and then walked away from gets
 * silently re-pointed the moment they come back to it — the click that was supposed
 * to be cheap eats the tab they were comparing against. *The most recently focused
 * one* needs a focus history that `Workspace` does not record and that nothing else
 * would ever read.
 *
 * So the slot is marked instead of inferred, and the mark is set by the gesture
 * that made the tab: a double-click (`tab_open_diff`) means "open this properly"
 * and produces `preview: false`; a single click (`tab_retarget_diff`) reuses the
 * preview tab, or creates one when there is none. That is the symmetry the panel
 * already had — double-click has meant "open properly" since the click rules landed
 * — and it makes the count the user complained about fall from thirty to one.
 *
 * Always `false` for a [`DiffOrigin::ClaudeMcp`] tab, and
 * `cide_core::workspace::retarget_diff` refuses one outright: that tab is holding an
 * agent turn open on a promise about *one* file, and re-pointing it would leave the
 * CLI blocked on a diff nobody can answer.
 *
 * `#[serde(default)]` because this variant is older than the field — unlike
 * [`DiffOrigin::Git`]'s fetch key, `TabKind::Diff` has been reachable through
 * Claude's `openDiff` since M7, so `workspace.json` files carrying the field-less
 * form exist. Defaulting to `false` reads them as what they are: tabs nobody
 * designated as scratch.
 */
preview: boolean, } | { "kind": "settings", section: SettingsSection, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalRenderer = "auto" | "webgl" | "dom";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalSettings = { 
/**
 * Point size for the terminal's mono face. See [`EditorSettings::font_size`] for the type.
 *
 * Defaults **equal to the editor's**, which is a decision rather than a coincidence:
 * `tokens.css` unified the two because a terminal beside an editor at a half-pixel
 * difference reads as two typefaces, and that shipped once already. Two controls means
 * they *can* diverge; nothing should make them diverge on their own.
 */
fontSize: number, scrollback: number, 
/**
 * Which xterm.js renderer to prefer.
 *
 * A setting rather than a probe because the healthy and unhealthy paths are
 * indistinguishable from JavaScript: WebGL context creation succeeds even on a
 * software rasterizer, and `WEBGL_debug_renderer_info` is masked — on Linux it reports
 * "Apple GPU" regardless of hardware.
 */
renderer: TerminalRenderer, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which theme the webview should paint.
 *
 * **Light is the default, by explicit user instruction** — it used to be `Dark`. The
 * default is read in more places than the settings screen: `Settings` is `#[serde(default)]`
 * throughout, so it is also what a `workspace.json` with no `theme` key deserializes to,
 * and it is what `windows.rs` bakes into `?theme=` before a webview exists. Flipping it
 * here is what makes a fresh install open white.
 *
 * The variant order is the mock's Appearance segmented control, and it stays Dark-first
 * even though Dark is no longer the default: ts-rs emits the union in declaration order,
 * and reordering would rewrite `generated.ts` for a cosmetic reason.
 */
export type Theme = "dark" | "light";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the flattened, windowed file tree.
 */
export type TreeRow = { path: string, 
/**
 * The last component, which is all the row draws.
 */
name: string, 
/**
 * Indent level. 0 is a top-level row: a project root when the project has several, the
 * root's own children when it has one.
 */
depth: number, kind: TreeRowKind, 
/**
 * Only meaningful for directories.
 */
expanded: boolean, 
/**
 * Whether to draw a twisty. A directory that walked to nothing (empty, or entirely
 * ignored) gets none, so clicking it cannot appear to do nothing.
 */
hasChildren: boolean, 
/**
 * A symlink is shown as a link rather than followed: the walk does not descend through
 * one, so its subtree is not in the index and must not be drawn as expandable.
 */
symlink: boolean, 
/**
 * Index into `Project::roots`. The tree colours and groups by root in a multi-root
 * project, and needs this without re-deriving it from path prefixes on every row.
 */
root: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TreeRowKind = "dir" | "file";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The status the file tree draws in its one-letter tag column.
 *
 * Deliberately *not* [`FileState`]. The commit panel needs both sides of the index because a
 * tri-state checkbox is a function of the pair; the file tree has one 9px column and has to
 * answer "what happened to this path" with a single letter. Two types rather than one lossy
 * shared one, because collapsing the pair is exactly the bug `ChangeEntry` exists to avoid
 * and re-deriving that collapse in TypeScript would put the rule somewhere it cannot be
 * tested against a real repository.
 *
 * The variants are the mock's — `M` blue, `A` green, `D` faint and struck through — plus
 * the two the tree can hold that the mock does not draw. Every one of them is reachable;
 * see `cide_git::tree_status` for what produces each.
 */
export type TreeStatus = "clean" | "modified" | "added" | "deleted" | "untracked" | "ignored";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-path git status for the file tree, keyed by the same absolute path a [`TreeRow`]
 * carries.
 *
 * [`TreeRow`]: crate::TreeRow
 *
 * # Why absolute paths and not repo-relative ones
 *
 * Every other path on this wire is repo-relative, because that is how git stores them. This
 * one is not, and the reason is that its only consumer is the file tree, whose rows are
 * keyed by absolute path. Doing the rebasing in Rust — where the project's roots, the work
 * trees above them and the submodules below them are all known — keeps the frontend's lookup
 * a plain map hit. The alternative puts prefix arithmetic over three coordinate systems into
 * TypeScript, where it cannot be tested against a real repository and would silently produce
 * an untagged tree the first time a root was a symlink.
 *
 * # Size
 *
 * Bounded by the number of *changed* paths plus their ancestor directories, plus the paths
 * git reports as ignored — not by the size of the repository: a 100k-file checkout with four
 * edits ships a handful of entries, because an untracked or ignored *directory* travels as
 * one entry and is not recursed into. The pathological cases — a whole-tree `sed -i`, or an
 * ignore glob like `*.o` over an in-tree build — are capped, and [`Self::truncated`] says so
 * rather than letting the tail read as clean.
 */
export type TreeStatusMap = { 
/**
 * Absolute path → status. Paths absent from the map are [`TreeStatus::Clean`], except
 * under a directory that is itself `untracked` or `ignored`, whose descendants inherit
 * it — see `ui/src/sidebar/treeStatus.ts`.
 */
statuses: { [key in string]: TreeStatus }, 
/**
 * The cap was hit and the map is a prefix in path order. The entries present are still
 * correct; paths after the cut are simply untagged.
 */
truncated: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file tab whose buffer holds edits that have not been written to disk.
 *
 * The path travels with it for the same reason [`SessionSummary`] carries a pane title: a
 * dialog that says "3 unsaved files" and cannot say *which* gives the user no basis to
 * choose between discarding and going back. `title` is the basename the tab strip already
 * shows, so the dialog and the strip name the same thing; `path` disambiguates the two
 * `mod.rs` the user has open.
 */
export type UnsavedTab = { tab: TabId, project: ProjectId, projectName: string, path: string, 
/**
 * The tab strip's label — the file's basename.
 */
title: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WatchBackend = "native" | "polling";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the watcher is watching, and why.
 *
 * `Polling` is a degraded mode with a visible cost — a change can take a whole poll
 * interval to be noticed — so the reason is carried to the UI rather than logged. A user
 * whose inotify limit is exhausted can raise `fs.inotify.max_user_watches`; a user who is
 * told nothing just thinks the file tree is broken.
 */
export type WatchStatus = { backend: WatchBackend, 
/**
 * Set only when `backend` is `polling`. A sentence, meant for a banner.
 */
reason: string | null, 
/**
 * Directories under an explicit watch. Zero in polling mode, which watches roots
 * recursively instead.
 */
watchedDirs: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Tauri window label, e.g. `shell:<uuid>` or `pane:<uuid>`.
 *
 * Kept as a string rather than a uuid newtype because Tauri itself keys windows by label
 * and `tauri-plugin-window-state`'s `map_label` collapses the prefixes.
 */
export type WindowLabel = string;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the app is laid out across OS windows.
 */
export type WindowMode = "stacked" | "perProject";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an OS window is showing.
 *
 * The `Stacked` and `PerProject` window modes are nothing more than two different
 * mappings from `ProjectId` to `WindowRole::Shell` over identical state — which is why
 * flipping the setting touches no project, tab, pane or session.
 */
export type WindowRole = { "kind": "shell", projects: Array<ProjectId>, active: ProjectId | null, } | { "kind": "detachedPane", project: ProjectId, tab: TabId, pane: PaneId, } | { "kind": "detachedTab", project: ProjectId, tab: TabId, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The persisted root. Everything durable hangs off this.
 */
export type Workspace = { 
/**
 * Bumped by `cide-core::persist` when the on-disk shape changes, so an old file can
 * be migrated rather than silently misread.
 */
schemaVersion: number, 
/**
 * Bumped on every mutation. Every event carries it, so the frontend can discard a
 * snapshot that arrived out of order.
 */
rev: bigint, settings: Settings, 
/**
 * Insertion order **is** the header tab order.
 */
projects: { [key in ProjectId]: Project }, windows: { [key in WindowLabel]: WindowRole }, };
