// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Harness } from "./Harness";

/**
 * makes the common case one click.
 */
export type AgentModels = { 
/**
 * Which harness this list describes, echoed back.
 *
 * Echoed for the reason `cmd::settings::ClaudeCliSupport::binary` is: the answer describes
 * *this* harness, and a form that captioned it with whatever its dropdown currently says
 * would label one CLI's models with the other's name for as long as a probe was in flight —
 * which is exactly the moment the user is switching between them.
 */
harness: Harness, 
/**
 * The ids, in the order the harness names them. Empty is a legal answer and not an error.
 */
models: Array<string>, 
/**
 * Why there is no list, as a sentence — or `None`.
 *
 * A sentence about the *machine* ("opencode is not on this app's PATH"), never a refusal
 * about the draft: it is drawn as the field's hint and never as an
 * [`AgentDraftProblem`], because nothing the user typed caused it and nothing they can type
 * in this form fixes it. The box stays editable either way.
 */
problem: string | null, 
/**
 * Whether this harness's CLI takes a pool entry's effort variant inside the model id
 * (`--model o3/Qwen-Coder#xhigh`, opencode 2) rather than as `--variant xhigh` (opencode 1,
 * MiMo). The pool screen's argv readout spells it this way; it said `--variant` for a CLI
 * that answers that flag with `Unrecognized flag`, over the exact argv t-1090 died on.
 * `false` for a harness with no variant at all.
 */
variantInModel: boolean, };
