// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { AgentScope } from "./AgentScope";
import type { Harness } from "./Harness";

/**
 * One role, as the panel draws it.
 *
 * The wire projection of `.cide/agents/<name>.md` (or its global twin beside `keymap.json`) —
 * not that file's parse tree. The fields the definition carries that only a spawn cares about
 * (`tools`, `permission-mode`, `effort`, the origin path) stay in `cide-agents`, because a
 * roster row cannot act on them.
 */
export type AgentDef = { 
/**
 * The role name, which is also the file stem — see [`AgentId`].
 */
id: AgentId, 
/**
 * What the row says. Title-cased from the id unless the file gives one, so a roster is
 * readable before anybody has thought about presentation.
 */
label: string, 
/**
 * Which of the four directories this definition was read from. (M30)
 *
 * # Why a roster row carries it when `origin`/`shadows` deliberately do not
 *
 * `LoadedAgent`'s doc has flagged for two milestones that the panel genuinely wants those
 * two paths and that adding them "would be a reasonable addition to `AgentDef` when someone
 * is next in there". This is the half that earned its way across, and a *path* is still not
 * what crosses: a scope is a closed enum the frontend can switch on, where a path is a
 * string it would have to parse to learn anything.
 *
 * What reads it is the roster's badge: a [`AgentScope::is_claude_code`] role is drawn
 * **Claude Code**, because a definition cide did not author, cannot fully model, and applies
 * through `--agent` rather than through its own flags is a fact the user has to be able to
 * see without opening anything.
 *
 * **It does not replace the Settings screen's per-scope probing**, and that is worth saying
 * because it looks as though it should. That screen issues one `agents_draft` per scope per
 * name, which is not a lookup of something this field already knows: a roster row is the
 * *merged* answer, one entry per name, so it names the scope that **won** and is silent
 * about the file it shadowed. Listing both is the whole point of that screen — a shadowed
 * definition must never be invisible — so the probe answers a question this field cannot.
 */
scope: AgentScope, harness: Harness, 
/**
 * One line, from the front matter's `description`. What the role is *for*, in the author's
 * own words — the orchestrator is given this verbatim when it asks what agents it has, so
 * it is prompt text as much as it is UI text.
 */
description: string, 
/**
 * The role's system prompt: the body of the markdown file, verbatim.
 *
 * **Carried on the wire although nothing in the frontend executes it**, because the panel
 * shows it folded and read-only. It is the only way a user can tell two roles apart once
 * they have edited the file — `description` is one line the author wrote early and rarely
 * revisits, while the prompt is the thing they actually tune. A roster that lists names
 * without them is a list of words.
 *
 * Read-only in the panel, deliberately: an editor here would be a second way to write a
 * committed file, racing `git` and the user's own editor for it.
 */
systemPrompt: string, 
/**
 * A model alias or full name from the definition. `None` means the harness's own default,
 * which is the right answer for a role whose author did not care.
 */
model: string | null, 
/**
 * The role's colour, as one of the eight hue names in `AgentsPanel/model.ts`'s `AGENT_HUES`
 * — or `None`, which means *derive one from the name*. (M75)
 *
 * # A presentation hint that cide reads and never writes
 *
 * `color` is **Claude Code's own front-matter key**, and [`AgentExtra`] already carries it
 * through a save untouched — `claude_corpus` asserts it by name among the keys cide does not
 * model. That does not change here, in either dialect: the key stays an extra, `render` goes
 * on emitting it verbatim from the source lines it occupied, and this field is a *read* of
 * it taken on the way past. Modelling it properly would mean cide re-spelling a key with its
 * own quoting rules in a committed file it did not author, to gain nothing a colour needs.
 *
 * So the value is normalised (trimmed, lowercased) and matched against the eight names; a
 * value that is not one of them — `automatic`, a hex, a typo, a colour Claude adds next
 * month — is `None` and the name's hash answers instead. Never a
 * [`Self::unavailable`] sentence: a role that could not be dispatched over a colour would be
 * absurd, and a role with no colour is exactly the ordinary case.
 *
 * It is deliberately **not** in `cide_agents::overrides::ChildSettings`. That type's
 * equality decides whether a paused run must be re-forked, and recolouring a role must not
 * cost somebody an in-flight turn.
 */
color?: string, 
/**
 * Why this role cannot be dispatched, as a sentence — or `None` when it can.
 *
 * **This is [`crate::Command::unavailable`] one layer down, and for the identical reason.**
 * A role whose harness binary is not on `PATH`, whose system prompt is empty, or which two
 * config files declared under one name, is drawn greyed **with this sentence** and gets no
 * Dispatch button at all — never a button that is offered and then refused, and never a
 * greyed row with nothing saying why.
 *
 * This project has paid for the listed-and-silently-inert state twenty-four times over
 * (`cide_core::commands`' note records the count), and the answer there is the answer here:
 * make it unrepresentable. `AgentsPanel/model.ts`'s `canDispatch` returns exactly one of a
 * green light or a sentence, never neither, and `check-agents.mjs` fails if it can return
 * both.
 *
 * A role is never *hidden* for being unavailable. "We could not tell" and "it is not there"
 * must stay distinguishable, and a role that vanished when its CLI was uninstalled would
 * look like a role the user had deleted.
 */
unavailable: string | null, 
/**
 * How many runs of this role may be live at once.
 *
 * Per role rather than only globally, because roles differ: a `qa` that reads and reports
 * parallelises more safely than a `developer` rewriting files. The declared number is the
 * enforced number under both isolations — worktrees are per (role, task), so parallel
 * tasks are parallel checkouts and the old clamp-to-1 is gone with its premise; what
 * cannot run twice is two children in *one* checkout, which the registry's admission gate
 * holds in the queue.
 */
maxConcurrent: number, 
/**
 * `worktree:` — whether this role's runs take a worktree under the project's worktree
 * isolation, default `true`.
 *
 * `false` opts the role out: its runs stand in the **project root**, on the user's own
 * checked-out branch, beside the user's own uncommitted changes. That is the right shape
 * for a role that only reads — a reviewer, a reporter — and the wrong one for anything
 * that edits, which is why it is per role and opt-*out*: the safe posture stays the
 * default and the file has to say otherwise. An opted-out role has no `cide/<role>`
 * branches and nothing to integrate — its work, if any, lands directly where the user is.
 * Under `isolation: shared` the flag is meaningless and ignored.
 */
worktree: boolean, };
