// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which box on the form a refusal belongs to.
 *
 * The whole reason [`AgentDraftProblem`] is not a string. A save that answers "invalid" leaves
 * the user to find which of eleven fields it meant, and the fields that actually get refused —
 * a name that cannot be a directory component, a permission mode from a different CLI's
 * vocabulary — are exactly the ones whose rule is not visible from the box.
 *
 * Variants are the draft's field names, so a frontend can key an error map by them without a
 * translation table, and adding a field to [`AgentDraft`] without a variant here is a field
 * whose refusals have nowhere to land.
 */
export type AgentField = "scope" | "name" | "label" | "harness" | "description" | "model" | "effort" | "tools" | "permissionMode" | "maxConcurrent" | "systemPrompt";
