// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { Harness } from "./Harness";

/**
 * One role, as the panel draws it.
 *
 * The wire projection of `.cide/agents/<name>.md` (or its global twin beside `keymap.json`) —
 * not that file's parse tree. The fields the definition carries that only a spawn cares about
 * (`tools`, `permission-mode`, `effort`, the origin path) stay in `cide-agents`, because a
 * roster row cannot act on them.
 */
export type AgentDef = { 
/**
 * The role name, which is also the file stem — see [`AgentId`].
 */
id: AgentId, 
/**
 * What the row says. Title-cased from the id unless the file gives one, so a roster is
 * readable before anybody has thought about presentation.
 */
label: string, harness: Harness, 
/**
 * One line, from the front matter's `description`. What the role is *for*, in the author's
 * own words — the orchestrator is given this verbatim when it asks what agents it has, so
 * it is prompt text as much as it is UI text.
 */
description: string, 
/**
 * The role's system prompt: the body of the markdown file, verbatim.
 *
 * **Carried on the wire although nothing in the frontend executes it**, because the panel
 * shows it folded and read-only. It is the only way a user can tell two roles apart once
 * they have edited the file — `description` is one line the author wrote early and rarely
 * revisits, while the prompt is the thing they actually tune. A roster that lists names
 * without them is a list of words.
 *
 * Read-only in the panel, deliberately: an editor here would be a second way to write a
 * committed file, racing `git` and the user's own editor for it.
 */
systemPrompt: string, 
/**
 * A model alias or full name from the definition. `None` means the harness's own default,
 * which is the right answer for a role whose author did not care.
 */
model: string | null, 
/**
 * Why this role cannot be dispatched, as a sentence — or `None` when it can.
 *
 * **This is [`crate::Command::unavailable`] one layer down, and for the identical reason.**
 * A role whose harness binary is not on `PATH`, whose system prompt is empty, or which two
 * config files declared under one name, is drawn greyed **with this sentence** and gets no
 * Dispatch button at all — never a button that is offered and then refused, and never a
 * greyed row with nothing saying why.
 *
 * This project has paid for the listed-and-silently-inert state twenty-four times over
 * (`cide_core::commands`' note records the count), and the answer there is the answer here:
 * make it unrepresentable. `AgentsPanel/model.ts`'s `canDispatch` returns exactly one of a
 * green light or a sentence, never neither, and `check-agents.mjs` fails if it can return
 * both.
 *
 * A role is never *hidden* for being unavailable. "We could not tell" and "it is not there"
 * must stay distinguishable, and a role that vanished when its CLI was uninstalled would
 * look like a role the user had deleted.
 */
unavailable: string | null, 
/**
 * How many runs of this role may be live at once.
 *
 * Per role rather than only globally, because roles differ: a `qa` that reads and reports
 * parallelises more safely than a `developer` rewriting files. The declared number is the
 * enforced number under both isolations — worktrees are per (role, task), so parallel
 * tasks are parallel checkouts and the old clamp-to-1 is gone with its premise; what
 * cannot run twice is two children in *one* checkout, which the registry's admission gate
 * holds in the queue.
 */
maxConcurrent: number, 
/**
 * `worktree:` — whether this role's runs take a worktree under the project's worktree
 * isolation, default `true`.
 *
 * `false` opts the role out: its runs stand in the **project root**, on the user's own
 * checked-out branch, beside the user's own uncommitted changes. That is the right shape
 * for a role that only reads — a reviewer, a reporter — and the wrong one for anything
 * that edits, which is why it is per role and opt-*out*: the safe posture stays the
 * default and the file has to say otherwise. An opted-out role has no `cide/<role>`
 * branches and nothing to integrate — its work, if any, lands directly where the user is.
 * Under `isolation: shared` the flag is meaningless and ignored.
 */
worktree: boolean, };
