// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { Harness } from "./Harness";
import type { ProjectId } from "./ProjectId";
import type { RunId } from "./RunId";
import type { RunNotify } from "./RunNotify";
import type { RunState } from "./RunState";
import type { SessionId } from "./SessionId";
import type { TaskId } from "./TaskId";

/**
 * One dispatched execution, as the panel draws it.
 */
export type AgentRun = { run: RunId, agent: AgentId, 
/**
 * [`AgentDef::label`] **copied at dispatch, not looked up at render**.
 *
 * A history row must still read correctly after the role has been renamed or its definition
 * deleted, and a row that re-derives its label from the current roster does neither: it
 * renames itself when a config file changes, or empties when a role is removed. A row that
 * renames itself is a row that lies about what happened — the run really was dispatched
 * under the old name, and that is the name in the transcript, in `/resume` and in the
 * terminal title.
 */
agentLabel: string, 
/**
 * Copied for the same reason as [`Self::agent_label`]: the run happened on this harness
 * whatever the definition says now.
 */
harness: Harness, project: ProjectId, 
/**
 * The PTY session, once there is one.
 *
 * `None` while [`RunState::Queued`] — there is no child yet — which is exactly why the Open
 * action is *withheld* until there is, rather than drawn disabled. A queued row renders no
 * Open control at all: a control that cannot work in this state should not be on the screen
 * in it.
 *
 * It is also the join key for the phase dot. The Agents store subscribes to
 * `cide://session-state` keyed on this, so a row's colour moves at session speed with no
 * round trip and no second per-run event stream.
 */
session: SessionId | null, state: RunState, 
/**
 * The task this run was dispatched against.
 *
 * **This is the whole agent→task half of the cross-link, and it is the only stored half.**
 * The reverse — "which agent is on task t-17 right now" — is derived at render time by
 * scanning live runs for this field; see [`crate::Task::agent`], which is the role a task is
 * *for* and not a claim about the present.
 *
 * `None` is legal: an ad-hoc run — the orchestrator asking a role to check or do one small
 * thing that is not on the board. Such a run stands in the **project root**, not in a
 * worktree of its own (M40; `cide_agents::run_checkout` is the rule). The row draws
 * `no task` in dim rather than nothing, because a run nothing can account for is worth
 * seeing.
 */
task: TaskId | null, startedUnixMs: bigint, 
/**
 * Milliseconds this run has **worked**, over its closed working intervals only.
 *
 * Read together with [`Self::working_since_unix_ms`]: the figure to show is this plus, when
 * that stamp is set, the time since it. Splitting a closed total from an open stamp is what
 * lets a live row tick between broadcasts without the producer sending a new number every
 * second, and what makes a paused or finished row's figure *stop* rather than freeze at
 * whatever the last event carried.
 *
 * [`RunState::counts_as_work`] is the definition of "working", and its doc carries the
 * argument for where the line is drawn.
 *
 * **This does not replace [`Self::started_unix_ms`]**, which stays exactly what it was: the
 * moment the run was dispatched. That is a real fact, it is what the panel's History sorts
 * by, and it is what `cide_agents::tools`' run list means by `started … ago` — which was
 * never wrong, because it says "started". What was wrong was rendering it as the run's
 * duration.
 */
workedMs: bigint, 
/**
 * When the current working interval began, or `None` when this run is not working.
 *
 * `Some` in exactly the states [`RunState::counts_as_work`] admits, which is the invariant
 * `cide_app::agents::move_to` exists to keep — it is the only thing in the process that
 * assigns a run's state, and it opens and closes this stamp on the transition.
 *
 * Deliberately **not** persisted across a cide restart. Every restored run comes back
 * `Interrupted`, which is not working, so this is `None` by construction and the hours cide
 * spent shut add nothing to the figure — the offline case needs no snapshot timestamp and
 * no code of its own.
 */
workingSinceUnixMs: bigint | null, 
/**
 * Where cide announces this run's turn endings — the nudge `agent_rpc::note_run_over` types
 * into a Claude pane. Recorded at dispatch and carried on the wire so the run list can say
 * which runs will never announce themselves. (M40)
 */
notify: RunNotify, 
/**
 * The run was frozen long enough that its in-flight model request may have timed out.
 *
 * **A field on the run, not an event**, and that is the load-bearing part. A window opened
 * *after* the resume has no history to derive this from, so an event-only design shows
 * nothing in the new window where the old one shows a warning — the exact failure
 * `cide://session-awaiting`'s doc records and answers by broadcasting the whole set. State
 * that a late-joining window must agree about belongs in the snapshot.
 *
 * A *suspicion*, surfaced as an offer, never an automatic re-dispatch: cide cannot see the
 * model request, only a process that was stopped and continued, and a re-dispatch would
 * double-bill a turn that in fact survived. The user answers Retry or Leave it, and
 * `agents_ack_stale_turn` clears it.
 */
staleTurn: boolean, 
/**
 * One line of extra context for the row — what the queue is waiting on, which worktree this
 * run holds. `None` for the ordinary case, which is most of them.
 */
note: string | null, 
/**
 * Whether **Open** has anything to show for this run. (M42)
 *
 * The gate the panel reads, and it is a field rather than a rule the panel derives from
 * [`Self::session`] because `session` stopped being the whole answer: a finished `opencode`
 * run's child is gone and its cide session with it, yet its conversation (`ses_…`) can be
 * re-opened in the real harness, and a finished `claude` run restored after a restart has
 * no session at all while its transcript sits on disk. The registry computes this from what
 * it holds in memory — a session it still owns, or a conversation it has confirmed can be
 * re-opened — so a roster broadcast costs no filesystem read. `false` for a queued run,
 * which is what keeps Open *withheld* there rather than drawn disabled.
 *
 * What Open then does is a second question with three answers — see [`RunOpen`].
 */
openable: boolean, 
/**
 * The model this run is on, `provider/model` where the harness spells it that way. (M89)
 *
 * **The run's, never the role file's.** After a local override or a pool failover the file
 * names what the *next* dispatch would get; this names what the child was actually told,
 * resolved by the same ladder as [`LogRunInfo::model`] so the panel's row and the log card
 * never disagree. `None` where nothing chose one and the harness picked its own default —
 * the row then draws the harness alone rather than guessing a name.
 */
model: string | null, 
/**
 * The pool that chose [`Self::model`] and how far down it the run is — `fast entry 2 of 3`.
 * (M89) `None` for a run with no pool, which is every harness but opencode today.
 *
 * A field rather than the sentence it used to be inside [`Self::note`]: a pool is the
 * standing fact of what the run is on, and a note is for events. A row that has to parse
 * prose to learn its model is a row that breaks on the next rewording.
 */
poolPosition: string | null, };
