// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentDef } from "./AgentDef";
import type { AgentRun } from "./AgentRun";

/**
 * What cide knows about a project's subagents right now.
 *
 * A tagged union with a first-class `Disabled`, on [`crate::DiagnosticsSnapshot`]'s argument:
 * an empty `runs` array cannot say whether orchestration is **off**, **on with no roles
 * defined**, or **on with roles and nothing running**, and those want three different screens.
 * The first of them is not an edge case either — **subagents are off by default, so the state
 * most users see first is precisely the one an array cannot express**, and it is the state that
 * most needs prose.
 */
export type AgentRoster = { "kind": "disabled", hint: string, configPath: string, } | { "kind": "empty", configPath: string, } | { "kind": "ready", agents: Array<AgentDef>, 
/**
 * Live runs first, then finished ones, in the order the panel's five groups read
 * (Running, Idle, Queued, Roles, Recent).
 */
runs: Array<AgentRun>, 
/**
 * Whether the queue will start anything new.
 *
 * **Distinct from "every run is paused", and the difference is what the user is about
 * to act on.** Pausing does two things — it closes the dispatch queue *and* it freezes
 * the children — and a project with the queue shut but nothing running looks identical
 * to an idle one unless this is on the wire. A user who reaches for Resume needs to
 * know which of the two they are looking at, and the panel header is the only control
 * that is reachable when the console pane itself is frozen.
 */
dispatching: boolean, };
