// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far one artifact has got.
 */
export type ArtifactState = "done" | "skipped" | "ready" | "blocked";
