// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";

/**
 * Where an attachment goes. Inbound. (M39)
 *
 * Three shapes because there are three gestures: files dropped on the card body, files added to
 * a comment that already exists, and files that ride along with a comment being written — the
 * composer's "report with a screenshot", which must land as **one** mutation so a refused file
 * never leaves a comment behind that names an attachment it does not have.
 */
export type AttachTarget = { "kind": "task" } | { "kind": "comment", id: CommentId, } | { "kind": "newComment", text: string, };
