// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

/**
 * One entry of the *finished and not yet looked at* set.
 *
 * The stamp is what makes a **local** notification correct, and a bare set of ids cannot do it.
 * A device that was asleep when a turn ended reconnects to a set, and has to decide whether each
 * entry is news. Without a stamp it can only choose between announcing everything it sees (a
 * notification every time the socket drops and comes back) and announcing nothing it has seen
 * before (silence for a session that went busy and finished *again* while it was away). With
 * one, the rule is a comparison: newer than the last one announced for that session is news.
 *
 * It is written when the session *enters* the set and never touched while it stays there —
 * every window observes the same transitions and reports them, and a repeat report that moved
 * the stamp would make one session's single wait look like a stream of them.
 */
export type AwaitingEntry = { session: SessionId, 
/**
 * Milliseconds since the epoch, as a JavaScript `number` rather than a `bigint`.
 *
 * ~1.7e12 today against a `Number.MAX_SAFE_INTEGER` of ~9.0e15, so the range is not close;
 * `a_stamp_stays_inside_a_javascript_number` pins it. `bigint` would be technically
 * truthful and would make every consumer write a cast that can only succeed — and the first
 * one to forget it gets `NaN` in a date, which is [`crate::properties`]' argument in a
 * second place.
 */
sinceUnixMs: number, };
