// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Orientation of a split. `Row` places children left/right, `Col` top/bottom.
 */
export type Axis = "row" | "col";
