// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One binding, in the layered keymap.
 */
export type Binding = { 
/**
 * A chord: `ctrl+p`, or a multi-stroke sequence like `ctrl+k ctrl+s`.
 *
 * Multi-stroke is why the frontend runs its own prefix state machine — CodeMirror's
 * `KeyBinding.key` parser handles single chords only.
 */
key: string, 
/**
 * The command id, e.g. `pane.split.right`. A leading `-` **removes** a binding
 * contributed by an earlier layer, which is how a user disables a default.
 */
command: string, 
/**
 * Context expression, e.g. `terminalFocused && !overlayOpen`. `None` means always.
 */
when: string | null, 
/**
 * Opaque payload handed to the command.
 */
args: unknown, };
