// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlameFollow } from "./BlameFollow";

/**
 * Options for one blame.
 *
 * Container-level `#[serde(default)]` so a caller that wants the ordinary answer sends `{}`,
 * and so adding an option here does not break every existing call site — the same reason
 * [`crate::settings::ClaudeCli`] carries one. The derived `Default` is safe here, unlike
 * `ClaudeInjection`'s: every field's zero value is the behaviour that was there before the
 * field existed.
 */
export type BlameRequest = { follow: BlameFollow, 
/**
 * git's `-w`. Reattributes a line whose only change was reindentation, which is the single
 * most common reason a blame gutter is useless — one reformatting commit otherwise owns
 * every line of the file.
 */
ignoreWhitespace: boolean, 
/**
 * Walk first parents only. On a merge-heavy branch this attributes a line to the merge
 * that brought it to *this* branch rather than to the commit on the side branch, which is
 * the reading someone asking "when did this land here" wants.
 */
firstParent: boolean, 
/**
 * Stop the walk at this revision — git's `--reverse` boundary in the useful direction:
 * blame the file as of an older commit rather than as of `HEAD`. `None` blames the current
 * source.
 */
newest: string | null, };
