// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How hard blame works to trace a line back past a move.
 *
 * Ordered by cost, and the cost is not linear: `CopiesAnywhere` is git's `-C -C`, which
 * searches every file in every parent commit and can take minutes on a large repository. The
 * enum exists so the expensive modes are a deliberate choice rather than something a default
 * hands to everyone.
 */
export type BlameFollow = "renames" | "movedLines" | "copiesInCommit" | "copiesAnywhere";
