// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { ColorScheme } from "./ColorScheme";
import type { Command } from "./Command";
import type { ResolvedBinding } from "./ResolvedBinding";
import type { ResolvedContributions } from "./ResolvedContributions";
import type { WindowLabel } from "./WindowLabel";
import type { WindowRole } from "./WindowRole";
import type { Workspace } from "./Workspace";

/**
 * Everything a freshly opened window needs in one round trip.
 *
 * One call rather than several: a window that has to make four requests before it can
 * paint will show three intermediate states, and on a slow IPC path that is visible.
 */
export type Bootstrap = { window: WindowLabel, role: WindowRole, workspace: Workspace, keymap: Array<ResolvedBinding>, commands: Array<Command>, capabilities: Capabilities, 
/**
 * The resolved language, server, panel and command set — builtins merged with whatever the
 * enabled extensions contribute. (M22)
 *
 * Here rather than behind its own command because it cannot be late. `foldSpecFor` is called
 * inside the editor's mount dispatch and cannot await: a fold spec that arrives one round
 * trip after first paint means the remembered scroll position is applied against unfolded
 * heights and the reader lands somewhere they did not leave. The rail has the same problem
 * in a smaller way — a button that appears a beat after the window does reads as a glitch.
 *
 * The *panel* set, not the panels' contents: no extension worker has started at this point
 * and none needs to have.
 */
extensions: ResolvedContributions, 
/**
 * The colour schemes the user has imported. (M24)
 *
 * Here for `extensions`' reason one floor down: the scheme is written onto `<html>` as
 * custom properties before the first editor mounts, and a palette that arrives a round trip
 * later is a buffer that paints in the wrong colours and then corrects itself. The compiled
 * -in `cide` scheme is deliberately *not* in this list — it is what `tokens.css` already
 * declares, so selecting it means clearing the properties rather than writing any.
 */
schemes: Array<ColorScheme>, };
