// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchInfo } from "./BranchInfo";
import type { BranchRef } from "./BranchRef";
import type { RepoInfo } from "./RepoInfo";

/**
 * Every branch of one repository, plus what `HEAD` is doing.
 *
 * One of these per repository, because a project can hold several roots and each root its
 * submodules — and in a superproject the branch you mean is genuinely ambiguous. The
 * selector names the repository whenever there is more than one.
 */
export type BranchList = { repo: RepoInfo, 
/**
 * The same [`BranchInfo`] the status bar reads, so the widget and the popup cannot
 * disagree about what is checked out.
 */
head: BranchInfo, 
/**
 * Local branches, most recently committed first.
 */
local: Array<BranchRef>, 
/**
 * Remote-tracking branches, same order. `origin/HEAD` is dropped: it is a symbolic ref
 * that duplicates whichever branch it points at.
 */
remote: Array<BranchRef>, };
