// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One branch as the selector draws it.
 *
 * Local and remote-tracking branches share this shape because the popup treats them the
 * same way: both are things you can check out, branch from, and read a tip line for. The
 * difference is [`Self::remote`], and it is what decides whether *Rename* and *Delete* are
 * offered — those write `refs/heads/`, and a remote-tracking ref is a cache of somebody
 * else's repository.
 */
export type BranchRef = { 
/**
 * Short name: `main`, or `origin/main` for a remote-tracking branch.
 */
name: string, remote: boolean, 
/**
 * This is `HEAD`. At most one entry in a [`BranchList`] has it.
 */
current: boolean, 
/**
 * `origin/main`, for a local branch that has one.
 */
upstream: string | null, 
/**
 * Commits on this branch that its upstream does not have, and vice versa. Both zero
 * for a remote-tracking branch, which is nobody's downstream.
 */
ahead: number, behind: number, 
/**
 * Abbreviated tip oid, 8 hex digits.
 */
tip: string, 
/**
 * Summary line of the tip commit — the second line of a branch row.
 */
subject: string, 
/**
 * Committer time of the tip, unix seconds. The popup sorts by it, because the branch
 * you want next is nearly always one of the handful you touched last.
 */
committed: bigint, };
