// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an extension is allowed to reach.
 *
 * A closed set, and closed is the point: an unknown capability in a manifest greys the extension
 * with the list in the sentence, because a build that silently ignored one would run an
 * extension under *less* restriction than its author declared and believed.
 *
 * The gate is at **use**, never at load. An extension asking for [`Capability::ProcessSpawn`]
 * still appears in the panel, still shows what it contributes, and is refused the moment it
 * tries — the rule `cide_agents::dispatch_refusal` follows for `bypassPermissions`, and for its
 * reason: refusing at load makes the row *vanish*, and a user cannot grant a permission to
 * something they cannot see.
 */
export type Capability = "editorRead" | "editorWrite" | "fsRead" | "gitRead" | "processSpawn";
