// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeName } from "./ChangeName";

/**
 * One active change, as the board lists it.
 */
export type ChangeSummary = { name: ChangeName, 
/**
 * Ticked and total checkboxes across the change's tracked-tasks artifact.
 *
 * **`total == 0` does not mean "complete"**, it means the checklist has no tasks yet, and
 * the two must never be rendered the same. The Review hop keys off exactly this pair and
 * fires only on `total > 0 && completed == total`.
 */
completedTasks: number, totalTasks: number, 
/**
 * The CLI's own word for where the change is (`no-tasks`, `in-progress`, `complete`).
 * Carried as a string rather than an enum: it is upstream's vocabulary, it can grow in a
 * point release, and a variant cide has not heard of must render as itself rather than
 * vanish into an `Unknown` arm.
 */
status: string, lastModified?: string, };
