// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileState } from "./FileState";

/**
 * One changed path.
 *
 * Carries *both* sides — `index` is HEAD→index, `worktree` is index→workdir — because the
 * tri-state checkbox in the commit tree is a function of the pair, and collapsing them to
 * one status is what makes a partially-staged file render as a lie.
 */
export type ChangeEntry = { path: string, 
/**
 * The pre-rename path, when git found a rename.
 */
origPath: string | null, index: FileState, worktree: FileState, 
/**
 * True when the index differs from HEAD for this path.
 */
staged: boolean, 
/**
 * libgit2 called at least one side binary. Hunk and line staging are refused.
 */
binary: boolean, 
/**
 * A gitlink. Its own changes appear under its own `RepoInfo`, not here.
 */
submodule: boolean, 
/**
 * The changelist that owns this path. Untracked and ignored entries carry the
 * changelist they *would* join if staged, which is always the active one.
 */
changelist: string, };
