// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one run of a gate or a verify command answered.
 */
export type CheckResult = { 
/**
 * The command, as run.
 */
command: string, 
/**
 * Exit 0 within the timeout.
 */
passed: boolean, 
/**
 * `None` when the process was killed (a timeout, a signal) rather than exiting.
 */
exitCode?: number, timedOut: boolean, 
/**
 * The last lines of combined output, which is where every test runner prints its verdict.
 */
tail: string, startedUnixMs: number, durationMs: number, 
/**
 * The commit that was checked, when the directory is a git checkout.
 */
head?: string, };
