// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a checkout actually did.
 */
export type CheckoutOutcome = { 
/**
 * The local branch that is now checked out.
 */
branch: string, 
/**
 * A local branch was created to track a remote one — `origin/feature` → `feature`.
 */
createdFromRemote: string | null, 
/**
 * The stash entry that was made, when the mode asked for one.
 */
stashed: string | null, 
/**
 * The stash was made, the switch succeeded, and the changes could **not** be put back.
 * They are in `git stash list`; this is git's own message for why.
 */
restoreFailed: string | null, };
