// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Environment toggles passed to `claude` children. All default off.
 */
export type ClaudeSettings = { 
/**
 * `CLAUDE_CODE_DISABLE_MOUSE=1`. Worth offering because xterm.js has no
 * shift-to-bypass gesture for mouse capture, so a TUI that grabs the mouse takes
 * selection with it.
 */
disableMouse: boolean, 
/**
 * `CLAUDE_CODE_ALT_SCREEN_FULL_REPAINT=1`.
 */
altScreenFullRepaint: boolean, 
/**
 * `CLAUDE_CODE_DISABLE_ALTERNATE_SCREEN=1`.
 */
disableAlternateScreen: boolean, };
