// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeInjection } from "./ClaudeInjection";

/**
 * The four arguments cide adds to a Claude pane, each independently switchable.
 *
 * Four named fields rather than a map keyed by a string: the set is closed — it is exactly
 * what `cide_core::claude_cli::INJECTIONS` enumerates — and a map would let `workspace.json`
 * name an injection that does not exist, which is a setting wired to nothing.
 *
 * Hand-written `Default` for the same reason [`ClaudeInjection`]'s is; a derived one here
 * would be correct only for as long as that one stays hand-written, which is not a property
 * worth depending on.
 */
export type ClaudeInjections = { 
/**
 * `--session-id <uuid>`. Off: no stable pane-to-conversation identity, and resume stops
 * working — the CLI mints its own id and files the transcript under it.
 */
sessionId: ClaudeInjection, 
/**
 * `--resume <uuid>`. Off: a restored pane starts a fresh conversation.
 */
resume: ClaudeInjection, 
/**
 * `--fork-session`. Off: Split → fork branches nothing; it becomes a plain resume.
 */
forkSession: ClaudeInjection, 
/**
 * `--settings <inline json>`. Off: **no hooks at all** — see the toggle's own copy.
 */
settings: ClaudeInjection, };
