// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `NAME=value` pair the user asked for.
 *
 * A named struct rather than a `(String, String)` because it crosses the wire and a tuple
 * arrives in TypeScript as a positional array — `pair[0]` and `pair[1]` in the component that
 * draws the two inputs, which is one transposition away from writing the value into the name.
 */
export type ClaudeEnvVar = { name: string, value: string, };
