// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

/**
 * One imported colour scheme, resolved and total.
 *
 * What is stored on disk and what rides [`crate::Bootstrap`] are the same value: the frontend
 * writes [`colors`](Self::colors) onto `<html>` as `--tk-<role>` custom properties and every
 * surface that highlights code follows for nothing, because `highlight.css` reads those
 * properties and `HighlightStyle` was built with `class:` rather than `color:`.
 */
export type ColorScheme = { 
/**
 * Stable, filename-safe, and what [`crate::EditorSettings`] stores. Derived from the source
 * theme's own name at import.
 */
id: string, 
/**
 * What the picker shows — the theme's own `name`, kept verbatim so a user recognises it.
 */
name: string, 
/**
 * Which [`Theme`] this scheme belongs under. A scheme paints the buffer's *background*, so
 * a dark scheme under a light window would be an inverted rectangle in a white app; the
 * setting is keyed by polarity precisely so that state is unreachable.
 */
polarity: Theme, 
/**
 * Role → `#rrggbb`. Total against [`scheme_roles`] after [`ColorScheme::normalise`].
 */
colors: { [key in string]: string }, 
/**
 * Where it was imported from, for the picker's subtitle. Advisory: the file is read once,
 * at import, and never again — see the module header of `cide_core::scheme`.
 */
source?: string, };
