// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathSelection } from "./PathSelection";
import type { RepoId } from "./RepoId";

/**
 * One repository's share of the commit being described. Selections use the same
 * HEAD-to-worktree positions as `CommitRequest`; staging-area mode reads the index instead.
 */
export type CommitMessageScope = { repo: RepoId, selections: Array<PathSelection>, };
