// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitFile } from "./CommitFile";
import type { CommitTotals } from "./CommitTotals";

/**
 * The second pass: the same file list with [`LineCount`]s filled in.
 *
 * A separate response and a separate call, because the first one has to paint. A commit's file
 * list comes out of one tree diff and is fast; the line counts need a *content* diff of every
 * file in it, and on a large merge that is the difference between a pane that appears
 * instantly with numbers arriving a moment later and a pane that appears after four seconds.
 */
export type CommitLineCounts = { 
/**
 * The same paths in the same order as [`CommitDetail::files`], so the renderer patches by
 * index rather than by matching path strings — which would go wrong for the two entries a
 * rename produces.
 */
files: Array<CommitFile>, total: CommitTotals, 
/**
 * The pass ran out of time. Files past that point carry [`LineCount::TimedOut`], and the
 * totals are marked [`CommitTotals::partial`].
 */
deadlineHit: boolean, };
