// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A command the palette can run and a key can be bound to.
 */
export type Command = { 
/**
 * Stable id, e.g. `pane.split.right`. Never localised, never renamed casually — user
 * keymaps refer to it.
 */
id: string, 
/**
 * Shown in the palette, e.g. `Split pane right`.
 */
title: string, 
/**
 * Right-aligned group in the palette, e.g. `Window`, `Claude`, `Terminal`.
 */
group: string, 
/**
 * Context in which the command is applicable, same grammar as `Binding::when`.
 */
when: string | null, };
