// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The totals line under a commit's file list.
 */
export type CommitTotals = { files: number, added: number, deleted: number, 
/**
 * At least one file's [`CommitFile::lines`] is not [`LineCount::Counted`], so `added` and
 * `deleted` are a **lower bound**. The UI prefixes them with a `≥`; without this flag it
 * would state a total that is quietly wrong, which is worse than stating none.
 */
partial: boolean, };
