// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A command the palette can run and a key can be bound to.
 */
export type Command = { 
/**
 * Stable id, e.g. `pane.split.right`. Never localised, never renamed casually — user
 * keymaps refer to it.
 */
id: string, 
/**
 * Shown in the palette, e.g. `Split pane right`.
 */
title: string, 
/**
 * Right-aligned group in the palette, e.g. `Window`, `Claude`, `Terminal`.
 */
group: string, 
/**
 * Context in which the command is applicable, same grammar as `Binding::when`.
 */
when: string | null, 
/**
 * Why this command cannot run *in any context*, or `None` when it can.
 *
 * Distinct from [`when`](Self::when), and the distinction is the whole reason this
 * field exists. A `when` clause says "not right now, because of where you are" — focus
 * a Claude pane and the command works. This says "not in this build, whatever you do":
 * the capability it needs does not exist yet. The palette draws these rows greyed with
 * the reason instead of hiding them, because a user who is looking for *Restart Claude
 * session* and finds nothing concludes the app cannot do it and stops looking; a
 * disabled row with a reason tells them what is actually true.
 *
 * The alternative was to delete such commands from the registry until they work. That
 * loses twice: the id stops being reserved (so a keymap.json naming it becomes an
 * error rather than a no-op), and nothing anywhere records that the gap exists — which
 * is how ~35 dead entries came to be listed in the first place.
 *
 * Nothing may bind a key to one of these; `cide_core::commands` has a test.
 */
unavailable: string | null, };
