// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionItem } from "./CompletionItem";

/**
 * The completion list at a position — or why cide cannot offer one.
 *
 * # `Unavailable` is usually not shown to anyone, and that is the design
 *
 * Every other answer in this module exists to put a sentence in front of the user, because every
 * other one is behind a key the user pressed. This popup opens **by itself**, many times a
 * minute, so an implicit query that fails must fail *silently* — the alternative is a
 * notification storm that trains the user to ignore the notice channel entirely. Only a query
 * the user made explicitly (Ctrl+Space) reports the reason. `reason` is therefore populated
 * exactly as carefully as its neighbours' and read far less often.
 */
export type CompletionAnswer = { "kind": "items", 
/**
 * Which reply this is, for [`CompletionItem::resolve`] to name.
 *
 * Monotonic per project. A resolve quoting a token the server no longer holds is
 * answered as such rather than with an empty edit list, because "there was no import to
 * add" and "I have forgotten which item you mean" are opposite claims and only one of
 * them is safe to act on silently.
 */
token: number, items: Array<CompletionItem>, 
/**
 * LSP's `isIncomplete`: this list was computed for *this* prefix and the server wants to
 * be asked again as the user types. The client must not cache it across keystrokes.
 */
incomplete: boolean, 
/**
 * cide's own cap was hit — see `MAX_COMPLETIONS`. Distinct from `incomplete`, because
 * they are different claims: `incomplete` is the server saying "ask me again", this is
 * cide saying "I dropped some". Both independently forbid the client's fast path.
 */
truncated: boolean, } | { "kind": "unavailable", reason: string, };
