// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which compose stack a container belongs to.
 */
export type ComposeMembership = { 
/**
 * `com.docker.compose.project`.
 */
project: string, 
/**
 * `com.docker.compose.service`.
 */
service: string, 
/**
 * `com.docker.compose.project.working_dir`, when the label is present. This is what makes a
 * stack *actionable*: `docker compose` needs a directory, and the label is the only record
 * of which one the stack was brought up from.
 */
workingDir?: string, 
/**
 * `com.docker.compose.project.config_files`, split on `,`.
 */
configFiles: Array<string>, };
