// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A compose invocation, resolved and ready to be spawned in a terminal pane. (M48)
 *
 * # Why this is a plan and not a command that runs it
 *
 * Because what it produces is an **ordinary shell pane**. Everything cide already does for one —
 * the job watcher that lights the pane dot when the run finishes, the structured-log renderer,
 * the proxy environment a `pull` needs, `$EDITOR`, park-across-a-project-switch, detach into a
 * window — lives in `session_spawn`, and a second spawn site in `cmd::docker` would be a second
 * copy of all of it that drifts. So Rust answers the one question the webview cannot
 * (*which binary, and what argv*) and the generic spawn does the rest.
 *
 * It is also why there is no deadline here. `cide_docker::compose::act` runs under a ten-minute
 * ceiling because nothing is watching it; a pane is watched by a person, who can read the
 * output and press Ctrl+C.
 */
export type ComposeRun = { 
/**
 * The absolute path to the binary — `docker`, or a standalone `docker-compose`.
 */
program: string, 
/**
 * Every argument, including the `compose` word when the plugin road needs it.
 */
args: Array<string>, 
/**
 * The directory to run in, which is the compose file's own.
 *
 * Load-bearing rather than cosmetic: Compose derives the project name from the working
 * directory's basename, resolves every relative `build:` context against it, and reads the
 * `.env` beside it. Running the same file from anywhere else is a different stack.
 */
workingDir: string, 
/**
 * What the pane is called — `compose up : shop`.
 */
title: string, };
