// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a stack button, or a compose file's own action, asks for. (M43, widened in M48)
 *
 * # Why the list grew
 *
 * It used to stop at `up`, `down` and `restart`, and said so in these words: *there is no
 * `build`, `pull` or `run`, because each of those is a long-running job with output worth
 * watching, which is a pane and not a button — and until there is somewhere to watch it, a
 * button that silently spends four minutes is worse than no button.*
 *
 * M48 built that somewhere. A compose action reached from a **file** — the tree's context menu,
 * the editor's gutter, the palette — runs in a terminal pane through
 * [`crate::docker::ComposeRun`], with no deadline, its output on screen and a Ctrl+C that
 * reaches it. So the constraint is lifted rather than argued away, and the three verbs it was
 * keeping out are here.
 *
 * `Recreate` is `up` with `--force-recreate`, and it is the one that has to be its own variant
 * rather than a flag: Docker cannot change a running container, so *recreate* is the only verb
 * that answers "I edited this file, apply it" — which is the reason somebody has the file open.
 */
export type ComposeAction = "up" | "down" | "restart" | "recreate" | "build" | "pull";
