// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether stack actions can work, and the sentence when they cannot.
 */
export type ComposeAvailability = { "kind": "present", version: string, } | { "kind": "absent", reason: string, };
