// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One replacement, in cide's units — 1-based lines, 1-based UTF-16 columns, end exclusive.
 *
 * The same units [`Usage::column`] carries and for the same reason: these become CodeMirror
 * document offsets, and CodeMirror counts in UTF-16 code units. Converting once, in Rust, at the
 * point the LSP range is read is what keeps a `use` statement from landing one character off in
 * a file with a non-ASCII identifier above it.
 */
export type CompletionEdit = { line: number, column: number, endLine: number, endColumn: number, 
/**
 * May be empty — a deletion — and may contain newlines.
 */
text: string, };
