// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompletionEdit } from "./CompletionEdit";
import type { CompletionKind } from "./CompletionKind";

/**
 * One row of the completion popup.
 *
 * # What is deliberately not here
 *
 * **`documentation`.** Every server sends it, it is markdown, it is frequently a whole doc
 * comment, and a thousand-item reply carrying all of them is megabytes across an IPC channel
 * for a panel this milestone does not draw. `convert::completion` drops it at the point of
 * conversion rather than here, so nothing downstream can grow a dependency on it being present
 * and then find it truncated. When the documentation panel is built, the honest way back is
 * `completionItem/resolve` for the *selected* row — one request, not a thousand.
 */
export type CompletionItem = { 
/**
 * What the popup shows. rust-analyzer puts a signature in here — `push(…)` — so it is a
 * display string and **not** what typing is matched against. See [`Self::filter_text`].
 */
label: string, 
/**
 * What the user's typing is matched against: LSP's `filterText`, or the label when the
 * server sent none.
 *
 * Separate from `label` because for rust-analyzer they routinely differ, and using the
 * label for both is the mistake that makes a popup stop narrowing as you type — it matches
 * `push(…)` against `pus` and scores it worse than an unrelated row.
 */
filterText: string, 
/**
 * The dimmed text drawn immediately after the label, with no gap — LSP's
 * `labelDetails.detail`.
 *
 * For an auto-import candidate this is the whole reason the row is distinguishable:
 * rust-analyzer puts `(use std::collections::HashMap)` here, which is the popup's only
 * warning that accepting will also edit the top of the file. Falls back to nothing rather
 * than to `detail` below, because the two are drawn in different places and swapping them
 * puts a type where a sentence belongs.
 */
detail: string | null, 
/**
 * The type or signature, drawn away from the label — `labelDetails.description`, or the
 * item's own `detail` for a server that does not send label details.
 *
 * The fallback is what keeps a minimal server's popup from being a column of bare
 * identifiers, and it is the right way round: `detail` is *defined* as "a human-readable
 * string with additional information about this item, like type or symbol information",
 * which is what `labelDetails.description` was later carved out of.
 */
description: string | null, kind: CompletionKind, 
/**
 * The text to insert, already reduced to one form from LSP's three
 * (`textEdit.newText` → `insertText` → `label`).
 *
 * LSP snippet syntax when [`Self::snippet`] is set, plain text otherwise.
 */
insert: string, 
/**
 * [`Self::insert`] is a snippet template rather than literal text.
 */
snippet: boolean, 
/**
 * The range the insert replaces, when the server sent a `textEdit` that says so.
 *
 * `None` means "replace whatever the client thinks the current word is", which is what an
 * `insertText`-only item means and what CodeMirror does by default. Believing a server's
 * range when it sent one matters for the cases where it is *wider* than the word — gopls
 * replacing `fmt.Pri` including the dot, rust-analyzer replacing a whole `use` path.
 */
replace: CompletionEdit | null, 
/**
 * This row's rank in the server's own `sortText` order, 0 first.
 *
 * An integer and not the `sortText` string, because the string is a sort key with no meaning
 * outside a comparison — `"ffff0000"` is not a score — and the client needs a *number* to
 * hand CodeMirror as a boost. Sorting once, in Rust, is also what keeps every consumer from
 * re-implementing LSP's "absent `sortText` falls back to `label`" rule.
 */
sort: number, 
/**
 * Edits that must land with this one — the `use` line, the `import` block. Usually empty.
 *
 * Always outside the completion range, per the spec, which is what lets the client apply
 * them in their own transaction and map the insert through it.
 *
 * **Usually empty even for an auto-import row**, and that is not a bug — see [`Self::resolve`].
 */
extraEdits: Array<CompletionEdit>, 
/**
 * This row has edits that have not been computed yet: resolve it before accepting.
 *
 * `Some(index)` is the handle to pass to `diagnostics_completion_resolve`, alongside the
 * [`CompletionAnswer::Items::token`] this row arrived with.
 *
 * # Why this exists at all
 *
 * cide declares `resolveSupport: ["documentation", "additionalTextEdits"]`, which it must:
 * rust-analyzer offers **no auto-import candidates whatsoever** to a client that cannot
 * resolve edits lazily (measured — see the handshake in `cide_lsp::session`). So the import
 * edit for `HashMap` genuinely does not exist at the moment the popup is drawn, and the one
 * round trip that computes it happens when the user commits to the row.
 *
 * `None` means there is nothing deferred and accepting is instant, which is the common case:
 * a local variable, a keyword, a method already in scope. Paying a round trip on every
 * accept to cover the minority would put a language server between the user and the Tab key.
 */
resolve: number | null, 
/**
 * The server marked it deprecated, through either `deprecated` or a `tags` entry of `1`.
 */
deprecated: boolean, };
