// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One conflicted path, as the panel's *Merge Conflicts* group draws a row.
 *
 * `resolved` is *"this path once had conflict stages and no longer does"*, which is what
 * makes a resolved row stay visible with a tick rather than vanishing — a row that
 * disappears when you resolve it gives the user no way to see what they have done, and no
 * way back to a file they resolved wrongly.
 */
export type ConflictEntry = { path: string, resolved: boolean, 
/**
 * libgit2 called at least one side binary. The three-pane resolver refuses it and the
 * row offers *Yours* and *Theirs* only — see [`ConflictFile::binary`].
 */
binary: boolean, };
