// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which side of a three-way merge a one-click resolution takes.
 *
 * `Base` is offered because a delete/modify conflict sometimes has no other sensible answer,
 * and because *"put it back how it was"* is a real decision. It is not offered as a default
 * anywhere — `cide_git::conflict::take_side` does exactly what it is told.
 */
export type ConflictSide = "base" | "ours" | "theirs";
