// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The CLI a project's console runs. (M93)
 *
 * Interactive console CLIs. Their adapters provide cide session identity and lifecycle events.
 */
export type ConsoleHarness = "claude" | "codex" | "opencode";
