// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComposeMembership } from "./ComposeMembership";
import type { MountRow } from "./MountRow";
import type { Pair } from "./Pair";
import type { PortRow } from "./PortRow";

/**
 * What the detail pane shows for a container. (M47)
 *
 * Structured rather than the raw `inspect` document, which is a different surface — see
 * `TabKind::Docker`. This is the handful of fields somebody looks at; that is the whole truth
 * behind them, and both exist on purpose.
 */
export type ContainerDetail = { id: string, name: string, image: string, state: string, status: string, created: bigint, 
/**
 * The entrypoint and command, joined — what the container is actually running.
 */
command: string, ports: Array<PortRow>, mounts: Array<MountRow>, env: Array<Pair>, labels: Array<Pair>, networks: Array<string>, 
/**
 * `no`, `always`, `unless-stopped`, `on-failure`.
 */
restartPolicy: string, compose?: ComposeMembership, };
