// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionRef } from "./ExtensionRef";

/**
 * Where a contribution came from.
 *
 * On the wire because the Extensions panel has to answer *"why is my `.sql` file coloured like
 * that"* without the user reading two manifests. cide ships SQL and YAML grammars of its own, so
 * the ordinary state after installing either extension is that a builtin lost — and a user who
 * cannot see that happen has no way to tell a working extension from an inert one.
 */
export type ContributionSource = { "kind": "builtin" } | { "kind": "extension", extension: ExtensionRef, };
