// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeState } from "./MergeState";

/**
 * What happened when the user pressed *Continue*.
 */
export type ContinueOutcome = { 
/**
 * The commit that concluded a merge, or the last one a rebase wrote. Empty when a
 * rebase step produced nothing to commit.
 */
oid: string, 
/**
 * Where the operation stands now. `None` means it finished and the tree is clean.
 */
state?: MergeState, };
