// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the cursor is. Absent from a capture means hidden, not at the origin.
 */
export type Cursor = { row: number, col: number, };
