// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Checking out a commit from the log, which necessarily detaches `HEAD`.
 *
 * Its own outcome and not [`crate::git::CheckoutOutcome`], which is about branches: that type's
 * `branch` and `created_from_remote` are meaningless here, and this one's `previous` — the
 * thing to offer as a way back — has nowhere to live there. The overlapping fields keep the
 * same names and the same meanings on purpose, so the two toasts read alike.
 */
export type DetachOutcome = { 
/**
 * Short oid of the commit now checked out.
 */
head: string, 
/**
 * Its summary line, so the toast can say what you are standing on rather than only where.
 */
summary: string, 
/**
 * The branch that was checked out before, or a short oid if `HEAD` was already detached.
 *
 * The single most important field here: a detached `HEAD` is the state users most often
 * reach by accident and least often know how to leave, and this is what lets the toast
 * offer *Back to main* instead of leaving them to work it out.
 */
previous: string, 
/**
 * A stash was made to get the working tree out of the way. Same meaning as
 * [`crate::git::CheckoutOutcome::stashed`].
 */
stashed: string | null, 
/**
 * The stash was made, the checkout succeeded, and the changes could **not** be put back.
 * They are still in `git stash list`; this is git's own message for why.
 */
restoreFailed: string | null, };
