// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Diagnostic } from "./Diagnostic";
import type { SourceReport } from "./SourceReport";

/**
 * What the app knows about a project's problems right now.
 */
export type DiagnosticsSnapshot = { "kind": "unavailable", reason: string, sources: Array<SourceReport>, } | { "kind": "scanning", 
/**
 * The still-scanning sources, joined for the headline.
 */
source: string, items: Array<Diagnostic>, sources: Array<SourceReport>, } | { "kind": "ready", 
/**
 * The sources that answered, joined — "no problems" is only as good as who checked.
 */
source: string, items: Array<Diagnostic>, sources: Array<SourceReport>, 
/**
 * How many items were dropped by the emit cap.
 *
 * Non-zero means `items` is a prefix. The header counter must report
 * `items.len() + truncated`: saying `1000` when there are `1214` is the same quiet lie
 * the panel exists to avoid, one layer down.
 */
truncated: number, };
