// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which pair of trees a diff compares.
 */
export type DiffSide = "staged" | "unstaged" | "combined";
