// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineOrigin } from "./LineOrigin";

/**
 * One line of a hunk.
 *
 * `no_newline` is the `\ No newline at end of file` marker, folded onto the line it
 * annotates rather than modelled as a line of its own. Keeping it as a separate row would
 * put a phantom entry in the middle of the indices a [`LineRef`] uses, and every off-by-one
 * there is a mis-staged line.
 */
export type DiffLineView = { origin: LineOrigin, 
/**
 * Without the leading `+`/`-`/` ` and without the trailing newline.
 */
content: string, oldLineno: number | null, newLineno: number | null, noNewline: boolean, };
