// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the user answered a diff that Claude Code is blocked on.
 *
 * The three outcomes are the protocol's, and the difference between them is what gets
 * written to disk — so this is one of the few wire types where a wrong mapping destroys
 * work rather than degrading a view.
 */
export type DiffAnswer = { "kind": "acceptedEdited", contents: string, } | { "kind": "acceptedAsIs" } | { "kind": "rejected" };
