// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLineView } from "./DiffLineView";

export type DiffHunkView = { 
/**
 * Index into [`FileDiff::hunks`]. Named explicitly so a [`LineRef`] is readable in a
 * log line without the surrounding array.
 */
index: number, 
/**
 * The `@@ -a,b +c,d @@ section` line as libgit2 rendered it.
 */
header: string, oldStart: number, oldLines: number, newStart: number, newLines: number, lines: Array<DiffLineView>, };
