// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { ProjectId } from "./ProjectId";
import type { TaskId } from "./TaskId";

/**
 * Dispatch one run. Inbound.
 */
export type DispatchRequest = { project: ProjectId, agent: AgentId, 
/**
 * The task this run is for.
 *
 * `None` is legal and means an ad-hoc run — a user or the orchestrator asking a role to do
 * one thing that is not on the board. The panel's Dispatch button nonetheless **always**
 * fills it, because a run with no task is a run the Tasks panel cannot account for: it
 * draws no chip on any row, it leaves no trace once it has exited, and the record of what
 * the agents did that afternoon has a hole in it.
 */
task?: TaskId, 
/**
 * Extra instruction for this run only, appended after the task body.
 *
 * `None` means the task speaks for itself, which is the case the orchestrator should be
 * aiming for: instruction that lives only in a prompt is instruction the next run of the
 * same task never sees.
 */
prompt?: string, };
