// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerDetail } from "./ContainerDetail";
import type { ImageDetail } from "./ImageDetail";
import type { NetworkDetail } from "./NetworkDetail";
import type { VolumeDetail } from "./VolumeDetail";

/**
 * The detail pane's content. (M47)
 */
export type DockerDetail = { "kind": "container" } & ContainerDetail | { "kind": "image" } & ImageDetail | { "kind": "volume" } & VolumeDetail | { "kind": "network" } & NetworkDetail | { "kind": "missing", reason: string, };
