// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComposeAvailability } from "./ComposeAvailability";
import type { ContainerRow } from "./ContainerRow";
import type { ContextRow } from "./ContextRow";
import type { ImageRow } from "./ImageRow";
import type { NetworkRow } from "./NetworkRow";
import type { VolumeRow } from "./VolumeRow";

/**
 * Everything one read of a live daemon produced.
 *
 * Boxed inside [`DockerBoard::Ready`] because the failure arms are two strings and this is a
 * hundred containers; an unboxed variant makes every `DockerBoard` that size, including the
 * ones a panel holds while showing an error.
 */
export type DockerSnapshot = { 
/**
 * The endpoint this snapshot came from, as a `DOCKER_HOST` URL.
 */
endpoint: string, 
/**
 * Which named context is in use, when the endpoint came from one. `None` for an endpoint
 * from `CIDE_DOCKER_HOST`, `DOCKER_HOST` or a bare socket path — those have no name, and
 * inventing one ("default") would make the switcher lie about what is selected.
 */
context?: string, 
/**
 * Every context the store holds, for the switcher. Sorted by name.
 */
contexts: Array<ContextRow>, 
/**
 * The API version actually negotiated — the lower of what the daemon offers and what cide
 * was built against. Shown in Settings, because it is the first thing to ask about when a
 * field is empty that should not be.
 */
apiVersion: string, 
/**
 * What the daemon calls itself: `Docker Engine`, `podman`, and so on.
 */
server: string, containers: Array<ContainerRow>, images: Array<ImageRow>, volumes: Array<VolumeRow>, networks: Array<NetworkRow>, 
/**
 * Whether `docker compose` is available on this machine, and where it was found.
 *
 * # Why the *board* carries this, and not a separate command
 *
 * Because the panel needs it in the same frame as the stacks it decides the buttons for.
 * A stack row is drawn from container labels — pure Engine API — and its `up`/`down`
 * buttons need a CLI plugin the daemon has never heard of (ADR 0013). Two calls would give
 * a frame in which the stacks are drawn and their buttons have not yet decided whether they
 * exist, which is exactly the flicker a user reads as "the button did not appear".
 */
compose: ComposeAvailability, };
