// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerStream } from "./DockerStream";

/**
 * Which container a pane is attached to, and how. (M42)
 */
export type DockerPane = { 
/**
 * The full container id, which is what every call is addressed by.
 */
container: string, 
/**
 * The name as it was when the pane was opened — for the title, and for the sentence when the
 * container is gone. **Not** re-resolved on restore: a name is reused whenever a compose
 * stack is recreated, and a pane that silently re-pointed at a *different* container with
 * the same name would be the worst outcome available here.
 */
name: string, stream: DockerStream, };
