// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a documentation tab is *about* — enough to ask the server again, never the page itself.
 *
 * The same argument `TabKind::Docker` makes: a tab is durable and a page is not. A page for
 * `Node` is a claim about the engine the user runs today; the tab carries the question, and the
 * pane asks it on every mount. Two shapes because two providers answer two kinds of question —
 * a Godot native symbol has a stable name, a hover has only the place it was asked at.
 */
export type DocsSubject = { "kind": "reference", source: string, refKind: string, target: string, } | { "kind": "position", path: string, line: number, column: number, word: string, };
