// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A link drawn under the title.
 */
export type DocsLink = { label: string, 
/**
 * An `https://` URL, or a `#ref/…` fragment the same provider can follow.
 */
href: string, };
