// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffView } from "./DiffView";

export type EditorSettings = { 
/**
 * Point size for the editor's mono face.
 *
 * `f32`, not `u8`, and the type is the fix rather than a refinement of it: the design
 * mock specifies **12.5px**, `tokens.css` ships that, and an integer cannot hold the
 * project's own default. The two defaults here were 13 and 12 — neither the mock's number
 * nor each other's — which went unnoticed for exactly as long as nothing read them.
 *
 * Clamped where a patch lands, not here: see [`clamp_font_size`].
 */
fontSize: number, tabSize: number, insertSpaces: boolean, showMinimap: boolean, wordWrap: boolean, trimTrailingWhitespaceOnSave: boolean, 
/**
 * Write a changed file when it loses focus, and after a minute with no edits. (M15)
 *
 * **On by default**, which is why `persist::v2_to_v3` writes the value into every existing
 * document rather than letting `#[serde(default)]` supply it. The distinction matters for
 * exactly the reason [`crate::ProxyScope`]'s did: a defaulted field means an existing
 * user's setting is an *inference* from a constant in this build, so the day somebody
 * changes the default for new installs, every workspace on disk silently changes behaviour
 * — and this particular behaviour writes the user's files. Written down, an upgrade is a
 * fact on disk and a later change to the default touches new installs only.
 *
 * The *interval* is deliberately not here. Rust does nothing with it; a single
 * `AUTOSAVE_IDLE_MS` in `ui/src/editor/autosave.ts` has one home and nothing to disagree
 * with. What crosses the wire is the yes/no.
 */
autosave: boolean, 
/**
 * How a diff is laid out. See [`DiffView`].
 */
diffView: DiffView, 
/**
 * Which colour scheme paints the buffer, under each [`crate::Theme`]. (M24)
 *
 * **Two fields rather than one, and the pair is the design.** A scheme owns the editor's
 * *background* as well as its token colours, so a single field would let an imported dark
 * scheme paint a dark rectangle inside a white window, beside a white sidebar and a white
 * terminal — and every contrast ratio `check-theme.mjs` records against `--panel` would
 * stop describing the editor. Keyed by polarity, an imported dark scheme is only ever a
 * *different dark*; the disagreeing state is unreachable rather than merely discouraged.
 *
 * It is also the shape `tokens.css` already has: one light block, one dark block. The
 * Appearance screen shows one row, for whichever theme is showing.
 *
 * The value is a [`crate::ColorScheme::id`], or [`crate::BUILTIN_SCHEME`] for the compiled-in
 * one. A `String` and not an enum because the set is open by construction — the schemes are
 * whatever the user has imported. An id naming a scheme that has since been removed falls
 * back to the builtin at paint time rather than being repaired here: a setting is not the
 * place to discover that a file is missing, and a user who re-imports gets their choice
 * back.
 */
colorSchemeLight: string, colorSchemeDark: string, 
/**
 * How to reformat a buffer, keyed by [`crate::lang::LanguageDef::id`]. (M26)
 *
 * **A language absent from this map is formatted by its language server**, and one present
 * here is formatted by this instead — the configured entry wins. The precedence is that way
 * round because this map is the only lever a user has over a formatter cide chose for them:
 * both servers are bundled now, so "I do not want the shipped rust-analyzer's rustfmt"
 * would otherwise mean switching the whole server to [`ServerBinaryChoice::System`], which
 * is a far larger hammer than the complaint.
 *
 * **A `Vec<String>` and not a command line**, for the reason [`ClaudeCli::args`] gives at
 * length and which applies here word for word: a single string needs a quoting parser cide
 * would have to invent, and would get wrong at the first `--stdin-filepath "my file.ts"`.
 * One token per row in the UI, and the argv reaches `execvp`, never a shell — so `$HOME`,
 * `*`, `|` and `&&` are literal argument text and not syntax. The two placeholders cide
 * does substitute are `${file}` and `${dir}`; see `cide_core::format::argv`.
 *
 * The program is run as a **filter**: the buffer on stdin, the formatted text on stdout.
 * That is what `prettier --stdin-filepath`, `black -`, `gofmt` and `rustfmt --emit stdout`
 * all do, and it is the only shape that can format an *unsaved* buffer. A formatter that
 * only rewrites files in place — `cargo fmt` itself — does not belong here, and would be
 * exactly the on-disk write under a dirty buffer that `cide_core::document`'s
 * `a_stale_precondition_refuses_and_leaves_the_file_alone` calls the one that matters.
 *
 * Empty by default rather than seeded, for the reason
 * [`InspectionSettings::server_binaries`] states: a seeded row would make today's default a
 * stored fact that survives a future change of default.
 */
formatters: { [key in string]: Array<string> }, };
