// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffView } from "./DiffView";

export type EditorSettings = { 
/**
 * Point size for the editor's mono face.
 *
 * `f32`, not `u8`, and the type is the fix rather than a refinement of it: the design
 * mock specifies **12.5px**, `tokens.css` ships that, and an integer cannot hold the
 * project's own default. The two defaults here were 13 and 12 — neither the mock's number
 * nor each other's — which went unnoticed for exactly as long as nothing read them.
 *
 * Clamped where a patch lands, not here: see [`clamp_font_size`].
 */
fontSize: number, tabSize: number, insertSpaces: boolean, showMinimap: boolean, wordWrap: boolean, trimTrailingWhitespaceOnSave: boolean, 
/**
 * Write a changed file when it loses focus, and after a minute with no edits. (M15)
 *
 * **On by default**, which is why `persist::v2_to_v3` writes the value into every existing
 * document rather than letting `#[serde(default)]` supply it. The distinction matters for
 * exactly the reason [`crate::ProxyScope`]'s did: a defaulted field means an existing
 * user's setting is an *inference* from a constant in this build, so the day somebody
 * changes the default for new installs, every workspace on disk silently changes behaviour
 * — and this particular behaviour writes the user's files. Written down, an upgrade is a
 * fact on disk and a later change to the default touches new installs only.
 *
 * The *interval* is deliberately not here. Rust does nothing with it; a single
 * `AUTOSAVE_IDLE_MS` in `ui/src/editor/autosave.ts` has one home and nothing to disagree
 * with. What crosses the wire is the yes/no.
 */
autosave: boolean, 
/**
 * How a diff is laid out. See [`DiffView`].
 */
diffView: DiffView, };
