// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One extension, as its manifest names itself — `sql`, `yaml`. (M22)
 *
 * A string for [`AgentId`]'s reason and one more of its own. The author writes it in
 * `cide-extension.json`; it is the second segment of the install path; it is the prefix of every
 * command the extension contributes (`ext.sql.showStatements`), and **command ids are API** —
 * a user's `keymap.json` names them, so an id cide minted per install would change under a
 * reinstall and silently orphan every binding pointing at it.
 *
 * Not globally unique, and not pretending to be: two marketplaces may each ship an extension
 * called `sql`. Identity is the pair (marketplace, extension), which is why nothing here tries
 * to make the string alone carry it — `cide-ext` reports the collision and names both manifests
 * rather than inventing a winner.
 */
export type ExtensionId = string;
