// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionId } from "./ExtensionId";
import type { MarketplaceId } from "./MarketplaceId";

/**
 * One extension, named the only way that is unambiguous.
 */
export type ExtensionRef = { marketplace: MarketplaceId, extension: ExtensionId, };
