// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a finding stopped something.
 *
 * The distinction `cide-agents` had to invent and for the same reason: an unknown manifest key
 * **warns** while an unknown capability **greys the extension**. Drawn identically they would be
 * indistinguishable, and a user would spend an afternoon chasing a yellow line that was never
 * going to be the reason their extension would not load.
 */
export type ExtSeverity = "error" | "warning";
