// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullStrategy } from "./PullStrategy";
import type { PulledCommit } from "./PulledCommit";

/**
 * Result of a fetch or a fast-forward pull.
 *
 * # Why this carries more than `advanced`
 *
 * It used to carry `remote`, `shelled_out`, `output` and `advanced`, and the only sentence
 * anything could build from that was *"Fast-forwarded 7 commits from origin"*. That answers
 * "did it work"; it does not answer "what did I just take", which is the question a person
 * asks after pulling into a tree they are about to build. The three answers a pull can give
 * — *nothing came down*, *this came down*, and *I refused because you have diverged* — must
 * be told apart at a glance, and the middle one is the one that needs contents.
 *
 * The fields below the transport half are therefore the pull's own report: which branch
 * moved, from which commit to which, what the diff between them totals, and the commits
 * themselves. A plain fetch fills in none of it, because a fetch moves no working tree —
 * see [`FetchOutcome::fetched`], which says so in one place instead of at every call site.
 */
export type FetchOutcome = { remote: string, 
/**
 * True when the `git` binary did it because a credential helper is configured — the
 * same rule [`PushOutcome::shelled_out`] records for pushes.
 */
shelledOut: boolean, 
/**
 * git's own text. `Everything up-to-date`, or the transport's complaint, lives here.
 *
 * **Untrusted on the binary route.** `git fetch`'s stderr carries the server's `remote:`
 * sideband lines verbatim, which are written by whoever runs that server. It is shown
 * and nothing else: never parsed into an action, never used to decide what the app will
 * do next. The frontend collapses it to one line and caps it (`branchModel::oneLine`).
 */
output: string, 
/**
 * How many commits the fast-forward moved `HEAD`. Zero for a plain fetch, and for a
 * pull that had nothing to take.
 */
advanced: number, 
/**
 * The branch the pull moved. Empty for a fetch, which moves none.
 *
 * Filled in even when `advanced` is zero, so the frontend can say *"main is already up
 * to date"* rather than the anonymous *"already up to date"* a fetch gets.
 */
branch: string, 
/**
 * Where that branch was before, short. Empty for a fetch.
 */
oldOid: string, 
/**
 * Where it is now, short. Equal to `old_oid` when nothing came down.
 */
newOid: string, 
/**
 * `git diff --shortstat` between the two, over the whole fast-forward.
 */
filesChanged: number, insertions: number, deletions: number, 
/**
 * The commits taken, newest first, **capped in Rust**.
 *
 * Capped here and not in the frontend on purpose: a 400-commit pull after a fortnight
 * away must not put 400 rows on the IPC wire to have 390 of them dropped by a `slice`
 * in a component.
 *
 * Always *what came down from upstream*, whichever strategy ran — walked as
 * `push(upstream).hide(pre-pull local tip)`. That is what makes one field right for a
 * fast-forward, a merge and a rebase alike.
 */
commits: Array<PulledCommit>, 
/**
 * How many more there were beyond `commits`. Zero when the list is complete.
 */
moreCommits: number, 
/**
 * The walk that produced [`Self::commits`], spelled as the revspec
 * `<pre-pull local tip>..<upstream tip>` over **full** oids — what the notice's *View
 * commits* hands the log, which then runs the same walk uncapped.
 *
 * Spelled here and not in the frontend, for the reason [`PushOutcome::refspec`] is: one
 * producer, so the rows the log draws are the rows this struct's `commits` are the head of.
 * Full oids rather than [`Self::old_oid`]'s eight characters because a range is resolved by
 * `revparse`, and eight characters are ambiguous in a repository the size of the kernel —
 * the toast would read fine and the link would open an `AmbiguousRev` refusal.
 *
 * Deliberately **not** `old_oid..new_oid`. For a merge that range includes the merge commit
 * cide has just made, and for a rebase it includes the user's own replayed commits; neither
 * was received. Empty for a fetch and for a pull that took nothing.
 */
received: string, 
/**
 * What the pull did.
 *
 * `None` for a plain fetch **and** for a pull that had nothing to take: in both cases no
 * integration happened, and there is no honest value to name. A separate `PullOutcome`
 * type was considered and rejected — the frontend has exactly one function that turns
 * this struct into a sentence, and a second DTO would double the shapes it handles to
 * avoid four zeros.
 */
strategy?: PullStrategy, 
/**
 * How many of **your own** commits a rebase replayed onto the new base.
 *
 * Zero for every other strategy. [`Self::advanced`] is still what came *down*; a rebase
 * reports both because it does both, and one number cannot say "took 7, rewrote 3".
 */
rewritten: number, 
/**
 * Local commits a rebase did not replay because replaying them would have produced
 * nothing — git's `--empty=drop`, which is nearly always *this patch is already
 * upstream*.
 *
 * Reported rather than swallowed: `git rebase` drops them silently, and a user whose
 * three commits became two has to be told which arithmetic happened or they go looking
 * for the lost one.
 *
 * It also counts one case `git rebase` does **not** drop — a commit that was empty to
 * begin with, which git keeps and libgit2 does not. `cide_git::pull` states both
 * differences; this number is what makes either of them visible.
 */
skipped: number, 
/**
 * Paths left conflicted by a merge or rebase that could not complete on its own.
 *
 * **Non-empty is not a failure.** The operation did what was asked; git state is on disk
 * (`MERGE_HEAD` or `.git/rebase-merge`), the index carries stages 1/2/3, and the user now
 * resolves. Reporting it as `Ok` rather than `Err` is what routes it to the conflict
 * surface instead of to the red toast that `chrome/Failures.tsx` draws for refusals.
 */
conflicts: Array<string>, };
