// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What happened to one file on one side of the index.
 */
export type FileState = "unmodified" | "added" | "modified" | "deleted" | "renamed" | "copied" | "typeChange" | "untracked" | "ignored" | "conflicted";
