// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStamp } from "./FileStamp";

/**
 * What rides beside a file's bytes on the way **from** the webview. (M63)
 *
 * The head of the frame `file_write_bytes` is handed. The path is in the head and not in a
 * request header because a header value is visible ASCII and a path is not — see
 * `cide_ipc::frame`'s module comment. `if_unchanged` has `file_write`'s meaning exactly:
 * `None` writes unconditionally (Ctrl+S), `Some` is the autosave precondition.
 */
export type FileBytesWrite = { path: string, ifUnchanged: FileStamp | null, };
