// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStamp } from "./FileStamp";

/**
 * What rides beside a file's bytes on the way **to** the webview. (M63)
 *
 * The head of the frame `file_read_bytes` answers with (`cide_ipc::frame`): the two facts
 * [`FileDoc`] carries besides its text, from the same `metadata` call that read the bytes.
 * The drawing pane's autosave compares against `stamp` exactly as the editor's does.
 */
export type FileBytesHead = { 
/**
 * See [`FileDoc::writable`] — the mode bits, and the dependency-cache rule applied.
 */
writable: boolean, 
/**
 * See [`FileDoc::stamp`].
 */
stamp: FileStamp | null, };
