// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffHunkView } from "./DiffHunkView";
import type { DiffSide } from "./DiffSide";
import type { FileState } from "./FileState";

/**
 * A per-file diff, and the only thing a [`Selection`] is meaningful against.
 */
export type FileDiff = { path: string, oldPath: string | null, side: DiffSide, status: FileState, binary: boolean, 
/**
 * Unix mode bits, e.g. 33188 (0o100644). Zero when the side does not exist.
 */
oldMode: number, newMode: number, hunks: Array<DiffHunkView>, 
/**
 * Hash of the exact patch text this diff was derived from.
 *
 * A selection carries it back, and staging refuses a mismatch. Without it, a user who
 * checks three lines while Claude is mid-edit stages three *different* lines — the
 * panel's selection would be applied to a diff it never saw.
 */
rev: string, 
/**
 * False when the file cannot be partially staged at all — binary, a submodule, a
 * symlink or a deletion. The UI hides the per-hunk affordances rather than offering a
 * control that will be refused.
 */
partialOk: boolean, };
