// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Symbol } from "./Symbol";

/**
 * What is known about one file's structure.
 *
 * Three states, three different claims — see the module docs for why this is not a `Vec`.
 */
export type FileOutline = { "kind": "unsupported", reason: string, } | { "kind": "failed", reason: string, } | { "kind": "ready", 
/**
 * `Rust` / `Go`, spelled as the status bar spells it.
 */
language: string, symbols: Array<Symbol>, 
/**
 * A cap stopped the extraction, so `symbols` is a prefix rather than the whole file.
 */
truncated: boolean, };
