// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchStatus } from "./WatchStatus";

/**
 * What a project's index is doing, and how it is watching.
 */
export type FsStatus = { 
/**
 * True between `fs.index` starting and the walk finishing. The picker is usable the
 * whole time — this only tells the UI whether its counts are still climbing.
 */
indexing: boolean, files: number, dirs: number, 
/**
 * `treeCount` at the moment the status was taken, so a caller that is only sizing a
 * scrollbar does not need a second round trip.
 */
rows: number, watch: WatchStatus, };
