// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When the active milestone's gate runs without being asked.
 *
 * A gate is a project's own acceptance run, and on the projects milestones were built for it is
 * long: selfcraft's `slice` took 16 minutes and `items` 7, terrastrike's gates 7–15 with a
 * `timeoutSecs` of one to two hours. `Merge` reruns it after every agent merge, so a batch of
 * subagents finishing a few minutes apart keeps a gate running for the whole afternoon, each
 * verdict about a commit already superseded by the next merge. `Idle` waits for the project to
 * go quiet — the spinner's wake, which runs a stale gate before it plans — so a batch costs one
 * run; `Manual` leaves it to the Run gate button. Every mode still runs it when asked, and when a
 * plan is defined or a proposal changes it: those are deliberate and rare.
 *
 * Deserialised leniently: a value this build does not know reads as `Merge` rather than failing
 * the plan, because a typo in one key must not cost the whole `milestones` block (see
 * [`MilestonePlan`]).
 */
export type GateRuns = "merge" | "idle" | "manual";
