// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal geometry, in cells and in cell pixels.
 *
 * The pixel fields must be real. Passing zeroes is the usual shortcut and it breaks any
 * program that asks the terminal for its cell size — sixel and inline-image output, and
 * pixel-resolution mouse reporting.
 */
export type Geometry = { cols: number, rows: number, cellWidth: number, cellHeight: number, };
