// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitLabPublishFailure } from "./GitLabPublishFailure";

export type GitLabPublished = { published: Array<string>, failed: Array<GitLabPublishFailure>, };
