// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitLabDraftAuthor } from "./GitLabDraftAuthor";
import type { GitLabDraftReply } from "./GitLabDraftReply";
import type { GitLabSeverity } from "./GitLabSeverity";
import type { GitLabSide } from "./GitLabSide";

/**
 * A review comment that exists **only in cide** until the user publishes it.
 *
 * The GitLab position is computed when the draft is written, against the MR version that was
 * latest then — a line outside every hunk is refused at that moment, while the agent that chose
 * it can still pick another, rather than at publish time when nobody is there to fix it.
 */
export type GitLabDraft = { id: string, review: string, severity: GitLabSeverity, body: string, 
/**
 * `None` for a general comment on the MR.
 */
path: string | null, oldPath: string | null, side: GitLabSide | null, line: number | null, 
/**
 * The GitLab text position, SHAs included, ready to POST.
 */
position: unknown, 
/**
 * The MR head the position was computed against; a newer head marks the draft outdated.
 */
headSha: string, author: GitLabDraftAuthor, createdUnixMs: number, 
/**
 * The local discussion about this draft, oldest first (M101). `default` so a drafts file
 * written before it still loads — `Drafts::load` sets an unreadable file aside, and losing
 * every unpublished finding to a new field would be that path taken for no reason.
 */
replies: Array<GitLabDraftReply>, };
