// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleAt } from "./RuleAt";

/**
 * One *"this pattern is that colour"* rule, compiled into a grammar hook by the frontend.
 *
 * # The pattern
 *
 * A JavaScript regular expression **source** — no delimiters, no flags. The frontend anchors it
 * with `^` if the author did not, because `StringStream.match` matches at the stream position
 * and an unanchored pattern would silently scan forward and colour the wrong run.
 *
 * It **must consume at least one character when it matches**. `StreamLanguage` throws
 * *"Stream parser failed to advance stream"* after ten no-op calls, which does not mis-colour a
 * buffer, it takes the buffer down. A zero-width match is refused at load with the manifest's
 * path and the rule's index, rather than at the tenth token of the first file somebody opens.
 *
 * # The tag
 *
 * A CodeMirror stream-parser token name — `propertyName`, `meta`, `labelName`,
 * `variableName.function`. Validated in the frontend rather than here, against
 * `editor/highlight.ts`'s `tagsFor`, which is the same function the buffer and the minimap
 * resolve names through. A list of legal names copied into this crate would be a second
 * authority that could disagree with the first, and the disagreement would show as a token that
 * parses, matches, and paints in no colour at all.
 */
export type GrammarRule = { 
/**
 * A JavaScript regex source. See the type's own note — it must consume a character.
 */
pattern: string, 
/**
 * The stream-parser token name this run is coloured as.
 */
tag: string, 
/**
 * Where the rule may match. Defaults to [`RuleAt::Anywhere`].
 */
at: RuleAt, };
