// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphicsRung } from "./GraphicsRung";

/**
 * The ladder, plus whether the automatic heuristic is still in charge.
 */
export type GraphicsStatus = { rungs: Array<GraphicsRung>, 
/**
 * False once the user has set any rung explicitly.
 *
 * Taking an explicit choice as "you are driving now" is what lets a rung be turned
 * *off* at all: the launcher's defaults are applied with set-if-unset semantics, so
 * there is no value this side could write that means "and do not apply the default
 * either". Overriding one rung therefore stands the whole heuristic down, and the
 * screen says so rather than leaving the user to discover it.
 */
automatic: boolean, 
/**
 * True when `CIDE_NO_GRAPHICS_WORKAROUNDS` was set in the launching environment, which
 * disables the lot regardless of what is stored here.
 */
suppressedByEnv: boolean, };
