// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line segment in a row's gutter.
 *
 * The lane structure is computed in Rust and shipped as segments rather than being derived in
 * the renderer from `parents`. Two reasons. Deriving it needs the *whole* walk in hand —
 * lane assignment for row N depends on every row before it — so a virtualised list, which is
 * the only kind that can show a hundred thousand commits, cannot do it: it does not have the
 * rows it has scrolled past. And the resume token has to carry the open lanes across a page
 * boundary anyway ([`LaneResume`]), so the state exists here regardless; computing it twice,
 * in two languages, guarantees the two eventually disagree about where a line goes.
 */
export type GraphEdge = { "kind": "pass", lane: number, color: number, } | { "kind": "enter", top: number, color: number, } | { "kind": "exit", bottom: number, color: number, 
/**
 * The parent this edge goes to is **not in this page** — the walk was cut by a limit,
 * a budget or a shallow floor. Drawn fading out rather than into a node that never
 * arrives, which is what an ordinary `Exit` at the bottom of a page looks like and is
 * how a graph acquires lines to nowhere.
 */
dangling: boolean, } | { "kind": "bundle", lane: number, count: number, };
