// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Linux rendering workarounds, applied before the webview is created.
 *
 * Each is off by default and each costs something; see `docs/adr/0006`. `disable_dmabuf`
 * is the exception the app cannot start without on a stock KDE Wayland desktop, so
 * `cide-app::graphics` applies it unconditionally unless the environment already has an
 * opinion — this struct is the user-facing override for the machines that heuristic gets
 * wrong.
 */
export type GraphicsSettings = { disableDmabufRenderer: boolean | null, disableCompositingMode: boolean | null, disableNvidiaExplicitSync: boolean | null, };
