// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Harness } from "./Harness";

/**
 * A harness's own conversation, and where it has to be re-opened from. (M42)
 *
 * The three facts a pane needs to put the **real harness** back on an agent run's conversation
 * after the run's child has gone, and none of the facts it does not: no run id (the run may have
 * left the registry's history by the time the pane comes back after a restart), no argv (the
 * harness spells that, in Rust, at spawn time).
 *
 * `id` is a string rather than a [`SessionId`] on purpose. For `claude` it *is* cide's session
 * uuid, because a claude run's session id is the value handed to `--session-id` and `--resume`
 * keeps it. For `opencode` it is the CLI's own `ses_…`, minted by the child and scraped off its
 * output, which no `SessionId` can hold. One field, two spellings, and the harness that wrote it
 * is the one that reads it.
 *
 * `cwd` is load-bearing on both harnesses: Claude Code files a transcript under the directory it
 * was started in, and an agent run starts in its worktree (`.cide/worktrees/<role>-<task>`), so
 * `claude --resume` from the project root answers *no such conversation*. It travels here rather
 * than being recomputed from a run because the worktree name is the run's business and the pane
 * outlives the run.
 */
export type HarnessSession = { harness: Harness, id: string, cwd: string, };
