// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which CLI actually runs a role.
 *
 * An enum and not a string because it selects an implementation — `cide_agents::harness`
 * dispatches on it — and because the settings surface and the definition parser must agree on
 * the set. A role naming a harness this build does not have is a *parse* error with a line
 * number, which is only possible if the set is closed.
 *
 * More are expected; adding one is a variant here, an `impl Harness` there and one insert into
 * the registry. That is the shape the trait was chosen for.
 */
export type Harness = "claude" | "opencode" | "qwen" | "codex";
