// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one non-interactive run produced.
 *
 * A flat mirror of the CLI's terminal `result` frame rather than an enum over success and
 * failure. The CLI reports its own verdict in `is_error` *and still fills in the rest* —
 * a run that stopped on `error_max_turns` has partial text, a cost and a duration worth
 * showing — so splitting the shape by outcome would throw away the fields that make the
 * failure explicable.
 */
export type HeadlessResult = { 
/**
 * The `result` field: the final assistant text.
 */
text: string, 
/**
 * `text` parsed as JSON, when a schema was requested and the output parses.
 */
structured: unknown, 
/**
 * The CLI's own verdict, not ours. A `false` here with a non-zero exit status is
 * possible and is treated as failure by [`cide_claude::headless`].
 */
isError: boolean, 
/**
 * `success`, `error_max_turns`, `error_during_execution`, … Passed through verbatim:
 * the set is not documented and a release may add to it.
 */
subtype: string, 
/**
 * The uuid the CLI minted for this run.
 *
 * Reported **even with `--no-session-persistence`**, which this lane always passes —
 * verified against 2.1.226 by `cide-claude`'s `real_headless` test, which originally
 * asserted the opposite and failed. The flag governs whether the transcript reaches
 * disk, not whether the run has an id. So this is not evidence that a one-shot is
 * resumable, and nothing should offer to resume it.
 *
 * `Option` because the field is not guaranteed to be in the frame, not because it is
 * expected to be absent.
 */
session: string | null, costUsd: number | null, durationMs: bigint | null, numTurns: number | null, };
