// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One non-interactive request.
 */
export type HeadlessRequest = { 
/**
 * The whole prompt, including any diff or selection it embeds.
 *
 * Delivered to the child on **stdin**, never as argv. A commit-message prompt carries a
 * staged diff, which routinely runs to tens of kilobytes and can pass `ARG_MAX`; and a
 * prompt beginning with `-` would be parsed as a flag. Both failures are silent in
 * different ways, and stdin has neither.
 */
prompt: string, 
/**
 * A model alias (`opus`, `sonnet`, `haiku`) or a full name. `None` uses the user's own
 * default, which is the right choice for a feature they did not ask to configure.
 */
model?: string, 
/**
 * A JSON Schema for structured output, passed through as `--json-schema`.
 *
 * When set, [`HeadlessResult::structured`] carries the parsed object; `text` still
 * carries whatever the CLI printed, so a caller that gets malformed structure can show
 * something rather than nothing.
 */
jsonSchema?: unknown, 
/**
 * A hard ceiling on what this one call may spend, as `--max-budget-usd`.
 *
 * Worth setting on anything triggered by a keystroke: a palette one-shot that goes
 * looping is a bill the user never agreed to and no UI in this app would show them.
 */
maxBudgetUsd?: number, };
