// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much of a buffer's diagnostics are drawn in the gutter and under the text.
 *
 * IDEA's highlighting-level widget, and the reason it exists is a 40,000-line generated file
 * where every line is a warning. Per *editor* rather than global — see
 * `ui/src/editor/highlightLevel.ts` for where the override is held and why it is not persisted.
 *
 * All three levels keep the grammar. Turning highlighting down is about problems, not colour,
 * and IDEA's lexer keeps colouring at every level too.
 */
export type HighlightLevel = "none" | "syntaxOnly" | "allProblems";
