// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryTabId } from "./HistoryTabId";
import type { RepoId } from "./RepoId";

/**
 * One tab of the tool window's Log surface. (M18)
 *
 * The whole tab and not a `(RepoId, String)` pair, because two tabs on the same file are the
 * ordinary case — see [`HistoryTabId`]'s own note — so the identity has to be minted rather
 * than derived from the subject.
 */
export type HistoryTab = { 
/**
 * This tab's divider, in per mille, or `None` for the kind's default.
 *
 * # Per tab, not per project (M21)
 *
 * `ToolWindowState::log_split` is the Log tab's, and a History tab wants a different number
 * for a reason that is about the *question* rather than about taste: the Log tab's right
 * half is a commit's summary and its file list, which is a narrow column beside a wide list,
 * while a History tab's right half is **one file's diff** — the thing the tab was opened to
 * read. Fifty-fifty is what that wants, and it is what was asked for.
 *
 * Sharing one number would make the two fight: dragging the log wide would squeeze every
 * history diff, and widening a diff would squeeze the log. `None` rather than a stored 500
 * so a tab that has never been dragged follows the default if it ever changes, which is the
 * same reason `log_split` is a field and not a literal at the call site.
 */
split: number | null, id: HistoryTabId, repo: RepoId, 
/**
 * Repo-relative and slash-separated, the way `cide_ipc::git` spells every path. **Empty
 * means the whole repository**, which is the commonest tab of all — an `Option<String>`
 * would put a `None` case into every consumer to express a state that is already the
 * natural zero of a path filter, and `cide_ipc::history::LogQuery::path` converts the empty
 * string to `None` at the one seam that cares.
 */
path: string, 
/**
 * What the chip shows: a file name, or the repository's name for a whole-repository tab.
 *
 * Stored rather than derived, for the reason [`DiffSpec`] gives about titles generally: the
 * title is a *label the gesture chose* and it survives a restart, where a derived one would
 * change the day the derivation is improved and would silently relabel every saved tab.
 */
title: string, };
