// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageDoc } from "./ImageDoc";

/**
 * Preview of one Git side. Absence is distinct from an existing file that cannot be shown.
 */
export type ImageDiffSide = { "kind": "absent" } | { "kind": "ready", doc: ImageDoc, } | { "kind": "unavailable", reason: string, };
