// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The image formats cide will put on screen, as **sniffed from the file's own bytes**.
 *
 * Not derived from the extension. The extension decides which *viewer* a tab opens with —
 * that rule is `ui/src/panes/imageKinds.ts`, on the frontend, because it has to be answered
 * before any IPC happens — and this is the answer to the different question of what the file
 * actually contains. Keeping them apart is what lets a `.png` that is really a JPEG render
 * correctly *and* describe itself honestly in the status bar, and it is what makes
 * "this claims to be a PNG and is not" a sentence rather than a blank pane.
 *
 * The list is what a WebKitGTK `<img>` decodes without help. TIFF, AVIF, JPEG XL and `.svgz`
 * are deliberately absent: the first two are engine-version-dependent, and a gzipped SVG
 * needs a `Content-Encoding` the asset protocol does not set, so it would fail *silently* in
 * the image decoder — the one failure mode this whole feature is written to avoid.
 */
export type ImageFormat = "png" | "jpeg" | "gif" | "webp" | "bmp" | "ico" | "svg";
