// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStamp } from "./FileStamp";
import type { ImageFormat } from "./ImageFormat";

/**
 * One image file, as far as the pane needs to know before it can draw it.
 *
 * Answered by `image_read`, which has already proved three things by the time this exists:
 * the file is within the cap, its bytes really are one of [`ImageFormat`], and the asset
 * protocol scope has been widened to admit exactly this path. A pane holding one of these
 * can build a URL and render it.
 */
export type ImageDoc = { 
/**
 * **The canonical path**, which is what the asset URL is built from — not the path that
 * was asked for.
 *
 * Tauri's asset scope canonicalises before it matches (`scope::fs::Scope::is_allowed`
 * calls `try_resolve_symlink_and_canonicalize`), while the protocol handler itself does
 * a plain `File::open` on whatever string the URL carried. Handing the frontend the
 * canonical form makes those two agree by construction. Building the URL from the
 * symlink instead would work today and break the day the scope's matcher changes, and
 * the failure would be a 403 the `<img>` reports as a generic load error.
 *
 * The tab still *opens* on the path as given — see `tab_open_file` — so the caller keeps
 * the name the user pointed at for display. This field is a fetch address, not a label.
 */
path: string, 
/**
 * What the bytes say the file is, which the caller may not assume matches its extension.
 */
format: ImageFormat, 
/**
 * The file's size on disk, for the readout.
 *
 * A `number` on the wire rather than [`FileStamp::mtime_nanos`]'s decimal string: the cap
 * is 32 MiB, so this cannot approach `Number.MAX_SAFE_INTEGER` and there is nothing here
 * for a double to round away.
 */
bytes: number, 
/**
 * What the file was when this was read, used as a **cache-buster** on the asset URL.
 *
 * The asset protocol serves a real HTTP-shaped response and WebKit caches it by URL, so
 * an image an agent has just rewritten would keep showing the old pixels for as long as
 * the tab lives. Appending the stamp to the query string makes a changed file a changed
 * URL. `None` — a filesystem with no usable mtime — simply means no cache-buster, which
 * is the same behaviour cide had before and not a failure worth reporting.
 */
stamp: FileStamp | null, };
