// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageDiffSide } from "./ImageDiffSide";

/**
 * Immutable previews of the actual Git comparison, served through the asset protocol.
 */
export type ImageDiff = { 
/**
 * Changes can resolve an image rename without changing the patch used for staging.
 */
oldPath: string | null, old: ImageDiffSide, new: ImageDiffSide, };
