// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One image, as a row.
 */
export type ImageRow = { 
/**
 * The `sha256:…` id, in full.
 */
id: string, 
/**
 * Every `repo:tag` this image answers to. **Empty is meaningful**: an untagged image is a
 * dangling layer, which is the whole basis of a prune, so the panel needs to tell an image
 * with no tags from one whose tags it failed to read.
 */
tags: Array<string>, 
/**
 * Unix seconds.
 */
created: bigint, 
/**
 * Bytes.
 */
size: bigint, 
/**
 * How many containers, running or not, were created from this image. `-1` where the daemon
 * did not count — Docker's own sentinel, kept rather than flattened to `0`, because `0`
 * means "safe to remove" and `-1` means "cide does not know".
 */
containers: bigint, 
/**
 * Docker's word for what this is: `image`, or a manifest kind on a newer daemon.
 */
kind: string, };
