// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an inspect tab is showing. (M43)
 */
export type InspectTarget = { "kind": "container", id: string, } | { "kind": "image", id: string, } | { "kind": "volume", name: string, } | { "kind": "network", id: string, };
