// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";
import type { Contributions } from "./Contributions";
import type { ExtProblem } from "./ExtProblem";
import type { ExtensionId } from "./ExtensionId";
import type { MarketplaceId } from "./MarketplaceId";

/**
 * An installed extension.
 *
 * `Eq` is deliberately absent from here down: a [`SettingKind::Number`] carries an `f64`, so
 * nothing containing a [`Contributions`] can be `Eq`. `PartialEq` is what every caller actually
 * uses — comparing two snapshots, asserting one in a test — and the difference only matters to a
 * `HashMap` key, which none of these is.
 */
export type InstalledExtension = { name: string, version: string, description: string, 
/**
 * Whether the user has it switched on. A disabled extension keeps its row, its manifest and
 * its installed files; nothing of it reaches the registry.
 */
enabled: boolean, 
/**
 * The marketplace commit this copy was taken at. What an update compares against.
 */
commit: string, capabilities: Array<Capability>, contributes: Contributions, 
/**
 * Every contributed setting's current value, keyed by [`SettingDef::id`].
 *
 * **Resolved, not stored**: the defaults with whatever the user changed layered on top, every
 * one already through [`SettingDef::coerce`]. So a reader — the Settings page, the worker —
 * never has to know what a default is or what happens when a stored value is the wrong type.
 * The *stored* half, which is only the differences, is `extensions.json`'s.
 */
settings: Record<string, boolean | string | number>, 
/**
 * The directory the code was copied into. Shown in the panel; also the jail
 * `cide-ext://` resolves against.
 */
path: string, 
/**
 * The worker entry point, relative to [`Self::path`], or `None` for a purely declarative
 * extension — a language and a server and nothing else, which is a first-class case and not a
 * degenerate one.
 *
 * On the wire rather than assumed to be `main.js`, because the manifest may name anything and
 * an extension whose entry is `src/worker.js` would otherwise have `has_worker` true and a
 * 404 behind it. Refused at load if it leaves the installed directory — the same jail
 * `cide-ext://` uses, reused rather than restated.
 */
main?: string, 
/**
 * One sentence, when the extension loaded **greyed**: its manifest parsed but something in
 * it is not usable. `None` for the ordinary case.
 */
unavailable?: string, problems: Array<ExtProblem>, marketplace: MarketplaceId, extension: ExtensionId, };
