// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";
import type { ExtensionId } from "./ExtensionId";
import type { MarketplaceId } from "./MarketplaceId";

/**
 * Install, or update, one extension.
 */
export type InstallRequest = { 
/**
 * The capabilities the user is granting, which must equal the ones the manifest declares.
 *
 * Echoed back rather than taken from the manifest, and this is the whole of the consent
 * mechanism: an install whose granted set does not match what cide is about to read is
 * refused. Without it a marketplace could add `process:spawn` to a manifest between the sheet
 * being drawn and the button being pressed, and the user would have approved a different
 * extension from the one that installed.
 */
granted: Array<Capability>, marketplace: MarketplaceId, extension: ExtensionId, };
