// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyName } from "./KeyName";

/**
 * A keystroke, as a device describes it.
 *
 * **Semantic, never bytes**, and that is not a convenience — it is the only shape that can be
 * correct. Whether an arrow key is `CSI A` or `SS3 A` depends on DECCKM, and whether pasted text
 * must be wrapped in `CSI 200~` depends on bracketed-paste mode; both are modes of the *child*,
 * known only to the screen mirror. A device that encoded its own bytes would be guessing at
 * state it cannot see, and the failure is an arrow key arriving in a TUI as a literal `A`.
 *
 * It also means the device needs no terminal knowledge at all: a key bar sends `up`, and what a
 * program two machines away actually receives is cide's problem.
 */
export type KeyEvent = { key: KeyName, 
/**
 * The character for [`KeyName::Char`], ignored otherwise.
 *
 * A `String` rather than a `char` because a soft keyboard emits graphemes — an emoji, an
 * accented letter composed from two code points — and a terminal takes the UTF-8 either way.
 */
text?: string, ctrl?: boolean, alt?: boolean, shift?: boolean, };
