// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeymapConflict } from "./KeymapConflict";
import type { KeymapProblem } from "./KeymapProblem";
import type { ResolvedBinding } from "./ResolvedBinding";

/**
 * Everything Settings → Keymap draws.
 */
export type KeymapReport = { 
/**
 * Every binding after layering defaults → platform → user, each remembering its layer.
 */
bindings: Array<ResolvedBinding>, 
/**
 * Keystrokes more than one command answers to. Reported, never resolved: which should
 * win is a judgement only the user can make.
 */
conflicts: Array<KeymapConflict>, 
/**
 * Lines in the user's file that did not do what they look like they do.
 */
problems: Array<KeymapProblem>, 
/**
 * Where the overrides file lives, so the screen can name it. It need not exist — a
 * fresh install has no overrides, which is not an error.
 */
path: string, };
