// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeymapReport } from "./KeymapReport";

/**
 * What one `keymap_edit` call did, and the state of the keymap afterwards.
 *
 * The counts are the whole reason this is not just a [`KeymapReport`]. The failure a keymap
 * editor has to be loud about is the edit that *matched nothing* — a *Restore default* whose
 * `when` did not line up with the entries it was aimed at changes no file, resolves to the
 * same table, and is indistinguishable on screen from one that worked. `removed: 0` is the
 * difference, and it is the same argument `resolve_with_diagnostics` makes for reporting a
 * recovery rather than performing it silently.
 */
export type KeymapEditResult = { 
/**
 * Entries deleted from `keymap.json`.
 */
removed: number, 
/**
 * Entries appended to it, the `-command` removals included.
 */
added: number, 
/**
 * The keymap as it now stands, so the screen never has to re-fetch to draw what it did.
 */
report: KeymapReport, };
