// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Two or more commands competing for one keystroke in one context.
 *
 * A wire mirror of `cide_core::keymap::Conflict` rather than that type itself, because
 * `ts-rs` exports per crate and `cargo xtask codegen` only reads `cide-ipc`'s bindings —
 * a `#[derive(TS)]` in `cide-core` lands in `crates/cide-core/bindings` and never reaches
 * `ui/src/ipc/generated.ts`. The domain type stays the domain's; this one is the wire's.
 */
export type KeymapConflict = { 
/**
 * The normalised keystroke, e.g. `ctrl+shift+p`.
 */
key: string, 
/**
 * The competing command ids in resolution order. The **last** one wins.
 */
commands: Array<string>, 
/**
 * The shared `when` clause, `None` when all of them are unconditional. Bindings whose
 * contexts differ are not in conflict — that is how one key means two things in a
 * terminal and in an editor.
 */
when: string | null, };
