// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenLaneWire } from "./OpenLaneWire";

/**
 * The graph's open columns at a page boundary.
 */
export type LaneResume = { lanes: Array<OpenLaneWire>, 
/**
 * The colour cursor, so the first row of the next page continues the rotation instead of
 * restarting it. Restarting recolours every open branch at each page boundary, which as
 * the user scrolls looks exactly like the graph redrawing itself at random.
 */
nextColor: number, };
