// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TcpEndpoint } from "./TcpEndpoint";

/**
 * A language server cide can drive.
 *
 * Until M22 this was `cide_lsp::Server`, a two-member enum with six `match` arms and — the field
 * that turns out to matter most — **no arguments at all**: `server.rs` built `Command::new(bin)`
 * and spawned it. `rust-analyzer` and `gopls` both speak LSP on stdio with no flags, so nothing
 * noticed. `yaml-language-server` needs `--stdio` and says so in its own README.
 */
export type LanguageServerDef = { 
/**
 * The binary name, looked up on the child's `PATH`. Never an absolute path from a manifest:
 * a marketplace that could name `/usr/bin/…` could name anything.
 */
binary: string, 
/**
 * Arguments, in order. `["--stdio"]` for the node-based servers.
 */
args: Array<string>, 
/**
 * The [`LanguageDef::id`]s whose files this server owns.
 */
languageIds: Array<string>, 
/**
 * A file whose presence means a directory is a project worth analysing.
 *
 * Empty means *any root* — which is right for a server that analyses single files (`sqls`
 * has no manifest to look for) and wrong for anything that resolves a dependency graph.
 */
projectMarkers: Array<string>, 
/**
 * What the Problems panel calls a root this server claimed: `Cargo`, `Go module`.
 */
projectKind: string, 
/**
 * How to install it, in the words the user would type.
 */
installHint: string, 
/**
 * Whether the server declares `workspace/didChangeWatchedFiles` and should be sent them.
 *
 * `gopls` has no watcher of its own and needs them; `rust-analyzer` has one that sees more
 * than cide's gitignore-filtered index and is made worse by being told twice.
 */
declaresWatchedFiles: boolean, 
/**
 * Directories to add to the child's `PATH` when the binary is not otherwise findable —
 * `~/.cargo/bin`, `~/go/bin`, `~/.local/share/npm/bin`. `~` is expanded; nothing else is.
 */
extraPathHints: Array<string>, 
/**
 * `initializationOptions` this definition wants sent, whatever the provenance. (M45)
 *
 * # The two lanes, and why they are separate
 *
 * `cide_lsp::config::init_options` sends cide's *own* configuration only to a
 * `Provenance::Bundled` or `Override` resolution — the shipped rust-analyzer fork and a
 * developer's build of it — so that a stock server gets byte-for-byte the handshake it has
 * always got. That gate is right for the fork, whose option names are a two-repo contract,
 * and wrong for a server that simply needs to be *told something*: `yaml-language-server`
 * has no idea a Compose file is a Compose file until it is handed a schema map, and it is
 * always a stock installation.
 *
 * So a definition may carry its own options, which are sent regardless of provenance, while
 * the fork-specific ones stay provenance-gated. **One producer each**: nothing may put a
 * fork option here, and nothing may put a definition's options behind that gate.
 *
 * `None` — the default, and what every builtin but `yaml-language-server` answers — means
 * "say nothing", which is the pre-M45 behaviour exactly.
 */
initOptions?: unknown, 
/**
 * Reach the server over TCP instead of spawning it. (M59)
 *
 * Godot's language server is the running Godot editor, listening on `127.0.0.1:6005`; there
 * is no binary to run on stdio and never will be. With this set, cide *attaches*: it
 * connects, handshakes, and treats "nothing is listening" as *not running* rather than as a
 * failure — the user opens the project in Godot and the row goes green by itself.
 *
 * # `binary` is still required, and it is the server's *name*
 *
 * It keys `cide_lsp::discover::install`'s merge, `by_binary`, the Problems panel's source id,
 * the supervisor thread's name and every log line; for a spawned server it is also the
 * program. Nothing is looked up for a connect server. `args` with `connect` is refused by the
 * manifest: spawn-and-connect (`godot --headless --editor --lsp-port N`) is a later pass, and
 * the same definition with `args` added is how it would be spelled.
 *
 * # Loopback only, as a literal address
 *
 * `host` must parse as an IP address and answer `is_loopback()`; a name — `localhost`
 * included — is refused, because connecting takes a `SocketAddr` and resolving a name is an
 * `/etc/hosts` question. This is the analogue of `binary`'s "never an absolute path":
 * `didOpen` carries the whole document, so a manifest that could name a host could ship the
 * user's files to it. Checked in `cide_ext::manifest` and again in `cide_lsp::discover`,
 * because a builtin definition is never validated.
 *
 * A connect server must also declare `project_markers`: empty means *any root*, and with
 * the attach retry that is a connect attempt against the port every few seconds in every
 * project the user ever opens.
 *
 * Paired with `skip_serializing_if`, unlike `init_options` above, whose `unknown` type
 * admits a `null`: `connect?: TcpEndpoint` would throw on `.host` if `null` arrived.
 */
connect?: TcpEndpoint, };
