// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileExtension } from "./FileExtension";
import type { FoldSpecDto } from "./FoldSpecDto";
import type { GrammarSpecDto } from "./GrammarSpecDto";
import type { ScratchTypeDto } from "./ScratchTypeDto";

/**
 * A whole language: what names it, what colours it, and how it folds.
 */
export type LanguageDef = { 
/**
 * A registry identifier, not a user-visible name — `sql`, `yaml`, `clike`.
 *
 * Also the `languageId` a language server's documents carry, which is why it is spelled the
 * way LSP spells it rather than however the author would like it capitalised.
 */
id: string, 
/**
 * What the status bar readout calls it.
 */
label: string, 
/**
 * The file extensions this language claims, lowercase and without the dot.
 */
extensions: Array<FileExtension>, 
/**
 * Whole file names with no useful extension — `dockerfile`, `.bashrc`. Lowercased on lookup.
 */
filenames: Array<string>, 
/**
 * Markdown fence words that mean this language, spelled as *extensions* — `golang` → `go` —
 * so they route through the same lookup a file path does.
 */
fenceAliases: Array<string>, grammar: GrammarSpecDto, fold: FoldSpecDto, 
/**
 * Rows for the *New scratch file…* picker, in the order it should list them.
 *
 * A list and not one row, because a language can be two things a person asks for: `.ts` and
 * `.js` load the same table, and so do `.c` and `.cpp`. Ordinary extensions want one.
 */
scratch: Array<ScratchTypeDto>, };
