// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionSource } from "./ContributionSource";
import type { LanguageDef } from "./LanguageDef";

/**
 * A language in the resolved registry, with the source that won.
 */
export type LanguageBinding = { def: LanguageDef, source: ContributionSource, 
/**
 * A source this one displaced, if any. Reported rather than silent — see
 * [`ContributionSource`].
 */
supersedes?: ContributionSource, };
