// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of one hunk of a [`FileDiff`].
 */
export type LineRef = { hunk: number, 
/**
 * Index into [`DiffHunkView::lines`].
 */
line: number, };
