// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the role form may offer in its **Model** box, for one harness. (M43)
 *
 * # Why a list at all, when [`AgentDraft::model`] is validated against nothing
 *
 * Because "validated against nothing" is a rule about what cide *refuses*, and it says nothing
 * about what cide can *suggest*. The two are the same asymmetry [`AgentDraft::effort`] states:
 * a menu, not a rule. This is the strong form of it — Claude Code has aliases anybody can type
 * (`sonnet`), while opencode wants `provider/model` drawn from whichever providers this machine
 * has configured, which on a real one includes ids like `unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_M`.
 * A field nobody can fill from memory is a field nobody fills, and the effect was that
 * selecting opencode left every role on the provider default with no way to say otherwise.
 *
 * So the frontend must never treat this as a closed set. `check-settings-agents.mjs` asserts
 * `model` is not a closed vocabulary and the box stays typable beside the menu; this type only
 * Whether one provider/model actually answered, run for real. (M45)
 *
 * A verdict and not a `Result` on the wire, for `AgentModels::problem`'s reason: the frontend
 * draws both outcomes as a sentence beside the row, and a rejected `invoke` would have to be
 * unwrapped through `errorText` into the same sentence anyway — with the difference that a
 * rejection reads as *cide* failing rather than the model.
 */
export type LlmModelTest = { 
/**
 * The `provider/model` that was tried, echoed so a late answer cannot be drawn against a
 * row the user has since edited.
 */
model: string, 
/**
 * Did it answer?
 */
ok: boolean, 
/**
 * One whole sentence, either way. The failure half is the provider's own words where there
 * were any — see `cide_agents::harness::opencode`'s `error_sentence`.
 */
detail: string, };
