// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlmProvider } from "./LlmProvider";
import type { ModelPool } from "./ModelPool";

/**
 * Every provider cide knows how to configure, and every pool built out of them.
 *
 * Two flat lists rather than maps keyed by id. The user types both keys, and a map would rewrite
 * the key on every keystroke and lose the row the moment two of them were briefly equal — the
 * argument [`crate::ClaudeCli::env`] already makes about `Vec<ClaudeEnvVar>` against `BTreeMap`.
 * For [`ModelPool::entries`] a map would also destroy the order, which is the entire feature.
 *
 * This rides every `cide://workspace-changed` to every window, like all of [`crate::Settings`],
 * so it must stay small — tens of rows, not a catalog. That is also why [`LlmProvider::Catalog`]
 * stores no model list: the 360 ids behind `openrouter` belong to opencode's cache, not to
 * cide's settings broadcast.
 */
export type LlmSettings = { 
/**
 * The providers, in the order the Settings screen draws them.
 */
providers: Array<LlmProvider>, 
/**
 * The pools. Named from a local agent override, never from a committed file.
 */
pools: Array<ModelPool>, };
