// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogResume } from "./LogResume";

/**
 * Where in the walk this page begins.
 */
export type LogCursor = { "kind": "newest" } | { "kind": "resume", token: LogResume, } | { "kind": "at", oid: string, } | { "kind": "after", oid: string, };
