// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogCursor } from "./LogCursor";
import type { LogRefs } from "./LogRefs";
import type { LogScope } from "./LogScope";
import type { Simplify } from "./Simplify";

/**
 * One request for a page of log.
 *
 * Everything about a view is in here, and that is deliberate: the walker holds no per-view
 * state between calls, so two panels asking for two different filters cannot interfere and a
 * window that is closed mid-walk leaves nothing behind. The continuation that *does* have to
 * survive a call is the token in [`LogCursor::Resume`], which travels with the request rather
 * than being remembered by the process — see [`LogResume`] for why that is not merely tidier.
 */
export type LogQuery = { scope: LogScope, refs: LogRefs, cursor: LogCursor, 
/**
 * Repo-relative path filter. `None` walks everything.
 *
 * Applied **per repository** under [`LogScope::Merged`], because a path is only meaningful
 * inside the repository that stores it and the same relative path in two roots is two
 * different files.
 */
path: string | null, 
/**
 * Follow the path across renames — git's `--follow`.
 *
 * Only meaningful with [`Self::path`], and like git's, single-path only. Ignored when
 * `path` is `None`; whether it was actually applied comes back as [`CommitPage::followed`]
 * rather than being assumed from the request, so a silently-ignored flag is visible.
 */
follow: boolean, simplify: Simplify, 
/**
 * Walk only first parents — git's `--first-parent`.
 *
 * Turns a merge-heavy history into the sequence of things that landed on this branch,
 * which is the reading most people want and almost nobody knows the flag for.
 */
firstParent: boolean, 
/**
 * Substring match against author name and email, case-insensitive. git's `--author`.
 */
author: string | null, 
/**
 * Substring match against the commit message. git's `--grep`.
 *
 * A substring and not a regex, on purpose: a regex from a text field is a way to hand a
 * user a walk that never finishes, and the search that people actually type is a ticket
 * number.
 */
text: string | null, 
/**
 * How many rows to produce. Capped in Rust — see `cide_git::history` — because a frontend
 * bug that asks for a million rows must not be able to allocate them here.
 */
limit: number, 
/**
 * How many commits the walk may **examine** while producing those rows.
 *
 * The second budget, and the one that keeps a filtered walk bounded. Without it,
 * `--follow` over a file touched twice in a forty-thousand-commit history walks the whole
 * repository — on the IPC thread — to fill a page of two. With it, the page comes back
 * short and honest with [`LogStop::Budget`], and the user's next scroll continues from the
 * frontier instead of starting again.
 */
scanLimit: number, 
/**
 * Compute the lane structure. `false` skips it entirely rather than computing it and
 * dropping it, which matters for the merged and filtered views where it would be
 * discarded anyway.
 */
graph: boolean, 
/**
 * Cap on concurrently open lanes. Rows needing more set [`GraphRow::overflow`] and the
 * excess is not drawn.
 *
 * A cap rather than "draw whatever there is" because the gutter is a fixed strip of chrome
 * beside a list: a repository whose `--all` view opens two hundred lanes would otherwise
 * size that strip to two hundred columns and leave four pixels for the commit summaries.
 */
graphLanes: number, };
