// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Harness } from "./Harness";
import type { TokenUsage } from "./TokenUsage";

/**
 * Which harness and model are behind a log line, for the card that opens one. (M80)
 *
 * # Why the card asks at all
 *
 * A run's pane draws `● bash  cargo test  1.2s #7` and nothing about *who ran it*. On one
 * machine a role may be an `opencode` pool that failed over twice, a `codex` the project's
 * overrides redirected it to, or the `claude` its file names — and the three are read back
 * from the same pane, in the same colours, days later. The two facts that answer "why did it
 * do that" are the harness and the model, and until M80 neither was anywhere on screen once
 * the run had left the Agents panel's live rows.
 *
 * `None` on a [`crate::LogLineDetail`] is the ordinary answer, not a failure: a shell pane's
 * structured log lines are the feature this card was built for and they belong to no run.
 */
export type LogRunInfo = { 
/**
 * The harness the standing child was **forked with**, which is not always the one the
 * role's file names — an override redirects it, and M78's whole lesson was that the two
 * answers drift silently. `AgentRegistry` reads it off the run, never off the definition.
 */
harness: Harness, 
/**
 * The model that child was given, spelled as the harness was told it: a pool candidate's
 * `provider/model`, the override's or the role's single model, or opencode's own resolved
 * default.
 *
 * `None` where cide named none and the CLI chose for itself — a `claude` run with no
 * `model:` in its definition, which is the common case. Drawn as a sentence saying so,
 * never as a blank: a blank beside a label reads as a broken dialog (`TaskDetailPending`'s
 * rule).
 */
model: string | null, 
/**
 * How far down its pool this run has fallen, as `2 of 3`, or `None` for a run with no
 * pool. The model above is *this* candidate, so without the position a failover is
 * invisible — the card would simply name a model nobody chose.
 */
poolPosition: string | null, 
/**
 * The last step's tokens, or `None` until the run has finished one.
 */
usage: TokenUsage | null, 
/**
 * The model's context window in tokens, where **this machine's configuration** states one.
 *
 * Only ever a number a user typed: `LlmModel::context`, looked up in the provider document
 * the child was forked with, by the pool candidate's provider **and** model id as two
 * separate keys. A catalogued model's window is the provider's business and cide holds no
 * table of them, and splitting a `provider/model` string to go looking would be inventing
 * the parser [`crate::PoolEntry`]'s header refuses to own. So this is usually `None`, and
 * the card then prints the token count with no percentage rather than a percentage of a
 * guess.
 */
contextLimit: number | null, };
