// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaneResume } from "./LaneResume";
import type { RepoResume } from "./RepoResume";

/**
 * Everything the walker needs to produce the *next* page, handed to the client and handed
 * back.
 *
 * # Why the continuation is on the wire instead of in a server-side cursor
 *
 * The obvious design keeps a live `git2::Revwalk` in a map keyed by a view id. It loses on
 * three counts, each of which was a real consideration rather than a hypothetical. A live
 * revwalk pins an open repository and a growing object cache per panel, and panels are cheap
 * to open and easy to forget to close — so the leak is the normal case, not the exceptional
 * one. It cannot survive the window being detached into another OS window, which is a gesture
 * this app treats as free. And it makes "the same view in two windows" two independent walks
 * over one mutable cursor, which is the class of bug the whole workspace-in-Rust design (ADR
 * 0002) exists to avoid.
 *
 * A token is a value. It can be duplicated, dropped, or replayed, and the worst outcome of any
 * of those is a page that is refused with [`LogStop::CursorLost`].
 *
 * # Why the resume types are the only structs here without `deny_unknown_fields`
 *
 * The whole point of [`Self::version`] is that an older build must be able to *recognise* a
 * token it cannot use, and answer [`crate::git::GitError::StaleLogCursor`]. With
 * `deny_unknown_fields`, a token from a newer build fails inside serde before the version
 * check ever runs, and the caller gets a deserialisation error naming a field instead of the
 * one refusal it knows how to recover from.
 */
export type LogResume = { 
/**
 * Format version of this token. Bumped whenever the shape below changes; a token whose
 * version this build does not know is refused, not guessed at.
 */
version: number, 
/**
 * Fingerprint of the [`LogQuery`] this token belongs to — every field of it except the
 * cursor.
 *
 * Checked before the token is used, because handing a token from one query to another
 * produces a page that is neither: the frontier was built under one path filter and the
 * budget accounting under another. The failure without this check is not a crash, it is a
 * log that quietly shows the wrong commits, which is the worst kind.
 */
key: string, 
/**
 * One entry per repository the scope named, in the scope's order.
 */
repos: Array<RepoResume>, 
/**
 * The graph's open columns, when the page that produced this token drew one.
 *
 * `None` when it did not. Resuming *with* a graph from a token that has no lane state
 * cannot continue columns that were never opened, so the next page starts its lanes fresh
 * and reports [`GraphOff::Rerooted`] rather than drawing edges into nothing.
 */
lanes: LaneResume | null, };
