// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the walk starts from, before any cursor is applied.
 */
export type LogRefs = { "kind": "head" } | { "kind": "branch", name: string, } | { "kind": "all" } | { "kind": "rev", spec: string, };
