// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a walk stopped producing rows.
 *
 * The reason a page needs this at all is that "no more rows" has six causes and only one of
 * them means the history is over. Collapsing them leaves the panel unable to decide whether to
 * keep the "load more" affordance, and — worse — unable to tell a shallow clone's floor from
 * the actual root commit, which reads to the user as *this project began here*.
 */
export type LogStop = "exhausted" | "page" | "budget" | "shallow" | "cursorLost" | "noSuchRef";
