// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoId } from "./RepoId";

/**
 * Which repositories one log walks.
 *
 * A project can hold several roots and each root its submodules, and "show me the history"
 * means different things in the two cases — so the caller says which, rather than the walker
 * guessing from how many repositories happen to be open.
 *
 * # A note that applies to every tagged union in this module
 *
 * This type is inbound (it is a field of [`LogQuery`], which carries `deny_unknown_fields`)
 * and yet it has no `deny_unknown_fields` of its own. That is not an oversight: **serde does
 * not support `deny_unknown_fields` on an internally tagged enum**, because the tag has to be
 * read out of the same map the fields come from and the buffering that requires is
 * incompatible with the strict check. [`crate::git::Selection`] lacks it for exactly this
 * reason and always has. The consequence is worth knowing rather than rediscovering: a
 * frontend that misspells a field inside one of these variants gets a `missing field` error if
 * the field was required, and silence if it was optional. Requests therefore keep their
 * optional fields on the *struct* side, where the strict check does apply.
 */
export type LogScope = { "kind": "one", repo: RepoId, } | { "kind": "merged", repos: Array<RepoId>, };
