// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A connected marketplace — a git repository that lists extensions. (M22)
 *
 * A string the *user* chooses, not a uuid, and for the same reason [`AgentId`] is one: it is
 * the directory name the clone lands in (`$XDG_STATE_HOME/cide/marketplaces/<id>/`), it is what
 * `extensions.json` keys its entries by, and it is what a person types to name one marketplace
 * apart from another in a sentence. A uuid is unreadable in all three positions, and the middle
 * one is decisive — a config file the user is expected to hand-edit cannot key its entries by a
 * value cide invented after the fact.
 *
 * Derived from the repository name on connect (`cide-marketplace` → `cide-marketplace`) and
 * disambiguated with a numeric suffix when that is taken, so the ordinary case needs no
 * decision from the user at all.
 *
 * Deliberately not validated here, exactly as [`AgentId`] is not. This crate is the wire shape;
 * `cide-ext` is where a name is checked against the character set that makes it safe to
 * `Path::join`, because that is the layer that knows the path to name in the refusal.
 */
export type MarketplaceId = string;
