// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capability } from "./Capability";
import type { ExtensionId } from "./ExtensionId";

/**
 * A row in a marketplace's index, whether or not it is installed.
 */
export type MarketplaceEntry = { id: ExtensionId, name: string, version: string, description: string, capabilities: Array<Capability>, 
/**
 * The version installed from this marketplace, when one is.
 */
installed?: string, 
/**
 * Whether the marketplace's copy declares a `version` different from the installed one —
 * the only thing an update offer compares, so a commit that ships code without a bump is
 * deliberately invisible here.
 */
updateAvailable: boolean, 
/**
 * One sentence, when this row cannot be installed — a manifest that did not parse, a
 * capability this build does not know. The row is still drawn; see [`Capability`].
 */
unavailable?: string, };
