// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which of the three layouts a markdown file was last read in. (M20)
 *
 * # Why this is a property of the *file* and not of the pane
 *
 * The same argument the whole of this module is built on, and it lands harder here than it
 * does for a scroll position. A `README.md` is a document somebody reads and a `NOTES.md` is
 * one they write, and the layout each wants is a fact about the file rather than about the
 * tile it happens to be showing in. A per-pane mode would also be lost by the one gesture a
 * reader makes most — closing the tab and opening it again from `Ctrl+P`.
 *
 * The cost is stated rather than hidden: a split showing one `.md` in two panes restores the
 * same layout into both, and switching in one does not switch the other until the next mount.
 * That is exactly the limitation [`ViewPosition::folds`] has, for exactly the same reason.
 *
 * Every file has one of these, including `main.rs`, where it is [`MarkdownView::Text`] and is
 * never read. A second store keyed on "only the markdown ones" would be a second answer to
 * "where was I in this file", which is the thing this module exists to have one of.
 */
export type MarkdownView = "text" | "split" | "preview";
