// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtProblem } from "./ExtProblem";
import type { MarketplaceEntry } from "./MarketplaceEntry";
import type { MarketplaceId } from "./MarketplaceId";
import type { MarketplaceState } from "./MarketplaceState";

/**
 * A connected marketplace.
 */
export type Marketplace = { id: MarketplaceId, 
/**
 * What its own `cide-marketplace.json` calls it, or the source's last path segment before
 * the index has ever been read.
 */
name: string, 
/**
 * The URL or local path it was connected by, verbatim as the user typed it.
 */
source: string, 
/**
 * Whether the source is reached by forking `git` or by libgit2 — see `cide_ext::market`.
 * On the wire because it is the difference between *"this will use your credential helper"*
 * and *"this is a directory on your disk"*, and the user should not have to infer it.
 */
authenticated: boolean, state: MarketplaceState, 
/**
 * The clone directory. Under `$XDG_STATE_HOME`, never in a project.
 */
path: string, entries: Array<MarketplaceEntry>, problems: Array<ExtProblem>, };
