// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PulledCommit } from "./PulledCommit";

/**
 * What `git merge <name>` did — the branch picker's *Merge into current branch*.
 *
 * Its own type rather than a reuse of [`FetchOutcome`], and the difference is honesty, not
 * taste: that struct's transport half (`remote`, `shelled_out`, `output`) and strategy ladder
 * (`strategy`, `rewritten`, `skipped`) are all lies for a merge that never touches the
 * network — reusing it would smuggle a branch name through a field documented as a remote.
 * `FetchOutcome::strategy`'s comment defends fetch and pull sharing one shape because one
 * frontend function turns both into sentences; a merge's sentences name the *source branch*,
 * which is a different set, so the honest shape is a different type with `branchModel`'s
 * `mergeNote` as its one sentence function.
 */
export type MergeOutcome = { 
/**
 * The ref merged in, exactly as the user picked it: `feature` or `origin/feature`.
 */
source: string, 
/**
 * The branch merged into — the one that was checked out.
 */
branch: string, 
/**
 * The branch simply moved forward; no merge commit exists.
 */
fastForward: boolean, 
/**
 * Where the branch was before, short. Equal to `new_oid` when the branch already
 * contained the source — and when conflicts landed, because a conflicted merge has not
 * moved `HEAD` yet.
 */
oldOid: string, newOid: string, 
/**
 * Commits the merge takes: reachable from the source, hidden behind the pre-merge tip.
 * Non-zero even when conflicts landed — the merge still brings them in once concluded.
 */
advanced: number, 
/**
 * `git diff --shortstat` between the two tips. Zeros while conflicts are pending, which
 * is the honest answer: nothing is different about the tree *yet*.
 */
filesChanged: number, insertions: number, deletions: number, 
/**
 * The commits taken, newest first, **capped in Rust** — same cap, same wire argument,
 * as [`FetchOutcome::commits`].
 */
commits: Array<PulledCommit>, 
/**
 * How many more there were beyond `commits`. Zero when the list is complete.
 */
moreCommits: number, 
/**
 * Paths left conflicted. **Non-empty is not a failure** — the same contract as
 * [`FetchOutcome::conflicts`]: real `MERGE_HEAD` state is on disk and the resolver
 * takes over.
 */
conflicts: Array<string>, };
