// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskId } from "./TaskId";

/**
 * One goal.
 */
export type Milestone = { 
/**
 * A short handle — `slice`, `p2` — that the gate command and the prompts name it by.
 */
id: string, title: string, 
/**
 * The task that holds this goal on the board. Work towards it is `subtaskOf` it.
 */
task?: TaskId, 
/**
 * Shell command, run with `sh -c` in the project root. Exit 0 is met.
 */
gate: string, 
/**
 * Seconds. `number` on the wire, not ts-rs's `bigint`: a day is 86,400 and a JavaScript
 * number holds that exactly, while a `bigint` would make every reader cast.
 */
timeoutSecs?: number, };
