// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { TaskId } from "./TaskId";
import type { TaskStatus } from "./TaskStatus";

/**
 * One task under a milestone: enough to draw a row and open the card. Outbound.
 */
export type MilestoneTask = { id: TaskId, title: string, status: TaskStatus, agent?: AgentId, 
/**
 * 0 for a direct subtask of the milestone's task, 1 for its subtasks, and so on.
 */
depth: number, };
