// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolEntry } from "./PoolEntry";

/**
 * A named, ordered list of models a run falls down. (M45)
 *
 * # Ordered, and the order is the whole feature
 *
 * A pool is not a set of equivalent models; it is a preference with fallbacks. The first entry is
 * what a run gets, and the rest are what it gets when that one is rate-limited, unreachable or
 * refuses to authenticate. So this is a `Vec` and the Settings screen has explicit move controls:
 * a sorted or set-shaped store would silently destroy the one thing the user is expressing.
 *
 * # Selection is sticky for a run
 *
 * An opencode run is one process per turn (`harness::opencode`'s header). A run that re-chose on
 * every turn would be a conversation whose turns were answered by different models with nothing
 * recording which. The choice therefore lives on the run as [`PoolChoice`], and only a failover
 * moves it.
 */
export type ModelPool = { 
/**
 * The name a local agent override refers to.
 *
 * A pool that an override names and that does not exist is a *refused dispatch* with a
 * sentence — never a silent fallback to the provider default, which would be a run answered
 * by a model nobody chose and billed to somebody who never agreed to it. That refusal is
 * affordable precisely because both halves are local: the person who made the inconsistency
 * is the person looking at the screen.
 */
name: string, 
/**
 * One line for the person choosing — "cheap first, then the subscription". Not prompt text;
 * nothing a model ever sees.
 */
description: string, 
/**
 * The entries, best first.
 */
entries: Array<PoolEntry>, };
