// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pair } from "./Pair";

/**
 * What the detail pane shows for a network.
 */
export type NetworkDetail = { id: string, name: string, driver: string, scope: string, internal: boolean, subnets: Array<string>, labels: Array<Pair>, 
/**
 * The containers attached, by name.
 */
attached: Array<string>, };
