// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What is at a path the user has typed or picked, for the location step's live hints.
 *
 * Every field is a fact about the disk *now*; the wizard re-probes as the path changes and
 * `project_new` re-checks everything it relies on rather than trusting an old probe.
 */
export type NewProjectProbe = { 
/**
 * The path as cide will use it: `~` expanded, relative paths refused (see `problem`).
 */
path: string, exists: boolean, isDir: boolean, 
/**
 * How many entries the directory already holds; `0` for one that does not exist. The
 * wizard keeps them — it never deletes — but says so, because "new project" in a folder full
 * of somebody's files is usually a mistyped path.
 */
entries: number, 
/**
 * The directory is itself a work tree (`.git` inside it).
 */
hasGit: boolean, 
/**
 * The nearest enclosing work tree, when the directory is *inside* one without being its
 * root. Subagent worktrees would then be the enclosing repository's, which is rarely meant.
 */
insideRepo?: string, hasOpenspec: boolean, hasCide: boolean, 
/**
 * A project over this path is already open; creating will activate it.
 */
openAlready: boolean, 
/**
 * Why this path cannot be used at all, as a sentence. `None` means it can.
 */
problem?: string, 
/**
 * Why the `openspec` CLI cannot be run, as a sentence; `None` when it can. Carried on the
 * probe so the OpenSpec step can say so *before* the user commits, not as a failed step.
 */
openspecMissing?: string, };
