// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One lane left open at a page boundary.
 *
 * Named `…Wire` because `cide-git` has its own richer `OpenLane` with the walker's bookkeeping
 * in it; this is the part that has to survive the round trip, and keeping the names distinct
 * stops the two being confused at the seam where one is built from the other.
 */
export type OpenLaneWire = { 
/**
 * Which column, left to right from zero.
 */
column: number, 
/**
 * The commit this lane is waiting for. The row that draws that oid is the row that closes
 * this lane.
 */
awaits: string, 
/**
 * Index into the renderer's palette, not a colour value. The palette is a CSS concern and
 * putting an `#rrggbb` on the wire would make the graph ignore the theme.
 */
color: number, };
