// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeEnvVar } from "./ClaudeEnvVar";
import type { OpencodeInjections } from "./OpencodeInjections";

export type OpencodeCli = { binary: string, args: Array<string>, env: Array<ClaudeEnvVar>, inject: OpencodeInjections, };
