// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Harness } from "./Harness";

/**
 * A partial update to [`OrchestrationConfig`]. `None` means "leave this alone".
 *
 * Mirrors [`crate::SettingsPatch`]'s shape deliberately — per-field `Option` with
 * `#[ts(optional)]`, so a caller flipping one switch need not restate the other two — and it is
 * allowed to, because none of these three fields is itself nullable. That is the exact test
 * [`crate::TaskEdit`] fails and explains at length.
 *
 * `Clone` rather than `Copy` since M79, for [`OrchestrationConfig`]'s reason.
 */
export type OrchestrationPatch = { 
/**
 * Turning this on writes `.cide/config.json`, and `agents_config_set` refuses it with a
 * sentence when the project is not a git repository — worktree isolation has nothing to
 * build on there, and a silent fallback to a shared tree is how two agents clobber one file
 * with nobody told.
 */
enabled?: boolean, maxConcurrent?: number, harness?: Harness, finishInNewTab?: boolean, autoSpin?: boolean, 
/**
 * Clamped by `AgentsConfig::apply` rather than refused, `max_concurrent`'s trade.
 */
autoSpinAfterSecs?: number, 
/**
 * Flattened to one line by `AgentsConfig::apply` before it reaches the file: this string is
 * typed into a terminal, where a newline is another Enter.
 */
autoSpinPrompt?: string, 
/**
 * Flattened to one line by `AgentsConfig::apply`, `auto_spin_prompt`'s reason.
 */
reviewPrompt?: string, 
/**
 * `agents.isolateEnv`, whole: the list replaces the file's, and an empty one turns
 * isolation off. `AgentsConfig::apply` drops a name `cide_core::isolated_env::check_var`
 * refuses; the `cide_agents_config` tool refuses it first, with the sentence. (M92)
 */
isolateEnv?: Array<string>, 
/**
 * `agents.isolateEnvShare`, whole, `isolate_env`'s terms.
 */
isolateEnvShare?: Array<string>, 
/**
 * `agents.verifyExclusive`.
 */
verifyExclusive?: boolean, };
