// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Harness } from "./Harness";

/**
 * The `agents` block of `.cide/config.json`.
 *
 * # Why this is not part of [`crate::Settings`]
 *
 * `Settings` is **global**: it lives at `Workspace.settings`, it is written to
 * `$XDG_STATE_HOME/cide/workspace.json`, and it rides every `cide://workspace-changed` to every
 * window of every open project. None of that is true of this.
 *
 * "This project runs subagents, under these roles, at this concurrency" is a property of the
 * **checkout**. It belongs beside `.cide/tasks.json` and `.cide/agents/*.md`; it is reviewable
 * in a pull request, where a teammate can see that a repository has started dispatching agents;
 * and above all it must not follow the user into an unrelated project. A global switch would
 * mean enabling subagents once, for a repository the user trusts, silently arms every other
 * checkout they open afterwards.
 *
 * `Project` has no settings field, and this change does not add one — the config is read fresh
 * from disk on demand rather than mirrored, for the reason the module header gives.
 * Correspondingly this config gets **no row** on the Settings screen: `SECTIONS` is global
 * settings and `useSettings.patch` writes a [`crate::SettingsPatch`], so a row there would have
 * to explain that it means something different from every other row on the screen.
 *
 * [`crate::SettingsSection::Agents`] is not that row and does not contradict this, which is
 * worth stating because the two read like opposites. That section is not a page of settings; it
 * is an **editor for files** — `.cide/agents/*.md` and their global twins — reached through the
 * Settings shell because that is where a person looks for *configure the thing*, and writing
 * through `agents_save`/`agents_delete` rather than through a patch. It is where the switches
 * in *this* struct will eventually be drawn too, and when they are they will still be a
 * per-project file write and still not a [`crate::SettingsPatch`]. The rule the paragraph above
 * is really stating survives intact: nothing about a project rides `Workspace.settings`.
 *
 * # Why this is `Clone` and no longer `Copy` (M79)
 *
 * It was `Copy` until [`Self::auto_spin_prompt`] arrived, and a prompt is a `String` a person
 * wrote. The alternative — keeping `Copy` by leaving the prompt off the wire — would have put
 * the one field on this screen that a user actually composes behind a hand edit of a JSON file,
 * which is the state `AgentDraft` exists to get *out* of.
 */
export type OrchestrationConfig = { 
/**
 * Off in the absence of the file, so a project that has never heard of this feature can
 * never spawn anything. The single most important default in the module.
 */
enabled: boolean, 
/**
 * How many runs may be live across the whole project, whatever the per-role ceilings say.
 *
 * 2 rather than "the number of roles": every run is a full `claude` with its own context
 * window and its own bill, and a default that started six of them the first time somebody
 * pressed the button would be a default nobody forgives.
 */
maxConcurrent: number, 
/**
 * The harness a role gets when its definition does not name one.
 */
harness: Harness, 
/**
 * A finished run's note opens a fresh Claude tab instead of typing into the console. (M79)
 *
 * `cide_agents::config::AgentsConfig::finish_in_new_tab` carries the argument; this is the
 * same key, on the wire because the user asked for it in Settings. Note it is **under**
 * `nudgeOrchestrator`, which stays disk-only: that key answers *announce my subagents at
 * all*, this one answers *where*.
 */
finishInNewTab: boolean, 
/**
 * cide wakes this project when it goes quiet with work still open. (M79)
 */
autoSpin: boolean, 
/**
 * How long that quiet must last, in seconds. The **stored** number, not the clamped one —
 * `AgentsConfig::to_wire` says why.
 */
autoSpinAfterSecs: number, 
/**
 * What the spun run is told. Empty means *use the one cide ships*, decided in
 * `AgentsConfig::spin_prompt` and never here.
 */
autoSpinPrompt: string, 
/**
 * What a reviewer tab is told, as a template with `{placeholders}`. Empty means *use the
 * one cide ships*, decided in `AgentsConfig::review_prompt_template`. (M84)
 */
reviewPrompt: string, };
