// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectOverrides } from "./ProjectOverrides";

/**
 * The answer to an [`OverrideProfileOp`]: the live table and the profiles, so a screen redraws
 * both from one reply rather than guessing what a switch did to the rows.
 */
export type OverrideProfilesState = { overrides: ProjectOverrides, active?: string, 
/**
 * Profile names, sorted.
 */
names: Array<string>, };
