// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who owns the path, in whatever detail this platform can answer.
 *
 * The numbers are always present on unix and the names are best-effort: a uid with no passwd
 * entry is the normal case inside a container, and the row still has to render. The frontend's
 * rule is *name when there is one, number always* — `ivan (1000)` — so a missing name costs a
 * word and never the fact.
 */
export type Owner = { uid: number, gid: number, user?: string, group?: string, };
