// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QrMatrix } from "./QrMatrix";

/**
 * An open pairing window.
 *
 * Held in memory and never written down: a code on disk outlives the two minutes it is good
 * for. The panel shows [`Self::grouped`] and a device may type it back with or without the dash.
 */
export type PairingInvite = { 
/**
 * The code as typed: eight characters, no punctuation.
 */
code: string, 
/**
 * The code as shown: `XXXX-XXXX`, because eight unbroken characters are read off a screen
 * wrongly.
 */
grouped: string, 
/**
 * Everything a device needs, for a scan or a paste.
 */
uri: string, 
/**
 * `uri` as a QR module grid, when it could be encoded.
 *
 * An `Option` rather than a required field, because the QR is a convenience over a thing
 * the user can always type: `code` and the address are the payload, and the panel draws
 * them whatever happens here. An encoder that refused would otherwise be able to stop a
 * pairing that has nothing wrong with it.
 */
qr?: QrMatrix, expiresUnixMs: number, };
