// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PairingAttempt } from "./PairingAttempt";

/**
 * How the pairing window the panel opened is getting on.
 *
 * One answer rather than two commands, because the panel asks both halves on the same event and
 * two round trips could disagree about the same instant — a device redeeming the code between
 * them would be reported as *still pairing* against a window that had already closed.
 *
 * `open` is the authority on whether the modal should still be on screen, and it is read from
 * the device store rather than inferred: the code is taken by a redemption, dropped by a wrong
 * guess and forgotten at the end of its two minutes, and all three are the same news to a panel
 * holding a QR nobody can use any more. Inferring it from the device list would have covered
 * only the first, and would have left a dead code on screen after an expiry.
 */
export type PairingProgress = { 
/**
 * Whether a code is still outstanding.
 */
open: boolean, 
/**
 * The device standing at the pairing step right now, if one is. See [`PairingAttempt`].
 */
attempt?: PairingAttempt, };
