// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutNode } from "./LayoutNode";
import type { Pane } from "./Pane";
import type { PaneId } from "./PaneId";

/**
 * A tab's pane layout.
 *
 * Pane *data* lives in a side map rather than inside the leaves, so looking a pane up by
 * id does not mean walking the tree, and `LayoutNode` stays small enough to clone freely
 * during a rebalance.
 *
 * Invariant, asserted in `cide-core` tests: the set of leaf ids equals the key set of
 * `panes`, exactly.
 */
export type PaneTree = { root: LayoutNode, focused: PaneId, 
/**
 * Maximizing is **not** a tree mutation — it is a flag the renderer honours by giving
 * one pane the whole grid area and hiding its siblings. That keeps restore exact and
 * costs no terminal reflow.
 */
maximized: PaneId | null, panes: { [key in PaneId]: Pane }, };
