// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a pane may be closed.
 *
 * The pinned Claude tab's first pane is `Primary`: closing it while it is the only leaf
 * returns `Err(PanePrimary)` so the project console can never be emptied by accident.
 */
export type PaneRole = "primary" | "auxiliary";
