// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionRef } from "./ExtensionRef";
import type { PanelDef } from "./PanelDef";

/**
 * A panel in the resolved registry.
 */
export type PanelBinding = { 
/**
 * `ext:<marketplace>.<extension>.<panel>` — the `ActivityView` the rail and the sidebar use.
 */
view: string, def: PanelDef, extension: ExtensionRef, };
