// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a pane is showing.
 */
export type PaneKind = "claude" | "shell" | "diff" | "editor";
