// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a pane may be closed.
 *
 * The pinned Claude tab's first pane is `Primary`: closing *or detaching* it returns
 * `Err(PanePrimary)` however many panes the tab holds, so the project console can never
 * lose its conversation — not by accident, and not by splitting first.
 */
export type PaneRole = "primary" | "auxiliary";
