// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a partial selection was refused.
 *
 * These are the cases where synthesizing a unified diff is *silently* wrong rather than
 * loudly wrong, which is why each one is a distinct tag: the frontend has to be able to
 * explain the refusal, and "patch failed" explains nothing.
 */
export type PartialRefusal = "binary" | "submodule" | "typeChange" | "deletion" | "rename" | "noNewlineOrdering" | "empty";
