// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A name a paste is about to land on that something already occupies.
 *
 * Answered by `fs_paste_plan` **before** anything is written, which is the whole shape of this
 * feature: the dialog collects every answer, and only then is `fs_paste` called. A user who
 * cancels at the fourth of seven questions has had nothing written on their behalf, so there
 * is no partial paste to describe and no half-finished folder to clean up.
 *
 * The counts are what make *Replace* an informed answer rather than a dare. A file collision
 * costs one file; a folder merge can cost hundreds, and the number is the only way to know
 * that before choosing.
 */
export type PasteCollision = { source: string, 
/**
 * The path that is already taken: `dest_dir` joined with the source's own name.
 */
dest: string, 
/**
 * The last component, which is what the dialog says.
 */
name: string, 
/**
 * Both sides are directories, so *Replace* means merge. See [`PasteChoice::Replace`].
 */
merge: boolean, 
/**
 * *Replace* is refused for this collision, and this sentence says why.
 *
 * Set when one side is a directory and the other is not — at the top, or anywhere inside a
 * folder being merged. Swapping a file for a folder is not a replacement of anything, and
 * guessing which one the user meant to keep is not a guess worth making. The dialog offers
 * only *Keep both* and *Cancel* when this is set, and `fs_paste` refuses a `Replace`
 * decision for it even if one is sent.
 */
blocked: string | null, 
/**
 * How many existing **files** *Replace* would overwrite. 1 for a file-on-file collision.
 */
replaces: number, 
/**
 * Entries in the destination folder a merge would leave completely alone.
 *
 * A folder counts as one entry and is not descended into: this number exists to say "your
 * files are still there", and inflating it by counting a `node_modules` recursively would
 * make it read as noise.
 */
keeps: number, 
/**
 * The first few relative paths `replaces` counted, so the dialog can name names.
 */
sample: Array<string>, 
/**
 * The preview walk hit its budget: `replaces` and `keeps` are lower bounds.
 *
 * Reported rather than swallowed. "at least 4096 files" is an answer; a wrong exact number
 * in a dialog about data loss is not.
 */
truncated: boolean, };
