// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one pasted path became.
 *
 * One of these per *source*, not per file on disk: pasting a directory of 4000 files is one
 * entry describing the directory. The counts inside it are what the panel says afterwards.
 */
export type PastedEntry = { source: string, 
/**
 * Where it landed.
 *
 * A path that was already occupied only when `replaced` is non-zero — that is, only when
 * the caller sent a `Replace` decision for this source. Otherwise the name moved out of
 * the way instead; see `renamed`.
 */
dest: string, 
/**
 * The destination took a *different* name because the one it wanted was taken.
 *
 * Reported rather than left for the user to notice, because the other reading of a paste
 * that quietly produced `main copy.rs` is that it did nothing: the row the user was
 * looking at is still there, still holding the older file.
 */
renamed: boolean, 
/**
 * Entries inside a copied directory that are neither a file, a directory nor a symlink —
 * fifos, sockets, devices — and were left behind.
 *
 * Copying them is either meaningless (a socket) or a hang (reading a fifo waits for a
 * writer that never comes), and refusing a whole paste over one stray `.sock` in a project
 * would be the worse answer. Counted so the panel can say so.
 */
skipped: number, 
/**
 * Existing files this entry overwrote, because the user chose [`PasteChoice::Replace`].
 *
 * Zero for every paste nobody explicitly answered *Replace* to, which is the invariant
 * worth being able to read off the result: a non-zero count here can only come from a
 * decision that was sent with the command.
 *
 * More than one when a folder was merged: the answer was given about `src`, and the files
 * it overwrote were inside it. That is the number the panel says afterwards, because
 * "replaced src" describes something the user cannot check by looking.
 */
replaced: number, };
