// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PasteChoice } from "./PasteChoice";

/**
 * One answer, bound to the source it answers for.
 *
 * A list of pairs rather than a map keyed by path: JSON object keys would make a path with a
 * `.` or a `/` in it a key nobody can round-trip safely, and the order the sources were given
 * in is the order the questions were asked in.
 */
export type PasteDecision = { 
/**
 * Exactly one of the paths in the paste's `sources`, matched by equality.
 */
source: string, choice: PasteChoice, };
