// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the path turned out to be, decided by `symlink_metadata` and never by the name.
 *
 * [`PathKind::Symlink`] wins over the other two: a link to a directory is reported as a link,
 * and [`FileProperties::symlink_target`] says where it goes. The alternative — following first
 * and reporting the destination's kind — is the bug this whole enum exists to prevent, and it
 * is spelled out on [`FileProperties`].
 */
export type PathKind = "file" | "dir" | "symlink" | "other";
