// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConsoleHarness } from "./ConsoleHarness";

export type PeerChatSelection = { harness: ConsoleHarness, 
/**
 * Native model identifier; OpenCode uses provider/model. None inherits the CLI default.
 */
model: string | null, };
