// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneId } from "./PaneId";

export type PeerChatReceipt = { id: string, sender: PaneId, status: string, detail: string, };
