// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PromptOption } from "./PromptOption";

/**
 * A permission prompt, as a device is shown it.
 *
 * Produced by `cide_claude::permission::parse` and carried here, rather than declared in that
 * crate and converted: `cide-ipc` is where a wire type lives, and a domain struct plus a wire
 * struct plus a `From` between them is three places for a field to go missing.
 */
export type PermissionPrompt = { 
/**
 * The lines above the options, in order, with the box drawing taken off.
 */
question: Array<string>, options: Array<PromptOption>, 
/**
 * Which option the TUI has highlighted, when it marks one.
 */
selected?: number, 
/**
 * A hash of the normalised block, and **the guard on every answer**.
 *
 * Over a network the prompt a person tapped can already have been replaced by the *next*
 * one. Without this, a tap on *"No, tell Claude what to do differently"* lands as *"1. Yes"*
 * on a prompt that arrived 300 ms later, and approves whatever it was asking about. The
 * answer is refused when this has moved.
 */
digest: string, };
