// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PickerRow } from "./PickerRow";

/**
 * One frame of picker results.
 *
 * A frame, not "the results": the file index streams in while the user is already typing,
 * so the honest answer to a query is always "here is the best 200 of what I have seen so
 * far, and I am still reading". `matched`/`total` are the two numbers behind the mock's
 * `6 of 2,418` counter, and they keep climbing during the walk.
 */
export type PickerFrame = { 
/**
 * At most the `limit` the caller asked for, capped in Rust at 200. A keystroke must
 * never ship 100k rows over IPC — the overlay draws about twelve.
 */
items: Array<PickerRow>, 
/**
 * `matched_item_count()`: how many candidates the query matches.
 */
matched: number, 
/**
 * `item_count()`: how many candidates exist so far.
 */
total: number, 
/**
 * The matcher is still working — either the walk is still injecting, or the query is
 * still being scored. The overlay polls again while this is true.
 */
running: boolean, 
/**
 * Echoed so a frame that arrives after the user has typed on can be discarded rather
 * than painted under the new query.
 */
query: string, };
