// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolEntryState } from "./PoolEntryState";

/**
 * One configured pool. (M90)
 */
export type PoolState = { name: string, description: string, entries: Array<PoolEntryState>, };
