// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One model request's generated tokens against its duration. (pool stats)
 *
 * Two integers rather than a rate so the report keeps `Eq` and the card does the one division.
 */
export type PoolStepRate = { tokens: number, ms: number, };
