// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolEntry } from "./PoolEntry";
import type { PoolSkip } from "./PoolSkip";

/**
 * One entry passed over, and why. (M90)
 */
export type PoolSkipped = { entry: PoolEntry, 
/**
 * Zero-based position in the run's own list.
 */
index: number, skip: PoolSkip, };
