// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolEntry } from "./PoolEntry";
import type { PoolRefusal } from "./PoolRefusal";
import type { PoolSkipped } from "./PoolSkipped";

/**
 * Something a pool did, for the card's "recent decisions". (M90)
 */
export type PoolEventKind = { "kind": "started", entry: PoolEntry, index: number, of: number, skipped: Array<PoolSkipped>, benchedFallback: boolean, } | { "kind": "refused", entry: PoolEntry, reason: PoolRefusal, untilUnixMs: number, } | { "kind": "reset", entry: PoolEntry | null, rewound: number, };
