// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `provider/model` in a pool, with the variant it should run at.
 *
 * # Three fields and not one `provider/model` string
 *
 * A model id **contains slashes**: `lmstudio/openai/gpt-oss-20b` is a real id, and
 * `unsloth/Qwen3.8-27B-GGUF:UD-Q4_K_M` carries a colon as well. A stored flat string would need a
 * split rule to get the provider back out — a parser cide would have to invent, own, and get
 * wrong at the first id that broke the assumption. Stored apart, cide only ever *joins*, which
 * cannot be wrong, and `--variant` (a separate flag on the argv) has somewhere to live.
 */
export type PoolEntry = { 
/**
 * An [`LlmProvider::id`] — including an [`LlmProvider::External`] one.
 */
provider: string, 
/**
 * A model id under that provider.
 *
 * cide refuses nothing here: for a catalogued or external provider it holds no list to refuse
 * against, and for a custom one the list is a shortlist. [`crate::AgentModels`]'s rule — a
 * menu, not a rule.
 */
model: string, 
/**
 * `--variant`. Blank means the model's own default.
 *
 * **When set it wins over the role's `effort:`**, and that is a decision rather than an
 * accident. A pool entry names a model *and how hard it should think* as one selectable
 * target — `gpt-5.1-codex-max` at `xhigh` is a different target from the same model at `low`
 * — while a role's `effort:` was written for whichever model the role itself named. The role
 * keeps its `effort:` for every entry that leaves this blank, so the only loser is an entry
 * that explicitly disagreed.
 *
 * The concrete failure this prevents: each model declares its own variant set (`gpt-5.2`
 * offers none/low/medium/high/xhigh, `gpt-5.1-codex-mini` only medium/high), so a role-level
 * `effort: xhigh` carried onto the candidate a rate limit fell over to would be refused
 * outright by the CLI — turning a recoverable failure into a hard one at the worst moment.
 */
variant: string, 
/**
 * How many runs may be on this entry at once, across every project. `None` is no limit.
 *
 * # A pool is a preference *and* a set of slots
 *
 * Without this a pool only moved a run down when a provider refused it — so a subscription
 * that allows four sessions took a fifth, which the provider then rate-limited, which failed
 * over, which is a round trip and a burnt turn to learn what the user already knew. With it,
 * admission (`cide_app::agents::admit_a_pass`) puts a run on the first entry that has room,
 * and a pool whose every entry is full keeps the run *queued* rather than overcommitting one.
 *
 * **Counted across projects**, because pools are global settings and the thing the number
 * describes — a provider account's concurrency — does not know which project asked.
 *
 * `0` is not a value: [`LlmSettings::cleaned`] turns it into `None`, since an entry nobody
 * may run on is an entry to delete, and a stored `0` would be a pool that queues for ever
 * with no sentence saying why.
 */
maxRunning?: number, };
