// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the provider an entry names can be used at all. (M90)
 */
export type PoolProviderState = "ready" | "disabled" | "missing";
