// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectId } from "./ProjectId";
import type { RunId } from "./RunId";
import type { RunState } from "./RunState";

/**
 * A run standing on, or waiting for, a pool target. (M90)
 */
export type PoolRunRef = { run: RunId, agentLabel: string, project: ProjectId, state: RunState, 
/**
 * `2 of 6`, as the run's own row says it.
 */
position: string, 
/**
 * The row's sentence — why a waiting run is waiting, or what its last failover was.
 */
note: string | null, };
