// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolBench } from "./PoolBench";
import type { PoolEntry } from "./PoolEntry";
import type { PoolProviderState } from "./PoolProviderState";
import type { PoolRunRef } from "./PoolRunRef";

/**
 * One entry of one configured pool, as it stands right now. (M90)
 */
export type PoolEntryState = { entry: PoolEntry, provider: PoolProviderState, 
/**
 * Slot-holding runs on this target in every project — what `maxRunning` is a ceiling on.
 */
running: number, runs: Array<PoolRunRef>, 
/**
 * `None` when admission is not steering around it.
 */
bench: PoolBench | null, };
