// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PoolRefusal } from "./PoolRefusal";

/**
 * Why admission passed over one entry on its way to the one a run started on. (M90)
 */
export type PoolSkip = { "kind": "full", running: number, max: number, } | { "kind": "benched", reason: PoolRefusal, untilUnixMs: number, };
