// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a **Ctrl+click** is about to do, decided before anything expensive runs.
 *
 * # Why the gesture needs a third command at all
 *
 * IDEA's Ctrl+click is two actions wearing one chord: on a *reference* it jumps to the
 * declaration, on a *declaration* it lists the usages. Deciding which is a question only the
 * language server can answer, so it is a round trip — and the Ctrl-hover underline has to make
 * the same decision, on pointer motion, without ever running the expensive half.
 *
 * So the discriminator is its own answer. [`Self::Declaration`] says "the caret is already on the
 * declaration, so the click means Find usages" **without** having searched for any, which is what
 * makes the underline affordable: hovering a declaration costs one `textDocument/definition`, not
 * a whole-workspace reference search.
 *
 * The hover and the click consume this same value, from the same cache entry. That is the whole
 * guarantee that the underline never promises something the click will not do — see
 * `ui/src/editor/codeIntel.ts`.
 *
 * Four variants and never a rejected promise, for the reason [`DefinitionAnswer`] states one type
 * up: "still indexing" and "there is nothing here" are different answers and a rejection carries
 * neither.
 */
export type ProbeAnswer = { "kind": "definition", path: string, line: number, column: number, 
/**
 * Same flag, same meaning and same producer as
 * [`DefinitionAnswer::Found::interface_method`], so Ctrl+click and Ctrl+B agree about
 * what they are about to do. The hover reads this value too and ignores it: the
 * underline promises "this jumps somewhere", which stays true either way.
 */
interfaceMethod: boolean, } | { "kind": "declaration" } | { "kind": "notFound" } | { "kind": "unavailable", reason: string, };
