// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pane } from "./Pane";
import type { PaneId } from "./PaneId";
import type { ProjectId } from "./ProjectId";
import type { ProjectRoot } from "./ProjectRoot";
import type { SessionId } from "./SessionId";
import type { Tab } from "./Tab";
import type { TabId } from "./TabId";

/**
 * One opened project: a header tab, or a whole window in `PerProject` mode.
 */
export type Project = { id: ProjectId, name: string, 
/**
 * Display form of the primary root, e.g. `~/work/cide`.
 */
displayPath: string, 
/**
 * CSS colour for the header tab's dot, e.g. `var(--accent)`.
 */
dot: string, 
/**
 * A project may hold several roots and nested submodules. Never empty; `roots[0]` is
 * the primary root and supplies `display_path`.
 */
roots: Array<ProjectRoot>, 
/**
 * `tabs[0]` is **always** the pinned Claude console. Enforced in `cide-core`.
 */
tabs: Array<Tab>, activeTab: TabId, 
/**
 * Panes torn out into their own windows.
 *
 * A detached pane cannot stay in its tab's `panes` map: the tree invariant is that the
 * leaf set and the key set are equal, and its leaf is gone. It has not stopped
 * belonging to the project though — its session is still running, and `WindowRole::
 * DetachedPane` records where it re-docks — so it waits here rather than being
 * destroyed and rebuilt, which would lose the binding to its conversation.
 */
detached: { [key in PaneId]: Pane }, 
/**
 * Immortal while the project is open. For a Claude pane this id *is* the value passed
 * to `claude --session-id`, so restoring a workspace needs no extra bookkeeping to map
 * a pane back to its conversation.
 */
primarySession: SessionId, };
