// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectOverrides } from "./ProjectOverrides";

/**
 * One project's named override tables, and which of them is live. (M123)
 *
 * # Why whole tables, not per-row presets
 *
 * The gesture this serves is "codex is out of quota; move this project onto something else,
 * and back tomorrow". That touches the project-wide row *and* every role row that named codex
 * with its own model and effort, so the unit that switches is the whole [`ProjectOverrides`].
 * A per-row preset would leave the user re-picking a preset on every row, which is the chore.
 *
 * # The active profile is the live table
 *
 * While a profile is active, every edit to the live table is mirrored into it
 * ([`AgentOverrides::set_project`]), so switching away never loses a change and there is no
 * "unsaved" state for the screen to draw. The alternative — a snapshot saved on demand — was
 * refused: a switch that silently discards the afternoon's edits is the failure a person only
 * finds out about when they switch back.
 */
export type ProjectProfiles = { 
/**
 * The profile the live table belongs to, or `None` when it belongs to none.
 */
active?: string, 
/**
 * Name → table.
 */
profiles: { [key in string]: ProjectOverrides }, };
