// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProxyTarget } from "./ProxyTarget";

/**
 * Which children the proxy settings reach.
 *
 * # The default is today's behaviour, exactly, and that is the whole requirement
 *
 * The population that has configured a proxy at all is, by construction, people for whom the
 * current arrangement works. Flipping any of these three would break one of them silently —
 * a proxy failure surfaces as a hang or a timeout with nothing on screen naming cide — so the
 * new capability is opt-in and the defaults reproduce the shipped behaviour: panes proxied,
 * cide's own `git` left exactly as it was.
 *
 * `Default` is therefore **hand-written**. `#[derive(Default)]` would give
 * `ProxyTarget::Configured` for all three, which silently puts every existing user's `git`
 * onto cide's proxy — the one change this type exists to make impossible by accident.
 *
 * And the defaults are not the only guard: `cide_core::persist` migrates a schema-1
 * `workspace.json` by **writing this object into the document**, rather than letting the
 * serde default supply it. The difference matters the day somebody decides a fresh install
 * should default to claude-only: with the value on disk that is a change to new installs,
 * and with it defaulted it is a silent re-scoping of every live configuration.
 */
export type ProxyScope = { 
/**
 * `claude` panes **and** the headless one-shot lane (commit messages, explanations).
 *
 * One field for both because they are one thing to a user: a `claude` cide started. The
 * one-shot lane never read the proxy setting at all before this field existed — it built
 * its own `std::process::Command` and inherited cide's raw environment — which is why
 * this doc names it explicitly rather than leaving it to be discovered.
 */
claude: ProxyTarget, 
/**
 * `$SHELL` panes.
 *
 * The case the request did not name, so the choice is stated rather than assumed: a
 * shell pane is the *user's shell*, and a `git pull` typed into one follows this setting
 * rather than [`Self::git`]. Defaulting it to anything but `Configured` would break the
 * corporate user who opens a shell pane to run `npm install` through their proxy today.
 */
shells: ProxyTarget, 
/**
 * cide's own `git` shell-outs: the Push and Fetch/Pull buttons, and nothing else.
 *
 * **`Untouched` by default and it has to be.** See [`ProxyTarget`]: today git inherits
 * cide's environment, `Configured` would move it onto cide's proxy instead, and `Direct`
 * would take a working corporate push away. Only "leave it alone" reproduces what is
 * already on people's machines.
 */
git: ProxyTarget, };
