// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What cide does about a divergence that **git config says nothing about**.
 *
 * The last step of the resolution order — `branch.<name>.rebase`, then `pull.rebase`, then
 * this — and the only one that can answer `Ask`.
 *
 * A separate enum from [`PullStrategy`] rather than a fourth variant of it, because `Ask` is
 * not a strategy: it is a request for a dialog. A fourth variant would be representable on a
 * [`PullRequest`], where it would mean nothing and every match would need an unreachable arm.
 */
export type PullDefault = "ask" | "fastForward" | "merge" | "rebase";
