// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a pull integrates a divergence.
 *
 * On a [`PullRequest`] it is an instruction; on a [`FetchOutcome`] it is a report of what
 * actually happened.
 *
 * `FastForward` means **fast-forward only**: advance when the upstream already contains the
 * branch, and refuse with [`GitError::NotFastForward`] otherwise. That is exactly what
 * `cide_git::pull` did before merge and rebase existed, which is why it is a value here and
 * not a third radio button in the dialog — see `cide_git::pull`'s header. A user who wants
 * today's behaviour permanently sets it in Settings; the dialog does not offer it, because
 * it is the one answer that always fails in the only situation the dialog appears in.
 */
export type PullStrategy = "fastForward" | "merge" | "rebase";
