// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `git.push`, including whatever the transport said.
 */
export type PushOutcome = { remote: string, refspec: string, 
/**
 * True when the push went through the `git` binary because a credential helper is
 * configured — libgit2 cannot drive an interactive helper.
 */
shelledOut: boolean, 
/**
 * stderr of the `git push`, or libgit2's progress text. This is where "Everything
 * up-to-date" and the remote's own messages live, and users read them.
 */
output: string, };
