// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionSummary } from "./SessionSummary";
import type { UnsavedTab } from "./UnsavedTab";

/**
 * Whether closing may proceed, and what it would cost.
 *
 * Both lists are empty in the common case, and that is the case where no dialog should
 * appear at all. A confirmation that fires whenever a process exists is one users learn to
 * dismiss without reading, which is worse than none.
 *
 * The two lists are separate because the two risks are not the same risk, and the
 * confirmation has to word them differently:
 *
 * * `unsaved` is **destruction**. Those edits exist nowhere else; closing loses them.
 *   Always reported, whatever the settings say — see `Settings::
 *   confirm_close_with_live_session`, which is about sessions and has no authority here.
 * * `blocking` is **interruption**. A `Busy` or `AwaitingPermission` session loses its
 *   turn, not its transcript: the conversation resumes with `claude --resume`. This list
 *   is governed by that setting, and is empty when the user has turned it off.
 */
export type QuitDecision = { blocking: Array<SessionSummary>, unsaved: Array<UnsavedTab>, };
