// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteBind } from "./RemoteBind";

/**
 * How a phone reaches this cide. (M72)
 *
 * **Off by default, and the toggle is a capability grant rather than a preference.** Everything
 * else on the Settings screen changes what cide looks like or how it behaves for the person
 * sitting at it; this one decides whether a second device may read the sessions on this machine
 * and type into them. The panel says so in words next to the switch.
 *
 * No credential lives here, and that is structural. [`crate::SettingsPatch`] patches per
 * top-level field, so a screen editing anything in a group sends the whole group back — which
 * makes a masked, write-only value unrepresentable, the hazard [`crate::SettingsPatch::llm`]
 * already documents. Paired devices and their token hashes live in their own `0600` file in the
 * state directory instead; `cide-remote`'s `devices` module has the four reasons.
 * # The default is the whole safety story
 *
 * Off, loopback, and *derive the port*. Derived rather than hand-written because every field's
 * own `Default` already says the right thing and a second spelling of them could drift — but
 * the values are not incidental, so they are argued here: turning the listener on does not by
 * itself put anything on a network, because the bind is still this machine only; and the port
 * is not a number anybody promised, because nobody typed it.
 */
export type RemoteSettings = { 
/**
 * Whether the listener runs at all.
 */
enabled: boolean, 
/**
 * Which addresses it answers on.
 */
bind: RemoteBind, 
/**
 * `0` means *derive one from the profile*, which is what makes a real instance and a `[DEV]`
 * instance both work with nothing configured. A number the user typed is a promise to a
 * device that saved it, so a configured port that is taken **refuses and says so** rather
 * than sliding to another — `cide_core::remote::port_for_profile` has the argument.
 */
port: number, 
/**
 * Permit binding an address that is routable from the internet.
 *
 * A separate switch from [`Self::enabled`] on purpose. "The people on my network" and
 * "everyone" are different decisions, and a single toggle that quietly meant the second
 * would be the kind of default nobody chose.
 */
allowNonPrivate: boolean, };
