// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplayOp } from "./ReplayOp";

export type ReplayOutcome = { op: ReplayOp, 
/**
 * The commit that was replayed, full oid.
 */
source: string, 
/**
 * The commit that was created, full oid. **Empty** under [`ReplayMode::WorkingTree`],
 * which creates none — empty rather than an `Option` so it reads the same way as
 * [`crate::git::FetchOutcome`]'s vacant fields, which use the same convention for the same
 * reason.
 */
created: string, 
/**
 * The summary line of the new commit, or the one that would be used.
 */
summary: string, files: number, };
