// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a replay leaves behind.
 */
export type ReplayMode = "commit" | "workingTree";
