// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Applying an existing commit's patch somewhere else.
 *
 * One enum for both directions, because everything about them is the same — resolve a commit,
 * pick a mainline for a merge, apply, refuse on conflict — except the sign of the patch. Two
 * enums would mean two of every error variant below, and the frontend catching one of them and
 * not the other.
 */
export type ReplayOp = "revert" | "cherryPick";
