// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReplayMode } from "./ReplayMode";

export type ReplayRequest = { 
/**
 * The commit to replay, as a full oid. Not a revspec: this comes from a row the user
 * clicked, so the ambiguity a revspec can carry has nothing to resolve and everything to
 * go wrong.
 */
commit: string, mode: ReplayMode, 
/**
 * Which parent is the mainline, **1-based**, as git's `-m` numbers them.
 *
 * Required for a merge and refused for anything else — [`crate::git::GitError::
 * MergeNeedsMainline`] and [`crate::git::GitError::NotAMerge`]. Deliberately not defaulted
 * to 1: "revert this merge" without saying which side to keep is a question with no
 * correct default, and picking one silently reverts an entire feature branch or none of
 * it, with no way for the user to tell which they got until they read the diff.
 */
mainline: number | null, };
