// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoId } from "./RepoId";

/**
 * An absolute path resolved to the repository that contains it. (M18)
 *
 * Absolute in, repo-relative out. Every surface that starts from a *file* — blame on the open
 * editor, "show history for this file" from the tree, a revision diff opened from a terminal
 * link — has an absolute path in hand and needs the pair this carries before it can ask
 * `cide-git` anything, because every other path on this wire is repo-relative.
 *
 * # Why the arithmetic is in Rust
 *
 * The same reason [`TreeStatusMap`] gives for going the other way, and it is the reason that
 * matters more here because this direction is the one that silently produces a *wrong* answer
 * rather than an untagged row. A prefix comparison in TypeScript is wrong for a symlinked root
 * (the path the user opened and the path git canonicalised are different strings that name one
 * directory), wrong for a nested submodule (the innermost repository owns the path, and the
 * superproject's root is also a prefix of it), and wrong for a path that is inside no
 * repository at all — which TypeScript would answer by producing a relative path against
 * whichever root sorted first. Rust knows the project's roots, the work trees above them and
 * the submodules below them, so it can answer the question or refuse it with
 * [`GitError::NotARepository`].
 */
export type RepoPath = { 
/**
 * The innermost repository containing the path — the submodule, never its superproject.
 */
repo: RepoId, 
/**
 * Repo-relative and slash-separated, the way every other path in this module is spelled.
 */
path: string, };
