// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchInfo } from "./BranchInfo";
import type { ChangeEntry } from "./ChangeEntry";
import type { ChangelistView } from "./ChangelistView";
import type { RepoInfo } from "./RepoInfo";

/**
 * Everything the commit tool window draws for one repository.
 */
export type RepoChanges = { repo: RepoInfo, branch: BranchInfo, 
/**
 * The default list is first; the rest keep their creation order.
 */
changelists: Array<ChangelistView>, unversioned: Array<ChangeEntry>, ignored: Array<ChangeEntry>, conflicts: Array<ChangeEntry>, 
/**
 * The index no longer matches what cide last wrote to it — someone ran `git add` in a
 * pane. Drives the non-blocking "staging changed outside cide" bar; committing while
 * this is true needs an explicit override.
 */
indexChangedExternally: boolean, 
/**
 * IDEA's "use Git staging area instead" toggle. In this mode the index is the truth
 * and cide never rebuilds it from a changelist.
 */
useStagingArea: boolean, };
