// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontierRef } from "./FrontierRef";
import type { RepoId } from "./RepoId";

/**
 * One repository's position in a paged walk.
 */
export type RepoResume = { repo: RepoId, 
/**
 * The walk's priority queue, serialised: the commits the next page continues from.
 *
 * Not "the last oid emitted". A history is a DAG, so after emitting a merge the walk is
 * standing on several commits at once, and a single oid cannot say which. Restarting from
 * one of them silently drops the other side of every merge.
 */
frontier: Array<FrontierRef>, 
/**
 * Oids already emitted or deliberately simplified away, so the next page cannot emit one
 * twice.
 *
 * Bounded rather than the whole walk's history: a commit can only be reached again through
 * a frontier entry, so the set that has to survive is the one reachable from the frontier,
 * not everything ever seen. `cide_git::history` prunes it on the way out.
 */
hidden: Array<string>, 
/**
 * Commit time of the last row emitted from this repository, unix seconds. Under
 * [`LogScope::Merged`] this is the key the interleave orders by.
 */
watermark: bigint, 
/**
 * The oids emitted at exactly [`Self::watermark`].
 *
 * Needed because commit times collide constantly — a rebase writes an entire branch inside
 * one second, and a scripted import writes thousands. A watermark alone therefore cannot
 * say which of the ties were already shown, and the page boundary either repeats them or
 * swallows them. This is the field that makes paging a merged walk exact instead of nearly
 * right.
 */
recent: Array<string>, 
/**
 * Commits this repository has examined **across every page so far**, so
 * [`LogQuery::scan_limit`] is a budget for the walk rather than for one call. Without the
 * carry, a filter that finds nothing turns into an unbounded walk one page-worth at a
 * time.
 */
scanned: number, 
/**
 * This repository is exhausted. The next page skips it entirely instead of re-opening it
 * to discover the same thing.
 */
done: boolean, };
