// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogStop } from "./LogStop";
import type { RepoId } from "./RepoId";

/**
 * One repository's contribution to a page.
 */
export type RepoPage = { repo: RepoId, 
/**
 * The repository's display name, denormalised onto the page.
 *
 * So that "the walk ran out of budget in cide-git" can be said without a second lookup.
 * The alternative is a frontend that has to join every page against the repository list
 * before it can render a status line, and a page that arrives before that list — which is
 * the ordinary case on first paint — renders a uuid.
 */
name: string, stop: LogStop, 
/**
 * Commits examined for this page, this repository. Not cumulative — the running total
 * lives in [`RepoResume::scanned`], where the budget is enforced.
 */
scanned: number, };
