// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResetKind } from "./ResetKind";
import type { ShelfEntry } from "./ShelfEntry";

export type ResetOutcome = { kind: ResetKind, headBefore: string, headAfter: string, commitsDropped: number, 
/**
 * How many files a `--hard` overwrote. Zero for the other two kinds, by construction.
 */
filesDiscarded: number, 
/**
 * The shelf entry that was made, when [`ResetRequest::shelve_first`] asked for one — the
 * whole entry and not just its id, so the toast can offer *Unshelve* without a second
 * call. Mirrors [`crate::git::CheckoutOutcome::stashed`].
 */
shelved: ShelfEntry | null, };
