// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a revspec typed by a user resolved to.
 *
 * Resolved in Rust and echoed back in full, because the string the user typed (`HEAD~3`,
 * `main@{yesterday}`) means something different tomorrow, and a tab titled with it would
 * quietly change what it shows. The tab keeps the oids; the label keeps the phrasing.
 */
export type ResolvedRev = { 
/**
 * Exactly what was typed.
 */
spec: string, 
/**
 * The single revision, or the *older* end of a range — the left-hand side of `a..b`.
 */
from: string, 
/**
 * The newer end of a range. `None` when [`Self::range`] is false.
 */
to: string | null, 
/**
 * The spec was a range (`a..b` or `a...b`) rather than a single revision. Not inferable
 * from `to` being `Some` by any rule worth writing twice, and the two produce different
 * views.
 */
range: boolean, 
/**
 * The short form a tab title uses: `a1b2c3d ‥ e4f5g6h`, or the branch name when the spec
 * named one. Built in Rust so every surface abbreviates the same way.
 */
label: string, };
