// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevSide } from "./RevSide";
import type { RevisionChange } from "./RevisionChange";

/**
 * Every file that differs between two revisions.
 */
export type RevisionRange = { new: RevSide, old: RevSide, 
/**
 * What the two sides resolved to. See [`RevisionDiff::new_oid`].
 */
newOid: string | null, oldOid: string | null, 
/**
 * Summary lines of the two endpoints, for the header. Empty for
 * [`RevSide::WorkingTree`], which has no commit and therefore no message — and an empty
 * string rather than an `Option` because the header renders it either way and a `None`
 * would only be turned back into one.
 */
newSummary: string, oldSummary: string, files: Array<RevisionChange>, 
/**
 * The file list was capped. Same rule as [`CommitDetail::files_truncated`].
 */
truncated: boolean, };
