// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffHunkView } from "./DiffHunkView";
import type { FileState } from "./FileState";
import type { RevSide } from "./RevSide";

/**
 * One file's hunks between two revisions.
 *
 * The read-only twin of [`crate::git::FileDiff`], and deliberately not that type. It has no
 * `rev` and no `partial_ok`, because there is nothing to stage from it and therefore no
 * staleness to check and no refusal to explain — reusing `FileDiff` here would put two fields
 * on the wire that are meaningless for every value of them, and the first caller to trust
 * `partial_ok` on a commit diff would be offering a *Stage hunk* button on frozen history.
 */
export type RevisionDiff = { path: string, 
/**
 * The pre-rename path, when the pair differs by a rename.
 */
oldPath: string | null, 
/**
 * The requested sides, echoed back. What the tab's header shows.
 */
new: RevSide, old: RevSide, 
/**
 * The commit oids those sides **resolved to**, so a [`RevSide::FirstParent`] or
 * [`RevSide::WorkingTree`] answer can still be quoted in a bug report or pinned by a
 * follow-up call. `None` for a side with no commit — the working tree, or a file that does
 * not exist on that side.
 */
newOid: string | null, oldOid: string | null, status: FileState, binary: boolean, 
/**
 * Unix mode bits, e.g. 33188 (0o100644). Zero when the side does not exist — the same
 * convention [`crate::git::FileDiff`] uses, so a reader who knows one knows both.
 */
oldMode: number, newMode: number, hunks: Array<DiffHunkView>, 
/**
 * The old side's full text, for whole-file rendering. Same rules as
 * [`crate::git::FileDiff::old_text`]: `None` for an absent side, a binary file, a
 * submodule, a typechange, or when a side exceeded the byte cap.
 */
oldText: string | null, 
/**
 * The new side's full text. See [`crate::git::FileDiff::new_text`].
 */
newText: string | null, 
/**
 * True when an existing side exceeded the byte cap and both texts were withheld.
 * See [`crate::git::FileDiff::texts_omitted`].
 */
textsOmitted: boolean, };
