// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where in a line a [`GrammarRule`] is allowed to match.
 *
 * Not a refinement: it is what keeps a rule from being quadratic. `data.ts`'s YAML key pattern
 * scans to the end of the line before its lookahead can fail, so running it once per token makes
 * a 200,000-character line 200,000 scans of 200,000 characters — measured at 4.8 s against 20 ms
 * for the same line tried at the line head only. CodeMirror parses under a time budget, so that
 * never froze a window; it just meant the colour never arrived and a core burned until the
 * buffer was closed. A manifest author will not know that, which is exactly why the choice is a
 * field with two values rather than a comment asking them to be careful.
 */
export type RuleAt = "lineStart" | "anywhere";
