// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";

/**
 * Where cide announces a run's turn endings — handed back, finished, failed. (M40)
 *
 * # Why this is recorded on the run and not looked up at the edge
 *
 * The nudge is a line typed into somebody's conversation (`agent_rpc::note_run_over`'s header
 * says why it is a PTY write at all), and *whose* conversation used to be a fixed answer: the
 * project's primary pane. That was wrong twice over once a second Claude pane could start a run —
 * by assigning a role, and since M40 by dispatching — because the pane that asked never heard,
 * and the pane that did hear had not asked. The choice belongs to the moment of dispatch, so it
 * is stamped there, rides the run through the snapshot, and is read at the edge.
 *
 * # Why `Primary` is resolved late
 *
 * `Project::primary_session` moves whenever the console pane binds a new conversation
 * (`workspace::bind_session` rewrites it on every restart), so a *session id* captured at
 * dispatch would name a conversation that no longer exists by the time a long run ends.
 * `Primary` is therefore a role, resolved when the line is typed; [`Self::Session`] is the
 * specific pane that asked, and falls back to `Primary` if that pane is gone.
 */
export type RunNotify = { "kind": "primary" } | { "kind": "session", session: SessionId, } | { "kind": "silent" };
