// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where one run is.
 *
 * # Deliberately shaped like [`crate::SessionState`], and deliberately not that type
 *
 * A run *is* a session plus a queue position, so the resemblance is not accidental and the
 * vocabulary is kept aligned on purpose — `Running` here is `Busy` there, `AwaitingPermission`
 * is the same fact under the same name, and `Finished { code }` is `Exited { code }`. Both are
 * driven by the same hook frames through `cide_claude::next_state`.
 *
 * The one place the vocabularies deliberately *diverge* is [`Self::Idle`], which collapses
 * `SessionState`'s `Idle` and `AwaitingInput` into a single arm. Its doc says why, at the
 * length the question deserves, because it is the kind of asymmetry that gets tidied away.
 *
 * They are still two enums, because **three of these states exist before or outside a child
 * process**: `Queued` has no process yet, `Paused` describes a process that is frozen rather
 * than doing anything, and `Failed` covers the run that never started — no worktree, no binary,
 * a spawn that returned an error. `SessionState` has no vocabulary for any of them, and it
 * should not: it answers "what is this terminal doing".
 *
 * Two enums describing overlapping facts is a real cost and it is taken knowingly. The
 * alternative was adding `Queued`/`Paused` to `SessionState`, and *every* existing consumer
 * would then have to grow an arm for a state it can never see — `awaitingRule.ts`,
 * `exitMarker.ts`, `restartRule.ts`, `paneHosts::setHostBusy` — which is four places to get a
 * subagent-only concept wrong in a pane that has nothing to do with subagents. (`Paused` does
 * reach `SessionState`, because a paused *session* is a fact a pane must draw; what does not
 * reach it is the queue.)
 */
export type RunState = { "state": "queued" } | { "state": "starting" } | { "state": "running" } | { "state": "idle" } | { "state": "awaitingPermission" } | { "state": "paused", sinceUnixMs: bigint, } | { "state": "interrupted" } | { "state": "finished", code: number, } | { "state": "failed", reason: string, };
