// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resource a role's work needs that a sandboxed harness denies by default. (M119)
 *
 * Measured on codex 0.157.1 (selfcraft, 2026-09-26): its workspace-write sandbox with the
 * network off refuses **every `AF_UNIX` socket** through seccomp, not only network ones. So an
 * Xvfb cannot listen on `/tmp/.X11-unix` although that directory is writable, and a Blender run
 * finishes its script and then hangs at exit on PulseAudio's wake-up write. The one switch that
 * lifts it is the sandbox's network access, which is why all three of these mean "network on"
 * to codex and differ only in what else a harness does for them (`Display` also points glvnd at
 * Mesa, because the sandbox's `/dev` has no GPU nodes and NVIDIA's EGL crashes Xvfb's GLX).
 * The three are kept apart anyway: they are what the *role* needs, and the next harness's
 * sandbox may not tie them together.
 */
export type SandboxNeed = "display" | "audio" | "network";
