// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One cell colour, or the terminal's default when absent.
 *
 * An index is kept as an index and never resolved to RGB here. The palette belongs to whoever
 * paints: cide's own editor colours come from `crate::theme`, and a phone reading this over a
 * network is entitled to a different, higher-contrast palette for a five-inch screen. Resolving
 * on this side would take that choice away and make every capture carry one machine's theme.
 */
export type ScreenColor = { "kind": "idx", index: number, } | { "kind": "rgb", r: number, g: number, b: number, };
