// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StyleRun } from "./StyleRun";

/**
 * One row of the grid.
 */
export type ScreenLine = { row: number, 
/**
 * The line continues into the next one because the text ran off the edge, rather than
 * because the program asked for a new line.
 *
 * A consumer narrower than the capture needs this to re-wrap without inventing breaks the
 * program never wrote: a soft-wrapped paragraph may be re-flowed and two separate lines
 * may not.
 */
wrapped?: boolean, runs: Array<StyleRun>, };
