// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchMode } from "./SearchMode";

/**
 * What the user typed, and the toggles beside the input.
 *
 * Echoed back on every [`SearchFrame`] whole, rather than only the pattern string: toggling
 * case-sensitivity without touching the text changes the answer, and a frontend that
 * compared pattern strings alone would paint the old results under the new toggle.
 */
export type SearchQuery = { pattern: string, mode: SearchMode, caseSensitive: boolean, 
/**
 * Wrap the pattern in `\b…\b`. On a literal made only of punctuation this can never
 * match, which is what `grep -w` does with the same input.
 */
wholeWord: boolean, };
