// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchHit } from "./SearchHit";
import type { SearchQuery } from "./SearchQuery";

/**
 * One page of a running or finished search.
 *
 * A page, not a result set. The walk is still running while the user reads the first hits,
 * so the panel asks repeatedly from an advancing `offset` and appends — the same poll shape
 * as [`PickerFrame`], and for the same reason: pushing an event per batch would put an
 * unbounded number of them on the IPC channel during a walk of a large repository.
 */
export type SearchFrame = { 
/**
 * The query these hits answer. A frame whose query is not the one on screen is dropped
 * rather than painted.
 */
query: SearchQuery, 
/**
 * Hits `[offset, offset + hits.len())` of the full list, in walk order. Every hit from
 * one file is contiguous, which is what lets the panel group by file without sorting.
 */
hits: Array<SearchHit>, 
/**
 * Where `hits[0]` sits in the full list. Echoed so a frame that arrives out of order
 * cannot be appended twice.
 */
offset: number, 
/**
 * Hits found so far. Keeps climbing while `running`.
 */
total: number, 
/**
 * Files with at least one hit so far — the second figure in the panel's readout.
 */
files: number, 
/**
 * Files opened and scanned so far. The only honest progress figure during a walk whose
 * size is not known in advance.
 */
scanned: number, 
/**
 * The walk is still going. The panel polls again while this is true.
 */
running: boolean, 
/**
 * The hit cap stopped the search early, so the counts are floors rather than totals.
 */
truncated: boolean, 
/**
 * An unusable pattern — an unbalanced `(` in regex mode, almost always.
 *
 * Carried on the frame instead of rejecting the command: half of every regex is
 * unparsable while it is being typed, and a rejected promise per keystroke would turn
 * ordinary typing into a stream of errors in the log.
 */
error: string | null, };
