// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which build of a language server cide runs — see [`InspectionSettings::server_binaries`].
 *
 * Two variants and not a path: a settings field that accepted an arbitrary binary path would
 * be a spawn-anything surface in a file extensions can ask cide to patch. The developer's
 * escape hatch for pointing at a work-in-progress build is the `CIDE_RA_PATH` environment
 * variable, which outranks both of these and never touches disk.
 */
export type ServerBinaryChoice = "builtin" | "system";
