// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the registry can still say about a session whose pane was not there to hear it die.
 *
 * This is the answer to the *rehydration* question — a pane host evicted and re-created after
 * its child had already gone, so the `cide://session-state` event fired before anything was
 * listening. That path used to ask `session_has_exited`, which answers a `bool`, and so the
 * `— exited —` marker on it never carried a number: the code existed in this process the whole
 * time and was simply never on the wire.
 *
 * Four variants because [`cide_pty`] genuinely has four states here and collapsing any two of
 * them loses the code again:
 *
 * * `Running` — the child is alive. The pane was rehydrated over a session that outlived it,
 *   which is the ordinary case and the reason the question is asked at all.
 * * `Reaping` — `has_exited()` is true but `exit_status()` is still `None`. EOF on the pty
 *   master and the reaper's `wait()` are two events on two threads, and this is the window
 *   between them. The code exists and is milliseconds away on `cide://session-state`, so the
 *   caller must decline to mark and let the event do it.
 * * `Exited` — reaped, with the status `wait()` returned.
 * * `Unknown` — the registry has never held this id. A `SessionId` restored from
 *   `workspace.json` after a restart is exactly this: the process that owned it died with the
 *   app and no code survives anywhere. **This is the only answer for which a bare
 *   `— exited —` is the truth**, and it is why this is a variant rather than an error —
 *   `NoSuchSession` would make the one honest case indistinguishable from a failed call.
 */
export type SessionExit = { "kind": "running" } | { "kind": "reaping" } | { "kind": "exited", code: number, } | { "kind": "unknown" };
