// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneId } from "./PaneId";
import type { SessionRecord } from "./SessionRecord";

/**
 * One row of the Sessions tab. Outbound.
 */
export type SessionRow = { record: SessionRecord, 
/**
 * A child is running for it right now.
 */
live: boolean, 
/**
 * A pane of this project is showing it, so Open reveals rather than resumes.
 */
pane: PaneId | null, 
/**
 * Whether its transcript can be searched: claude, qwen and codex keep one cide can read;
 * opencode's is a database it does not.
 */
searchable: boolean, };
