// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaudeSettings } from "./ClaudeSettings";
import type { EditorSettings } from "./EditorSettings";
import type { ExplorerSettings } from "./ExplorerSettings";
import type { GraphicsSettings } from "./GraphicsSettings";
import type { InspectionSettings } from "./InspectionSettings";
import type { ProxySettings } from "./ProxySettings";
import type { SidebarSettings } from "./SidebarSettings";
import type { TerminalSettings } from "./TerminalSettings";
import type { Theme } from "./Theme";
import type { WindowMode } from "./WindowMode";

export type Settings = { 
/**
 * *Stack projects in the header* vs *One window per project*.
 */
windowMode: WindowMode, theme: Theme, 
/**
 * Point size for everything that is **not** a buffer or a terminal.
 *
 * Beside `theme` rather than in a group of its own, and for the same reason `theme` is a
 * scalar: it is one number that repaints the whole window, and a one-field group would
 * buy nothing but a type. [`SettingsPatch`](crate::SettingsPatch) patches per top-level
 * field, so a scalar also means this is the one font size a caller can move without
 * first holding the whole group it lives in — the hazard `ui/src/editor/diffViewMode.ts`
 * works around for [`EditorSettings`].
 *
 * It is a *base*, not the size of any particular label. The chrome draws at fourteen
 * design sizes between 8px and 20px, and this number scales all of them proportionally
 * through one multiplier — `--ui-scale` in `tokens.css`, which is this over
 * [`DEFAULT_UI_FONT_SIZE`]. So at 15 the file tree's 13px rows are 15px and its 10.5px
 * path labels are 12.1px; the ratios the design mock specifies are preserved, which is
 * what `./run.sh --audit-chrome` measures.
 *
 * Deliberately *not* named `zoom` and deliberately not a percentage. Icons, borders and
 * splitter widths do not follow it, so it is not a zoom level, and calling it one would
 * promise a uniform scaling this does not do.
 *
 * `f32` for [`EditorSettings::font_size`]'s reason — the Settings control steps by half a
 * pixel and an integer would snap it. Clamped where a patch lands: see
 * [`clamp_ui_font_size`].
 */
uiFontSize: number, 
/**
 * "Each project keeps its own Claude tab — pinned, cannot be closed, only its panes
 * can." Off would mean a project with no console tab, which the rest of the model
 * does not currently allow; the toggle exists in the mock and is honoured as
 * read-only-true until there is a coherent meaning for false.
 */
eachProjectKeepsClaudeTab: boolean, 
/**
 * "Reopen the last project on launch — restores its tab strip and pane layout."
 */
reopenLastProject: boolean, 
/**
 * "Keep sessions running when a project window is closed."
 *
 * Deliberately *not* worded as the mock's "keep a project running when its window is
 * closed — live Claude sessions survive in the background". cide runs no background
 * daemon: quitting the app quits its Claude sessions, and the workspace is restored on
 * relaunch via `claude --resume`. Promising background survival would be a lie.
 */
keepSessionsOnWindowClose: boolean, 
/**
 * "Confirm before closing a project with a live session." *Live* means a session is
 * `Busy` or `AwaitingPermission` — not merely that a process exists, which would warn
 * constantly.
 *
 * Read by `cide_app::cmd::app::app_quit_requested`, and by nothing else. Its whole
 * authority is over the `blocking` half of `QuitDecision`: off, and a close no longer
 * asks about an agent mid-turn.
 *
 * It governs **sessions only**, and specifically not unsaved file tabs, which are
 * reported whatever it says. The two are different kinds of loss. Interrupting a turn
 * costs the turn — the conversation is keyed by `SessionId` and resumes with
 * `claude --resume` — so a user may reasonably decide they do not want to be asked.
 * Discarding an unsaved buffer costs the work outright, with nothing to resume from,
 * and a toggle whose label says "live session" must not quietly turn that guard off
 * too. If unsaved edits ever need their own toggle, that is a second field with its own
 * wording, not a second meaning stapled to this one.
 */
confirmCloseWithLiveSession: boolean, editor: EditorSettings, terminal: TerminalSettings, graphics: GraphicsSettings, claude: ClaudeSettings, proxy: ProxySettings, sidebar: SidebarSettings, explorer: ExplorerSettings, inspections: InspectionSettings, };
