// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One choice in a [`SettingKind::Choice`].
 */
export type SettingChoice = { 
/**
 * What is stored and what the worker reads.
 */
value: string, 
/**
 * What the Settings page shows. Defaults to `value` when absent.
 */
label?: string, };
