// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingChoice } from "./SettingChoice";

/**
 * What kind of value a setting holds, and therefore what control edits it.
 *
 * Four, and the set is closed for the reason [`crate::ext::PanelDef`] draws from a fixed icon
 * table: a setting cide has no control for is a setting the user cannot change, and the answer to
 * a genuinely missing kind is to add one here — where it gets a control, a theme and a check —
 * rather than to open a hole for arbitrary markup.
 *
 * The `default` is part of the *kind* rather than a field beside it, because a default has to
 * have the kind's type and a separate field could not be made to. It is also what a setting reads
 * as before the user has ever touched it, so an extension always has a value.
 */
export type SettingKind = { "type": "toggle", default: boolean, } | { "type": "text", default: string, 
/**
 * Shown in an empty field. Not a default — a placeholder the user never replaces stores
 * the empty string, which is the distinction a settings screen most often gets wrong.
 */
placeholder?: string, } | { "type": "number", default: number, 
/**
 * Clamped to this band on the way in, wherever the value came from. A hand-edited
 * `extensions.json` goes through the same coercion the spin control does — a clamp that
 * lives only in the UI is one `invoke` away from being bypassed, which is the argument
 * `cide_ipc::settings`' own clamps already make.
 */
min?: number, max?: number, } | { "type": "choice", default: string, choices: Array<SettingChoice>, };
