// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The severities an analyser can report, in LSP's own set.
 *
 * All four are rendered rather than the two the status bar counts: dropping info and hint at
 * the wire boundary would mean the panel could not show a diagnostic that exists, which is the
 * same class of lie as an empty list.
 *
 * IDEA's *weak warning* is this enum's `Info` is LSP's `Information` — one thing, three names.
 * A fifth variant for it would mean changing `SEVERITIES`, `SEVERITY_RANK`, `SeverityCounts`,
 * `summaryLine` and every assertion in `check-problems.mjs`, for a distinction neither
 * rust-analyzer nor gopls makes.
 */
export type Severity = "error" | "warning" | "info" | "hint";
