// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which half of a new split the freshly created pane occupies.
 */
export type Side = "before" | "after";
