// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one analyser is doing.
 */
export type SourceStatus = { "kind": "unavailable", reason: string, } | { "kind": "scanning", detail: string, percentage: number | null, } | { "kind": "ready" };
