// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One operation's guidance — `apply` or `archive`.
 */
export type SpecOperationGuidance = { operation: string, guidance: Array<string>, };
