// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeName } from "./ChangeName";
import type { SpecLauncher } from "./SpecLauncher";
import type { SpecOp } from "./SpecOp";

/**
 * Start an OpenSpec session. Inbound.
 */
export type SpecSessionStart = { op: SpecOp, 
/**
 * The change an Apply implements. Required for `Apply`, ignored otherwise.
 */
change?: ChangeName, 
/**
 * What the user typed: the idea for a Propose, the question for an Explore. One line — it
 * is typed into a terminal.
 */
text?: string, launcher: SpecLauncher, };
