// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecBoard } from "./SpecBoard";

/**
 * A board and the project generation it represents. Commands and events use the same clock.
 */
export type SpecSnapshot = { revision: number, board: SpecBoard, };
