// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeName } from "./ChangeName";
import type { DeltaOperation } from "./DeltaOperation";
import type { ProjectId } from "./ProjectId";
import type { SpecId } from "./SpecId";

/**
 * Set one requirement block in one delta file. (M28)
 *
 * Inbound, so `deny_unknown_fields`: a field the frontend sends that Rust has since renamed must
 * be a refusal the developer sees, not a value silently dropped.
 */
export type SpecRequirementSet = { project: ProjectId, change: ChangeName, spec: SpecId, operation: DeltaOperation, 
/**
 * The requirement to replace, by the name on its header.
 */
requirement: string, 
/**
 * The whole replacement block, `### Requirement:` header included.
 */
block: string, };
