// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One validation complaint, in the shape the Problems panel already draws.
 */
export type SpecIssue = { 
/**
 * `ERROR`, `WARNING`, `INFO` — upstream's spelling, for [`ChangeSummary::status`]'s reason.
 */
level: string, 
/**
 * Where in the document, as the validator names it.
 */
path: string, message: string, line?: number, column?: number, };
