// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a [`SpecChange`] came from. (M28)
 *
 * # Why an archived change is a different kind of answer, not a missing one
 *
 * `openspec archive` **moves** a change to `openspec/changes/archive/<YYYY-MM-DD>-<name>/` and
 * merges its deltas into the specs. The directory survives intact — proposal, design, checklist
 * and delta files, all of it — but no CLI command reads it: `show` resolves
 * `openspec/changes/<name>/proposal.md` and nothing else, so an archived change answers
 * *not found*. A task linked to one therefore rendered as a failure ("could not be read, it may
 * have been archived") from the moment the work was accepted, which is precisely the moment its
 * record matters most.
 *
 * So cide reads the directory itself, and this field is the honest label on what comes back: the
 * deltas are recovered with the same byte-range scanner the write path uses, and the two fields
 * no directory listing can answer — [`SpecChange::progress`] and [`SpecChange::validation`] —
 * carry neutral values that **no surface may draw** for this arm. A progress bar over `0/0` on a
 * change that is finished, or a green *valid* nobody validated, would each be a worse lie than
 * the refusal this replaced.
 */
export type SpecOrigin = { "kind": "active" } | { "kind": "archived", 
/**
 * The directory's own name, date stamp and all — the only place it is recoverable, and
 * what a user needs to find the files on disk.
 */
folder: string, };
