// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { Harness } from "./Harness";

/**
 * Who runs an OpenSpec session.
 */
export type SpecLauncher = { "kind": "harness", harness: Harness, } | { "kind": "role", agent: AgentId, };
