// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecScenario } from "./SpecScenario";

/**
 * One requirement: its text, and the scenarios that make it testable.
 */
export type SpecRequirement = { 
/**
 * The name off the `### Requirement: <name>` header, which is what the archive matches on.
 *
 * **Read from the delta file, not from the CLI's JSON**, which does not carry it: a
 * requirement's `text` there has already had its header folded away. See
 * `cide_spec::block::parse` for the whole argument — the short version is that the name is
 * how an edit addresses a block, so it has to come from the same scanner the writer uses.
 */
name: string, 
/**
 * The requirement's prose — everything between the header and the first scenario, as
 * written.
 */
text: string, scenarios: Array<SpecScenario>, 
/**
 * The whole block, header included, exactly as it is in the file.
 *
 * This is what the editor edits and what `spec_requirement_set` replaces. Carried verbatim
 * rather than recomposed from the fields above, because recomposing is lossy in a way
 * nobody would notice until a diff: a requirement whose prose the user never touched would
 * come back reflowed, and the blank lines, the indentation and any markup the fields do not
 * model would be silently normalised away.
 */
block: string, };
