// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecArtifactRules } from "./SpecArtifactRules";
import type { SpecOperationGuidance } from "./SpecOperationGuidance";

/**
 * A project's OpenSpec configuration, as far as cide's reader understands it.
 *
 * # Why nothing here is filled in with a default
 *
 * `schema` stays `None` when the file states no schema, exactly as `cide_spec::config::Config`
 * keeps it — and [`Self::default_schema`] is carried *beside* it rather than substituted into
 * it. A form that showed `spec-driven` in both cases could not tell "unstated" from "stated,
 * and happens to be the default", and pressing Save would then add a line to a committed file
 * that nobody asked for. The round-trip guarantee `cide_spec::config` makes — writing a value
 * back unchanged changes no byte — only survives if the value being written back is the one the
 * file actually states.
 */
export type SpecConfig = { 
/**
 * The workflow schema id the file states, or `null` when it states none.
 */
schema: string | null, 
/**
 * What an unstated `schema:` means — `cide_spec::config::DEFAULT_SCHEMA`.
 *
 * On the wire rather than typed into TypeScript because it is the *CLI's* default, not
 * cide's, and a second copy in the frontend is one that goes stale in silence the day
 * OpenSpec ships a different one. The select shows it as the resolved value.
 */
defaultSchema: string, 
/**
 * Free prose injected into every artifact-generation prompt, newlines and all.
 *
 * The high-value field: everything an agent is told about this project's stack and
 * conventions when it writes a proposal, a design or a spec comes from here.
 */
context: string | null, 
/**
 * Per-artifact rules, in the order the file states them.
 *
 * Ordered `Vec`s and not maps, for [`Self::operations`] too: document order is what the file
 * says and what the form should show. A map would alphabetise a list the user chose the
 * order of, and the write path splices lines back where it found them.
 */
rules: Array<SpecArtifactRules>, 
/**
 * Per-operation guidance, in the order the file states them.
 */
operations: Array<SpecOperationGuidance>, 
/**
 * `<root>/openspec/config.yaml`, absolute.
 *
 * Carried because the form deliberately shows **less** than the file holds. `openspec init`
 * writes 922 bytes of which roughly eight hundred are comments, and those comments are the
 * only documentation `context`, `rules` and `operations` have anywhere. A form that hid them
 * with no way through to the file would be hiding instructions, so the surface links to this
 * path and opens it in an editor tab.
 */
path: string, 
/**
 * Whether that file exists.
 *
 * A missing file reads as an empty config and is deliberately **not** an error — see
 * `cide_spec::config::read` — so nothing else in this struct can distinguish "there is no
 * config" from "there is a config that states nothing", and those two want different words
 * above the same form.
 */
exists: boolean, };
