// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `#### Scenario:` section of a requirement.
 */
export type SpecScenario = { 
/**
 * The title off its `#### Scenario: <title>` header.
 *
 * Also absent from the CLI's JSON — a scenario's `rawText` is its body alone — and also
 * recovered from the file. A card that showed scenarios with no titles would be showing a
 * reviewer a list of WHEN/THEN bullets with nothing saying what each one is a case *of*.
 */
title: string, 
/**
 * Everything under the header, as written.
 */
body: string, };
