// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeName } from "./ChangeName";
import type { SpecTouch } from "./SpecTouch";

/**
 * What accepting a change would do, before anybody presses anything. (M28)
 *
 * # Why a preview exists at all
 *
 * Because the gesture behind it is two irreversible things in a row — a merge into the branch
 * the user has checked out, and a rewrite of `openspec/specs/`, which is what every later run
 * reads as ground truth. `ConfirmDestructive`'s rule is that a *count* is not enough: the user
 * is about to act on specific files and "3 requirements" is not something anyone can check. So
 * this names them.
 */
export type SpecAcceptPlan = { change: ChangeName, 
/**
 * The branch that would be merged — `cide/<role>-<task>` — or `None` for a role that runs
 * in the checked-out tree (`worktree: false`), where there is nothing to merge.
 *
 * `None` is **not** a refusal, and the preview has to say so plainly, or a user will read a
 * missing step as a step that was silently skipped.
 */
branch?: string, completedTasks: number, totalTasks: number, 
/**
 * The capability files `archive` would rewrite, and what it would do to each.
 */
specsTouched: Array<SpecTouch>, 
/**
 * Empty means the gesture will go through. Non-empty is the list of sentences to draw
 * instead of the button, each naming what to do next.
 */
refusals: Array<string>, };
