// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `.cide/config.json`'s `openspec` key, as the panel's gear edits it.
 */
export type SpecSettings = { 
/**
 * Apply a change in `.cide/worktrees/spec-<change>` on branch `cide/spec-<change>` rather
 * than in the project root. Only Apply: a proposal written in a worktree would be invisible
 * to the panel (which reads the root) until it was merged.
 */
applyInWorktree: boolean, };
