// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of OpenSpec's workflow commands, as this project can actually invoke it.
 *
 * # Why the invocation is carried and not derived
 *
 * Because it has changed under cide once already, silently, and it will change again. OpenSpec
 * installed its workflow as **slash commands** in `.claude/commands/opsx/`, so `propose` was
 * `/opsx:propose` and cide spelled that prefix out in nine places. Somewhere before 1.7 the CLI
 * moved the same workflow to **Claude Code skills** — `.claude/skills/openspec-propose/SKILL.md`,
 * invoked as `/openspec-propose` — and every one of those nine places became a name no project
 * has. The panel's buttons then refused with a sentence telling the user to run `openspec
 * update`, which on a current CLI answers *"all tools up to date"* and writes nothing: a
 * dead end, in cide's own words, for a project that was set up correctly.
 *
 * So `name` is cide's own handle for the command (`propose`) — stable, used by
 * `spec_run_command` and by the panel's buttons — and `line` is what a *this* project types,
 * read from its directory. A third surface costs one arm in `cide_spec::claude` and nothing
 * anywhere else.
 *
 * # Why the panel is given the line rather than trusted with it
 *
 * It draws the line as a preview under the composer, and a preview that differed from what is
 * sent would be its own small lie. `spec_run_command` still resolves `name` against the
 * directory itself and never types a string the frontend handed it — the wire carries this so
 * the two agree, not so one of them can be told what to do.
 */
export type SpecCommand = { 
/**
 * cide's handle: `propose`, `explore`. Kebab, and never carries a surface's prefix.
 */
name: string, 
/**
 * What to type, prefix and all: `/openspec-propose`, or `/opsx:propose` on a project set up
 * by an older CLI.
 */
line: string, };
