// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One workflow schema the CLI offers.
 *
 * # Why this is not `Vec<String>`
 *
 * Because `openspec schemas --json` answers with the artifacts each schema declares, and the
 * artifact list is exactly the thing cide is forbidden to assume. `cide_spec::config`'s
 * `DEFAULT_ARTIFACTS` is documented as "a default and **not** a closed set — the schema decides",
 * so a rules editor that offered four hard-coded rows would be offering the wrong ones for any
 * project on a schema it did not ship with, with nothing on screen to say so. Taking the
 * artifacts from the same document that names the schema is the only version of this that stays
 * true when somebody installs a custom schema.
 */
export type SpecSchema = { 
/**
 * The id, as `schema:` would spell it.
 */
name: string, 
/**
 * One line, the CLI's own words, or `null` when it gave none.
 */
description: string | null, 
/**
 * The artifacts this schema generates, in workflow order.
 */
artifacts: Array<string>, 
/**
 * `package`, `project`, … — where the schema came from, in the CLI's spelling.
 *
 * Upstream's word rather than an enum, for [`ChangeSummary::status`]'s reason: it is shown
 * and never branched on, and a fifth source arriving must not be a parse failure.
 */
source: string | null, };
