// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecIssue } from "./SpecIssue";

/**
 * What `openspec validate --strict` said.
 */
export type SpecValidation = { valid: boolean, issues: Array<SpecIssue>, };
