// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpecId } from "./SpecId";

/**
 * One capability under `openspec/specs/`, as the board lists it.
 */
export type SpecSummary = { id: SpecId, requirementCount: number, };
