// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneId } from "./PaneId";
import type { SplitIntent } from "./SplitIntent";

/**
 * What a split produced.
 *
 * The resolved intent travels back with the pane id because the caller may not know it: a
 * `None` intent asks the domain for the tab's default, and the frontend still has to spawn
 * the right thing afterwards. Returning only the id would leave it guessing — and guessing
 * `NewClaude` where the domain said `ForkPrimary` starts a fresh conversation where the
 * user asked to branch an existing one.
 */
export type SplitOutcome = { pane: PaneId, intent: SplitIntent, };
