// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DockerStream } from "./DockerStream";
import type { SessionId } from "./SessionId";

/**
 * What a newly split pane should contain.
 *
 * This enum *is* the multiplexing model: "one session but splittable" resolves as one
 * **primary** session plus panes that each declare what they want.
 */
export type SplitIntent = { "kind": "newClaude" } | { "kind": "forkPrimary" } | { "kind": "mirror", session: SessionId, } | { "kind": "resume", session: SessionId, } | { "kind": "shell" } | { "kind": "docker", container: string, name: string, stream: DockerStream, } | { "kind": "adopt", session: SessionId, 
/**
 * What the pane is called — `compose up : shop`.
 */
title: string, };
