// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of `git stash list`.
 */
export type StashEntry = { index: number, message: string, oid: string, };
