// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a symbol is.
 *
 * LSP's `SymbolKind` narrowed to what Rust and Go actually declare — 17 rather than 26,
 * because a kind nothing can emit is a branch in every renderer that no fixture ever reaches.
 * The one addition is [`SymbolKind::Impl`], which LSP has no name for; see its own comment.
 */
export type SymbolKind = "module" | "package" | "struct" | "enum" | "union" | "interface" | "trait" | "impl" | "function" | "method" | "constant" | "static" | "variable" | "typeAlias" | "macro" | "field" | "variant";
