// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SymbolKind } from "./SymbolKind";
import type { SymbolSpan } from "./SymbolSpan";

/**
 * One declaration, with whatever it contains.
 */
export type Symbol = { kind: SymbolKind, 
/**
 * The identifier alone: `new`, `Serve`, `MAX_FRAME`.
 *
 * Never qualified. The qualification lives in [`Self::container`] so a renderer can dim one
 * and not the other, and so the project picker can match on the name the user is actually
 * typing — see [`SymbolRow::name`] for what happens when it cannot.
 */
name: string, 
/**
 * The rest of the signature, for a row's dimmed right-hand side: `(x: u32) -> Result<T>`
 * for a function, `impl<T> Display for Foo<T>` for an impl, `struct` for a Go type spec.
 * `None` when the name is the whole story.
 *
 * Plain `Option`, so TypeScript sees `detail: string | null` — **not** `#[ts(optional)]`.
 * That attribute changes only the emitted type and not what serde writes, so on an
 * outbound type it promises `detail?: string` while putting `null` on the wire. Every
 * outbound optional in this crate is spelled this way (`HeadlessResult::session`,
 * `SearchFrame::error`); `#[ts(optional)]` is for the inbound ones, which the frontend
 * builds and Rust only ever reads.
 */
detail: string | null, 
/**
 * The trail above this symbol, already joined: `net::server` in Rust, `*Server` in Go.
 * `None` at the top level.
 *
 * Precomputed rather than derived from [`Self::children`] by the receiver, because the
 * project index ships a **flat** list where the tree is gone — and two producers of one
 * breadcrumb string is two spellings of it.
 */
container: string | null, 
/**
 * The whole declaration, body included. What the breadcrumb tests the caret against.
 */
range: SymbolSpan, 
/**
 * The name's own span. Where the caret lands.
 */
selection: SymbolSpan, children: Array<Symbol>, };
