// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a project's symbol index is doing.
 */
export type SymbolIndexStatus = { 
/**
 * True between the walk starting and finishing. The picker is usable throughout; this
 * only says whether the counts are still climbing.
 */
indexing: boolean, 
/**
 * Source files parsed — not files walked, since a `.md` is neither.
 */
files: number, symbols: number, truncated: boolean, };
