// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SymbolRow } from "./SymbolRow";

/**
 * One frame of the project symbol picker.
 *
 * The same poll shape as [`crate::PickerFrame`], and `running` means the same thing — the walk
 * is still injecting, so ask again. A separate type only because its rows are.
 */
export type SymbolFrame = { items: Array<SymbolRow>, 
/**
 * How many symbols the query matches.
 *
 * A **ceiling** rather than an exact figure while a re-index is folding a watcher burst
 * in: the matcher is append-only (`cide_search::Matcher` has no `remove`), so a symbol a
 * keystroke ago deleted is still counted here until the next rebuild. It can never be
 * *drawn* — `items` is filtered against the authoritative store before it leaves Rust —
 * which is the half that matters. Same honesty as [`crate::SearchFrame::total`].
 */
matched: number, total: number, running: boolean, 
/**
 * Echoed, so a frame arriving after the user typed on is discarded rather than painted.
 */
query: string, 
/**
 * The index hit its whole-project cap and stopped. Counts are floors.
 */
truncated: boolean, };
