// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A span, in the units the editor and every stack trace use.
 *
 * See the module docs: 1-based lines, 1-based UTF-16 columns. [`Self::end_column`] is
 * **exclusive**, matching `RevealTarget::endColumn`, so a selection is
 * `[start_column, end_column)` and an empty span has `start == end`.
 */
export type SymbolSpan = { startLine: number, startColumn: number, endLine: number, endColumn: number, };
