// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneTree } from "./PaneTree";
import type { TabId } from "./TabId";
import type { TabKind } from "./TabKind";

/**
 * A workspace tab.
 *
 * **Every** tab carries a `PaneTree`, including file tabs. That is what makes "split the
 * editor right" and "promote this pane to a full tab" the same code path instead of two.
 */
export type Tab = { id: TabId, kind: TabKind, tree: PaneTree, };
