// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSpec } from "./DiffSpec";
import type { SettingsSection } from "./SettingsSection";

export type TabKind = { "kind": "claudeHome" } | { "kind": "claudeFull", title: string, } | { "kind": "file", path: string, dirty: boolean, } | { "kind": "diff", spec: DiffSpec, } | { "kind": "settings", section: SettingsSection, };
