// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TagOutcome = { name: string, 
/**
 * The commit the tag now points at.
 */
oid: string, annotated: boolean, 
/**
 * An existing tag was force-updated rather than created. The toast says so, because "moved
 * v1.2.0" and "created v1.2.0" are things the user needs to be able to tell apart after
 * the fact.
 */
moved: boolean, };
