// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentId } from "./CommentId";
import type { TaskAuthor } from "./TaskAuthor";

/**
 * One line of a task's log.
 *
 * # Append-only for **agents**. The user may edit and delete. (M21)
 *
 * It was append-only for everyone, and that argument is still the right one where it bites: an
 * agent that can quietly rewrite a comment after the fact leaves neither the user reading the
 * panel nor the next agent reading the task any way to tell that what they are acting on is not
 * what was written.
 *
 * What it never justified was stopping the person at the keyboard from fixing their own typo or
 * removing a comment that should not be there. **The boundary is the caller, not the comment's
 * author**: `TasksStore::edit` refuses [`TaskEdit::EditComment`] and [`TaskEdit::DeleteComment`]
 * for every author but [`TaskAuthor::User`], and no MCP tool exposes either — the arrangement
 * `TasksStore::remove` already had, for the same reason.
 *
 * Three fields carry that, and each is load-bearing rather than decorative — see their own
 * notes: [`Self::id`], [`Self::edited_at_unix_ms`] and [`Self::deleted`].
 */
export type TaskComment = { 
/**
 * Stable identity, and the reason a delete survives a merge.
 *
 * The file is merged with a stale copy of itself by unioning comments, and that union used
 * to be *structural* — `(author, at_unix_ms, text)` were the only three fields there were,
 * so `==` said exactly what the rule said. Under editing that rule is wrong twice: an edit
 * changes `text`, so the stale copy's original re-appears beside the new one, and a delete
 * removes a comment the stale copy still has, so the next merge puts it back.
 *
 * A comment written by this build gets a fresh v4 uuid. A comment already in a file gets one
 * **derived from the old merge key** by [`Self::legacy_id`] — deterministic, so two readers
 * of the same file agree, and identical under exactly the conditions structural equality was
 * identical under. That is what makes the change invisible to every task file that already
 * exists rather than a migration.
 */
id: CommentId, author: TaskAuthor, 
/**
 * The text, verbatim. **Markdown**, since M27.
 *
 * This said "never rendered as markup" until M31, and by then it had been wrong for a
 * milestone: `TaskMarkdown.tsx` renders it. The refusal it recorded was about a *road*, not
 * about markup — `string -> HTML string` into `dangerouslySetInnerHTML`, model-authored, in
 * the IDE's own chrome. That road is still not taken. The parser produces no HTML node of
 * any kind, every string reaches the DOM as a React child through React's escaping, and a
 * link is drawn as accented text that activates nothing; `TaskMarkdown.tsx`'s header carries
 * the whole argument and `check:markdown` asserts the parser can never invent such a node.
 *
 * Leaving the stale sentence here was not free. It was mirrored into the MCP input schema
 * (`cide_agents::tools`), so every agent was told in the tool it was about to call that its
 * report would not be formatted — and wrote one flat paragraph, which is exactly what the
 * card then drew. A comment is read by a person; the wording an agent is handed here is the
 * thing that decides whether it is readable.
 *
 * One dialect note: the card parses with `softBreak: 'break'`, so a lone newline is a line.
 * A comment is a message, not a `.md` file — the markdown *preview* keeps CommonMark.
 */
text: string, 
/**
 * Milliseconds since the Unix epoch, stamped by Rust when the comment lands.
 *
 * Written where the mutation is applied rather than taken from the caller, for
 * [`crate::ViewPosition::touched_at`]'s reason: a timestamp supplied by whoever is writing
 * is a timestamp an agent can get wrong, and this one orders the log.
 */
atUnixMs: bigint, 
/**
 * When the user last edited it, or `None` for a comment that stands as written.
 *
 * Drawn by the panel, and that is the point rather than a nicety. The user editing an
 * *agent's* comment is the one case left that could mislead a later reader — the whole
 * hazard the append-only rule existed to prevent, with the user in the agent's place — and a
 * visible "edited" mark is what keeps the log honest about it.
 *
 * It also decides the merge: for one id, the copy with the newer edit wins. A comment that
 * was never edited sorts as its `at_unix_ms`, so an edited copy always beats an untouched
 * one no matter which file it came from.
 */
editedAtUnixMs: bigint | null, 
/**
 * A tombstone. The comment is gone from the panel and from every agent's view of the task.
 *
 * Kept as a flag rather than removed from the vector, because a removed comment is one the
 * next merge with a stale file puts straight back. `deleted` only ever goes false → true, so
 * the merge rule is "either side deleted ⇒ deleted" and no ordering question arises.
 *
 * The text is **cleared** when this is set. The tombstone has to persist; the words do not,
 * and a deleted comment whose content sat in `.cide/tasks.json` for ever would be a delete
 * that did not delete.
 */
deleted: boolean, };
