// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkType } from "./LinkType";
import type { TaskId } from "./TaskId";

/**
 * One stored edge between two tasks, on the source task only. (M30)
 *
 * Unlike a [`TaskStatusChange`], an edge is **mutable** — unlink exists — so it carries the two
 * fields that let it survive the out-of-process merge: a tombstone and a stamp. There is
 * deliberately **no `LinkId`**: a comment needed a uuid because edits change its text while its
 * identity must persist, but an edge *is* its `(link, target)` pair — there is nothing else to
 * it — so the pair is the merge identity and a minted id would be a second name for the same
 * fact, with all of [`TaskFile::tasks`]' two-identities hazard.
 */
export type TaskLink = { link: LinkType, 
/**
 * The other task. Never validated against existence *here* — `cide-tasks` refuses a target
 * that does not exist at the gesture, but a target deleted afterwards leaves the edge
 * dangling and legal, because ids are never reused (see [`TaskId`]) and so a dangling edge
 * can never silently come to mean new work. Renderers mark it; nothing prunes it.
 */
target: TaskId, 
/**
 * A tombstone — but unlike [`TaskComment::deleted`] it is a **toggle**, not one-way.
 * A deleted comment is replaced by writing a new comment under a new id; re-linking the
 * same `(link, target)` pair recreates the *same* key, so "deleted wins for ever" would
 * make an unlink permanent after any merge. The stamp below is what resolves the toggle;
 * `cide_tasks::union_links` carries the argument.
 */
deleted: boolean, 
/**
 * Stamped by Rust when the link or unlink lands, for [`TaskComment::at_unix_ms`]'s reason —
 * and load-bearing beyond display: per `(link, target)` key, the merge keeps the copy with
 * the newer stamp.
 */
atUnixMs: bigint, };
