// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";

/**
 * The whole of `.cide/tasks.json`.
 *
 * `{ "schemaVersion": 1, "rev": 42, "tasks": [ … ] }`, written with `to_vec_pretty`, because a
 * one-line JSON file makes every change a whole-file diff and this file's diffs are read by
 * people.
 */
export type TaskFile = { 
/**
 * Bumped when the on-disk shape changes, so an old file can be migrated rather than
 * silently misread — [`crate::Workspace::schema_version`]'s job, for this file.
 */
schemaVersion: number, 
/**
 * Bumped on every accepted mutation.
 *
 * It rides `cide://tasks-changed` and the receiving store drops any snapshot whose `rev` is
 * not newer, exactly as `workspace_changed` does. This file genuinely has several writers —
 * two cide windows and every dispatched agent — so out-of-order arrival is not theoretical
 * here the way it is for a single-writer registry.
 */
rev: bigint, 
/**
 * **A list, not a map**, and the order is meaningful.
 *
 * Two reasons, and the first is about people: this file is read in pull requests, where a
 * list has an order a human can follow top to bottom and a map has whatever order the
 * serialiser felt like. The second is about the shape: a map would put each id in two
 * places — the key and the value's `id` — and the first hand edit that disagreed with
 * itself would be a task with two identities.
 *
 * There is deliberately **no `order` field**. The array *is* the order. A stored rank is a
 * second source of truth that a hand-edited or merged file can contradict, and then
 * something has to decide which of the two orderings the panel obeys.
 */
tasks: Array<Task>, };
