// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";

/**
 * Who wrote a comment.
 *
 * A **tagged enum rather than a bare author string**, so the panel can style the user's own
 * lines without string-matching a name that a config file is free to choose. With a string,
 * "is this mine" would be `author === 'you'` against a value an agent definition could legally
 * claim, and the styling would be wrong in the one case it matters: a user reading back a
 * conversation to work out which half of it they said.
 *
 * [`Self::Agent`] carries `label` beside `agent` for the reason [`crate::AgentRun::agent_label`]
 * states one layer up: the label is copied at write time, so a comment written by `developer`
 * still reads correctly after the role has been renamed. A comment that renamed its own author
 * when a config file changed would be a record that lies about what happened.
 */
export type TaskAuthor = { "kind": "user" } | { "kind": "orchestrator" } | { "kind": "agent", agent: AgentId, label: string, };
