// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { CommentId } from "./CommentId";
import type { TaskStatus } from "./TaskStatus";

/**
 * One change to one task. Inbound.
 *
 * # Why an enum and not a `TaskPatch` of options
 *
 * [`crate::SettingsPatch`] is a struct of `Option`s and works, so this shape needs a reason.
 * It is one field: **unassigning**.
 *
 * In a patch struct, `agent: None` means "not mentioned, leave it alone". Expressing "set it to
 * nobody" therefore needs `Option<Option<AgentId>>` — a shape that serialises as
 * absent-versus-null, that `deny_unknown_fields` cannot police (both are well-formed), that
 * reads identically in the TypeScript type, and that every caller gets wrong exactly once
 * before discovering the difference. `SettingsPatch` gets away with per-field `Option` because
 * none of its fields is *itself* nullable; [`Task::agent`] is.
 *
 * A variant per edit also makes the mutation the caller intended legible at the seam, which
 * matters more here than for settings: these calls come from MCP tools a language model fills
 * in, and a five-variant enum with one or two fields each is called correctly far more often
 * than one nine-field object.
 *
 * # There is deliberately no `Reorder`
 *
 * The array is the order and reordering it is a real gesture — but the panel has no drag
 * affordance in v1, so a `Reorder` variant would be a wire shape no caller reaches. That is the
 * dead-control failure wearing a different hat, and this repository has already deleted one
 * instance of it: [`crate::SplitIntent`]'s removed `Diff` variant, which existed, was reachable
 * from no code path, and whose handling arm would have minted a pane showing nothing. Add it
 * with the gesture, in the same commit.
 */
export type TaskEdit = { "kind": "setTitle", title: string, } | { "kind": "setBody", body: string, } | { "kind": "setStatus", status: TaskStatus, } | { "kind": "assign", agent: AgentId | null, } | { "kind": "comment", text: string, } | { "kind": "editComment", id: CommentId, text: string, } | { "kind": "deleteComment", id: CommentId, };
