// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { ChangeName } from "./ChangeName";
import type { SessionId } from "./SessionId";
import type { TaskAuthor } from "./TaskAuthor";
import type { TaskId } from "./TaskId";
import type { TaskLink } from "./TaskLink";
import type { TaskStatus } from "./TaskStatus";

/**
 * One task as the *board* carries it: everything except its body, its log and its files. (M68)
 *
 * # Why this is a separate type and not `Task` with three keys left out
 *
 * Two reasons, and the second is the one that decides it.
 *
 * `Task::body` and `Task::comments` carry no `#[serde(default)]` — deliberately, because for
 * those two an absent key is not a fact about the task but a truncated document. A `Task` with
 * them omitted is therefore a *hard* deserialize failure, and giving them defaults to make the
 * omission legal would re-open the argument [`TaskAuthor::user`] makes: once absent means
 * `User`, or means "no comments", nothing downstream can tell a task that has none from a
 * payload that did not carry any.
 *
 * And that distinction is exactly what this type exists to keep. The board is index-shaped
 * because `cide://tasks-changed` used to carry every word ever written into a project's tracker
 * — 2.19 MB on a four-month-old board, of which the comments alone were 77.5% — and Tauri
 * delivers an event by inlining the payload into a JavaScript **source string** and `eval`ing it
 * on the GTK main loop (`tauri`'s `event::emit_js_script`). Measured: 10.2 ms to parse that board
 * as JS source against 2.9 ms as JSON, per window, per comment an agent wrote. `TASKS_CHANGED`'s
 * own doc has the rest.
 *
 * So a row is what every consumer of the *list* already needed and nothing more: the panel's row
 * draws a glyph, an id, a title and an agent chip, and every off-panel reader
 * (`openCount`, the link pickers, `taskReveal`, the OpenSpec tab) reads status, id, title or
 * `change`. A whole task is fetched by id when something opens one.
 */
export type TaskRow = { id: TaskId, title: string, status: TaskStatus, 
/**
 * The role this task is **for** — see [`Task::agent`], which this mirrors exactly.
 */
agent: AgentId | null, 
/**
 * `#[ts(optional)]` **paired with `skip_serializing_if`**, unlike [`Task::session`].
 *
 * That pairing is not tidiness. `crate::docker`'s own header spells the failure out: on its
 * own, `#[ts(optional)]` changes the emitted *type* and not what serde writes, so the field
 * the TypeScript calls `undefined` arrives as `null`, `=== undefined` is false, and the next
 * property access throws. `Task` has carried that mismatch since M28 and `adapt.ts` absorbs
 * it with `== null`; a new type is a chance not to add a third instance of it.
 */
session?: SessionId, 
/**
 * `#[ts(optional)]` + `skip_serializing_if`, on [`Self::session`]'s argument.
 */
change?: ChangeName, 
/**
 * This task's own edges, tombstones included — [`Task::links`]' posture verbatim.
 *
 * Links stay on the row rather than moving to the content file with the log, because they
 * are read *across* tasks: `blocks` is derived by scanning every other task's list, and
 * auto-dispatch refuses a blocked task by reading its blockers' statuses. A reader that had
 * to open one file per task to answer "is this one blocked" would be loading the whole board
 * to render a list, which is the cost this type exists to avoid.
 */
links: Array<TaskLink>, createdBy: TaskAuthor, createdUnixMs: bigint, 
/**
 * See [`Task::updated_unix_ms`] — the merge tiebreak and the panel's in-group sort key.
 *
 * **A write to a task's content must bump this**, or a comment stops moving its task's merge
 * rank and its position in the panel. Nothing throws; the board just quietly stops reordering.
 */
updatedUnixMs: bigint, 
/**
 * How many live comments the task has. A **cache**; the content file is the truth.
 *
 * Named `…Count` rather than `comments`, and it is worth the extra word: a field called
 * `comments` that is a number where every other reader expects a vector turns `.length` into
 * `undefined` instead of a type error, and `undefined > 0` is false — so a task with forty
 * comments would render as one with none, in silence. The name makes that a compile error.
 *
 * It is a cache because the count lives in a committed, hand-editable file separate from the
 * comments it counts, so the two can disagree — after a hand edit, a partial merge, or a
 * crash between two writes. `cide_tasks` recomputes it whenever it loads content and takes
 * content's answer, on `repair`'s rule for an attachment record: the file on disk wins over
 * the record that describes it.
 */
commentCount: number, 
/**
 * Live attachments across the body and every live comment, as one number. (M39's count.)
 *
 * A cache, on [`Self::comment_count`]'s terms. `cide_task_list` prints it because "there is a
 * file on this one" changes whether an agent spends a `cide_task_get`.
 */
attachmentCount: number, };
