// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunId } from "./RunId";
import type { TaskBoard } from "./TaskBoard";
import type { TaskId } from "./TaskId";

/**
 * A task was saved even if its subsequent proposal could not be launched. A launch refusal
 * must not turn a successful creation into a rejected request that mints a second task on retry.
 */
export type TaskProposalCreated = { board: TaskBoard, task: TaskId, proposal: RunId | null, proposalError: string | null, };
