// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file attached to a task or to a comment. (M39)
 *
 * A **string** like [`CommentId`], and a fresh v4 uuid for every record, but with none of the
 * `legacy-` story: no task file written before attachments existed carries one, so there is
 * nothing to derive and no `Default` for a repairing loader to fill. Hence no `Default` and no
 * `is_empty` — a `TaskAttachmentId` that reached the store is a real uuid or the record is dropped.
 *
 * It is also a **path component**: the bytes live at
 * `.cide/attachments/<task>/<attachment>/<name>`, and that is why `cide_tasks::repair` must never
 * re-mint one the way it re-mints a malformed task or comment id. A comment id is only a merge
 * key; re-minting an attachment id would leave the file on disk under the old one, orphaned with
 * no symptom but a broken thumbnail.
 */
export type TaskAttachmentId = string;
