// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";

/**
 * What cide knows about a project's tracker right now.
 *
 * A tagged union with first-class `Absent` and `Unreadable` states, on
 * [`crate::DiagnosticsSnapshot`]'s exact argument: **an empty array cannot tell "nothing is
 * tracked yet" from "there is no tracker in this project" from "the file will not parse"**, and
 * those are three different sentences on the screen and three different sets of buttons under
 * them. A panel that renders all three as an empty list is the confident-empty-list failure
 * that module exists to prevent, wearing different clothes.
 */
export type TaskBoard = { "kind": "absent", hint: string, path: string, } | { "kind": "unreadable", path: string, error: string, } | { "kind": "ready", tasks: Array<Task>, rev: bigint, };
