// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskAttachment } from "./TaskAttachment";
import type { TaskComment } from "./TaskComment";
import type { TaskRow } from "./TaskRow";
import type { TaskStatusChange } from "./TaskStatusChange";

/**
 * One whole task, as `task_get` answers it: its [`TaskRow`] and everything the row leaves out.
 * (M68)
 *
 * # Why the row is nested rather than flattened in
 *
 * Because the two counts have exactly one producer, `cide_tasks::row_of`, and they must keep it.
 * A shape that inlined the row's fields beside the content ones would have to either carry the
 * counts again — a second place deriving a number, where both copies are plausible and a wrong one
 * looks exactly like a right one — or omit them, which pushes the derivation into the *frontend*
 * adapter and puts the same second copy one layer further away.
 *
 * Nesting keeps it to one: whoever builds this asks `row_of` for the row, and every consumer,
 * wire or webview, spreads that answer.
 *
 * It also happens to be the shape the storage split is heading for — a row from the index joined
 * to a content file — so this is the join, written down once while both halves still live in one
 * file.
 */
export type TaskDetail = { row: TaskRow, 
/**
 * The whole statement of the work, possibly empty — [`Task::body`]'s posture verbatim.
 */
body: string, comments: Array<TaskComment>, 
/**
 * The body's files. A comment's ride in its own [`TaskComment::attachments`].
 */
attachments: Array<TaskAttachment>, history: Array<TaskStatusChange>, };
