// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { ChangeName } from "./ChangeName";
import type { ProjectId } from "./ProjectId";
import type { TaskLinkSpec } from "./TaskLinkSpec";
import type { TaskStatus } from "./TaskStatus";

/**
 * A new task. Inbound.
 */
export type TaskNew = { project: ProjectId, 
/**
 * The one required field. A task with no title is a row nobody can act on.
 */
title: string, 
/**
 * Absent means empty. [`Task::body`] is not nullable; this is, only so the common call —
 * the orchestrator creating five titles at once — need not send five empty strings.
 */
body?: string, 
/**
 * The role this is for, if it is known at creation. Absent means unassigned.
 */
agent?: AgentId, 
/**
 * Where it starts. Absent means [`TaskStatus::Todo`], which is what every caller but the
 * compose dialog sends. (M21)
 *
 * # This field is the user's, and structurally not an agent's
 *
 * [`TaskStore::create`](../../cide_tasks/struct.TaskStore.html#method.create) used to say
 * there was deliberately no wire shape for this, because *"a task created directly into
 * `Done` is a status nobody moved it to"*. That worry is about **provenance**, and it is
 * still right about the caller it was written for: an agent minting finished work would
 * leave a tracker whose statuses record nothing.
 *
 * It does not apply to a person filling in a dialog with the four states in front of them
 * and pressing Create — *I am starting this now* is an ordinary thing to say, and the old
 * shape made them say it in two writes instead of one. The restriction that matters is
 * kept, and kept **structurally**: `cide_agents::tools`' create tool has no such argument
 * and `TaskSink::create` has no such parameter, so the MCP path cannot express one. It is
 * not a check that could be forgotten; it is a signature.
 */
status?: TaskStatus, 
/**
 * The OpenSpec change this task implements, if it is known at creation. (M28)
 *
 * Set at creation and not in a follow-up edit, which matters more than it looks: the
 * auto-dispatch trigger reads the task the mutation *left behind*, so a create-then-link
 * would dispatch a run from a task that did not yet name its change, and the run would be
 * told nothing about the checklist it was started for.
 */
change?: ChangeName, 
/**
 * Edges known at creation. Absent means none. (M30)
 *
 * Here for [`Self::change`]'s exact reason, with a sharper edge: a creation naming an
 * assignee dispatches, and the trigger reads the task the mutation left behind — so
 * create-then-link would dispatch a run from a task whose `blockedBy` did not exist yet,
 * and the one interleaving the gate exists for is the one it could never see.
 */
links?: Array<TaskLinkSpec>, 
/**
 * Files to attach to the body the moment the task exists. Absent means none. (M39)
 *
 * **Source paths**, on this machine, which `cide_tasks::attachments::import` copies under
 * `.cide/attachments/<the new id>/`; a path under its staging directory is consumed. Here
 * rather than as a follow-up `task_attach` for [`Self::links`]' reason in miniature: the
 * board is broadcast once with the attachments in place instead of once without and once
 * with, and a dropped file in the New task dialog is one gesture, not two.
 */
attachments?: Array<string>, };
