// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskAttachment } from "./TaskAttachment";
import type { TaskComment } from "./TaskComment";
import type { TaskStatusChange } from "./TaskStatusChange";

/**
 * One task's content: everything about it that is not in the index. (M68)
 *
 * The whole of `.cide/tasks/<task-id>/task.json`:
 * `{ "body": "…", "comments": [ … ], "history": [ … ], "attachments": [ … ] }`.
 *
 * # Why a task's own file, and why these four fields
 *
 * Because this is where a tracker's bytes actually are. Measured on a four-month-old board: 2.19 MB
 * across 126 tasks, of which the comment text alone was 77.5% and the bodies another 18%. The index
 * beside it is 4.5% — and the index is what every *list* reads, what the board broadcasts, and what
 * a mutation has to rewrite. Splitting along that line makes the hot file bounded by task **count**
 * rather than by every word ever written into the project, with no policy deciding what is "cold".
 *
 * The four fields are the ones no reader of a list needs and no reader of a card can do without.
 * `attachments` here is the **body's**; a comment's ride in its own [`TaskComment::attachments`],
 * which is why `cide_tasks::attachment_record` searches the two chained together and why splitting
 * them across two files would put one lookup on both sides of a lazy load.
 *
 * Tombstones live here, as they do everywhere in this file's vocabulary: a deleted comment stays so
 * that a merge against a stale copy cannot resurrect it. `adapt.ts` is the single seam that drops
 * them, and it is deliberately in the webview — see `cide_tasks::detail_of`.
 *
 * **No `rev` and no schema of its own.** Both would be a second ordering counter over one logical
 * document, and `emit::tasks_changed`'s doc spends a paragraph on why that is a trap. The index
 * carries the version for the whole tracker; a content file is dated by its own mtime, which is
 * what `cide_tasks` compares before it writes one.
 */
export type TaskContent = { 
/**
 * The whole statement of the work, possibly empty — [`Task::body`]'s posture verbatim.
 *
 * `#[serde(default)]`, unlike `Task::body`, and the difference is the point: a `Task` with no
 * `body` key is a truncated document, while a content file with none is a task nobody has
 * written a description for. Here the absence is a fact about the task, which is exactly the
 * test [`TaskAuthor::user`]'s doc sets for when a default is honest.
 */
body: string, 
/**
 * Oldest first, which is the order the panel renders and an agent reads.
 */
comments: Array<TaskComment>, 
/**
 * Every status transition, oldest first. (M27)
 */
history: Array<TaskStatusChange>, 
/**
 * The body's files. Records only; the bytes are at [`TaskAttachment::relative_path`]. (M39)
 */
attachments: Array<TaskAttachment>, };
