// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { TaskAuthor } from "./TaskAuthor";
import type { TaskComment } from "./TaskComment";
import type { TaskId } from "./TaskId";
import type { TaskStatus } from "./TaskStatus";
import type { TaskStatusChange } from "./TaskStatusChange";

/**
 * One task.
 */
export type Task = { 
/**
 * `t-17`. Stable for the life of the file and never reused — see [`TaskId`].
 */
id: TaskId, 
/**
 * One line. What the row shows and what an agent quotes.
 */
title: string, 
/**
 * The whole statement of the work, possibly empty.
 *
 * Not `Option<String>`: "no body" and "an empty body" are the same fact about a task, and
 * a nullable string would make every reader handle two spellings of it.
 */
body: string, status: TaskStatus, 
/**
 * The role this task is **for** — never "who is working on it now".
 *
 * The distinction is the whole reason this field has a doc comment. A task outlives the run
 * that failed at it: the run exits, the task stays assigned to `developer`, and the next
 * dispatch picks it up. "Which agent is on it *now*" is [`crate::AgentRun::task`] read the
 * other way round, derived at render time by `TasksPanel/model.ts`'s `agentChip` and stored
 * nowhere.
 *
 * Two writers for one fact is how a task ends up claiming an agent that exited an hour ago,
 * with nothing anywhere in a position to correct it — the run that would have known is gone.
 */
agent: AgentId | null, 
/**
 * Oldest first, which is the order the panel renders and the order an agent reads.
 */
comments: Array<TaskComment>, 
/**
 * Every status transition, oldest first. (M27)
 *
 * `#[serde(default)]` so every task file that already exists parses — the same posture
 * [`Self::created_by`] took when it landed: `.cide/tasks.json` is the user's committed
 * data, and a build that refused last week's file over a field it added would be the
 * tracker locking the team out of its own repository. Recorded only on an actual change:
 * a `SetStatus` naming the status the task already has writes no row.
 */
history: Array<TaskStatusChange>, 
/**
 * Who asked for this task: the person at the keyboard, the orchestrator, or a subagent.
 * (M21)
 *
 * # Why this is a field now, having deliberately not been one
 *
 * `TaskStore::create` used to answer *who asked for this* by **seeding the log**: a task an
 * agent created opened with one comment saying so, and a task the user created opened with
 * nothing. The reasoning was that a `creator` field is one more thing an agent must be taught
 * to fill and one more column the panel must draw.
 *
 * Both halves of that turned out to be wrong here. Nothing has to be *taught* — every
 * `create` call already carries a [`TaskAuthor`], because that is where a comment's author
 * comes from, so the field is filled by the seam rather than by a model. And the absence of a
 * line was doing the work of "the user made this", which is a fact inferred from a *missing*
 * record: a user who deletes that seeded comment — which M21 lets them do — would silently
 * turn an agent's task into their own.
 *
 * So it is stored, once, at creation, and never edited afterwards: [`TaskEdit`] has no
 * variant for it and no MCP tool can express one. A creator that could be rewritten is
 * provenance that lies, which is the thing the log's append-only rule exists to prevent.
 *
 * **Absent means [`TaskAuthor::User`]**, which is what a file written before this field
 * existed decays to — and `cide_tasks::repair` recovers the real answer for those files from
 * the seeded comment before anything reads them.
 */
createdBy: TaskAuthor, createdUnixMs: bigint, 
/**
 * Bumped on every accepted mutation, and **load-bearing beyond display**: the
 * out-of-process merge in `cide_tasks` resolves a task that changed on both sides by
 * keeping the higher `updated_unix_ms`.
 */
updatedUnixMs: bigint, };
