// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskQuestion } from "./TaskQuestion";

/**
 * The user's answer to a task waiting for them — the Waiting-for-you list's three buttons.
 * (M132) One command rather than three task edits, because each is several writes that must land
 * together and one of them starts a run: "send back" is a comment, a status and a dispatch into
 * the same role's conversation, and a UI composing that from `task_edit` calls would start the
 * role before the note it is meant to read had reached the board.
 */
export type TaskResponse = { "kind": "accept" } | { "kind": "sendBack", note: string, } | { "kind": "answer", text: string, selectedIds?: Array<string>, 
/**
 * The displayed question, checked under the store lock before writing an answer.
 * Omitted by legacy text-only callers.
 */
expectedQuestion?: TaskQuestion, };
