// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalRenderer } from "./TerminalRenderer";

export type TerminalSettings = { fontSize: number, scrollback: number, 
/**
 * Which xterm.js renderer to prefer.
 *
 * A setting rather than a probe because the healthy and unhealthy paths are
 * indistinguishable from JavaScript: WebGL context creation succeeds even on a
 * software rasterizer, and `WEBGL_debug_renderer_info` is masked — on Linux it reports
 * "Apple GPU" regardless of hardware.
 */
renderer: TerminalRenderer, };
