// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalRenderer } from "./TerminalRenderer";

export type TerminalSettings = { 
/**
 * Point size for the terminal's mono face. See [`EditorSettings::font_size`] for the type.
 *
 * Defaults **equal to the editor's**, which is a decision rather than a coincidence:
 * `tokens.css` unified the two because a terminal beside an editor at a half-pixel
 * difference reads as two typefaces, and that shipped once already. Two controls means
 * they *can* diverge; nothing should make them diverge on their own.
 */
fontSize: number, scrollback: number, 
/**
 * Which xterm.js renderer to prefer.
 *
 * A setting rather than a probe because the healthy and unhealthy paths are
 * indistinguishable from JavaScript: WebGL context creation succeeds even on a
 * software rasterizer, and `WEBGL_debug_renderer_info` is masked — on Linux it reports
 * "Apple GPU" regardless of hardware.
 */
renderer: TerminalRenderer, 
/**
 * How long a shell pane's foreground job must run before the pane will say anything
 * about it, in seconds.
 *
 * The notification policy behind the pane dot, both badges and the window title: a job
 * this long gets announced, and its end then notifies. It gates the announcement of the
 * *start*, not the end — see `cide_pty::jobs`, which carries the argument (an announced
 * job's `Finished` maps to `AwaitingInput`, which raises the marker unconditionally, so
 * nothing downstream can un-announce it). The question the threshold answers is *did I
 * walk away from this?*, and the
 * right number depends on what somebody runs all day — a two-minute incremental build
 * wants a different answer than a twenty-second test suite — which is why this is a
 * setting and not the constant it used to be.
 *
 * Seconds rather than a `Duration`: this crosses the wire, and TypeScript gets a plain
 * number to put in an input. A `u32` deliberately — zero is a coherent choice (announce
 * everything) and an hour is too (effectively off), so nothing here clamps.
 *
 * `#[serde(default = "…")]` for [`SidebarSettings::agents_width`]'s reason, which is
 * worth re-reading before adding the next stored field: every existing `workspace.json`
 * has a `terminal` object without this member, and the container's `#[serde(default)]`
 * does not supply a member a *present* object happens not to mention.
 */
jobNotifyAfterSecs: number, 
/**
 * Whether a shell pane rewrites structured (JSON) log lines for a person to read.
 *
 * On, because the state it replaces is a wall of braces nobody can skim and the
 * detection refuses anything it is not sure of (`cide_core::jsonlog` carries the gate,
 * and its negative corpus is the real specification). Off is a real answer, though, and
 * this is why it is a setting rather than a constant: the rewrite happens *upstream of
 * the screen mirror*, so a rendered line's original JSON is not in the scrollback and
 * cannot be copied back out. Somebody who pastes log lines into a ticket wants the
 * bytes, not the rendering.
 *
 * Never applies to a Claude pane — see `cmd::session`, where it is installed — and a
 * change reaches running shells immediately rather than at the next spawn.
 *
 * `#[serde(default = "…")]` for [`TerminalSettings::job_notify_after_secs`]'s reason,
 * one field up.
 */
jsonLogs: boolean, };
