// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The status the file tree draws in its one-letter tag column.
 *
 * Deliberately *not* [`FileState`]. The commit panel needs both sides of the index because a
 * tri-state checkbox is a function of the pair; the file tree has one 9px column and has to
 * answer "what happened to this path" with a single letter. Two types rather than one lossy
 * shared one, because collapsing the pair is exactly the bug `ChangeEntry` exists to avoid
 * and re-deriving that collapse in TypeScript would put the rule somewhere it cannot be
 * tested against a real repository.
 *
 * The variants are the mock's — `M` blue, `A` green, `D` faint and struck through — plus
 * the two the tree can hold that the mock does not draw. Every one of them is reachable;
 * see `cide_git::tree_status` for what produces each.
 */
export type TreeStatus = "clean" | "modified" | "added" | "deleted" | "untracked" | "ignored";
