// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the tree that a speed-search query matched, and where in its name.
 *
 * `row` is an index into the *composed* flattening — the same address `fs.treeRows` serves and
 * the same one the frontend's cursor moves to — so the seam between the walked index and the
 * synthetic groups is closed in Rust and never reaches the webview.
 *
 * `start`/`end` are offsets into [`TreeRow::name`] in **UTF-16 code units**, which is the unit
 * `String.prototype.slice` indexes in. See `cide_fs::speed` for why the conversion happens here
 * rather than in the frontend.
 */
export type TreeMatch = { row: number, start: number, end: number, };
