// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectId } from "./ProjectId";
import type { TabId } from "./TabId";

/**
 * A file tab whose buffer holds edits that have not been written to disk.
 *
 * The path travels with it for the same reason [`SessionSummary`] carries a pane title: a
 * dialog that says "3 unsaved files" and cannot say *which* gives the user no basis to
 * choose between discarding and going back. `title` is the basename the tab strip already
 * shows, so the dialog and the strip name the same thing; `path` disambiguates the two
 * `mod.rs` the user has open.
 */
export type UnsavedTab = { tab: TabId, project: ProjectId, projectName: string, path: string, 
/**
 * The tab strip's label — the file's basename.
 */
title: string, };
