// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Download progress, sent at most once per whole percent so a fast connection does not flood
 * every window with events.
 *
 * KiB in a `u32` rather than bytes in a `u64`: ts-rs exports `u64` as `bigint`, which JSON
 * cannot carry, and a 4 TiB ceiling is not one an AppImage will meet.
 */
export type UpdateProgress = { receivedKib: number, 
/**
 * `None` when the server sent no `Content-Length`.
 */
totalKib: number | null, };
