// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A submitted human prompt, not a terminal keystroke or a CLI's injected context.
 */
export type UserInput = { 
/**
 * Transcript byte offset: two equal prompts remain two separate entries.
 */
id: string, ordinal: number, text: string, };
