// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { CheckResult } from "./CheckResult";
import type { TaskId } from "./TaskId";

/**
 * Verify on one task's branch. Outbound.
 */
export type VerifyState = { task: TaskId, agent: AgentId, 
/**
 * It is running now; `last` is then the previous result, if any.
 */
running: boolean, last?: CheckResult, 
/**
 * The full output, as [`GateState::log`].
 */
log?: string, 
/**
 * Red verifies in a row on this task since the last green one. (M114)
 */
failures: number, 
/**
 * `agents.verifyRetries` as it stood when this was drawn: while `failures` is at most this,
 * a red verify went back to the run itself; past it, to the reviewer.
 */
retries: number, };
