// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentId } from "./AgentId";
import type { CheckResult } from "./CheckResult";
import type { TaskId } from "./TaskId";

/**
 * Verify on one task's branch. Outbound.
 */
export type VerifyState = { task: TaskId, agent: AgentId, 
/**
 * It is running now; `last` is then the previous result, if any.
 */
running: boolean, last?: CheckResult, 
/**
 * The full output, as [`GateState::log`].
 */
log?: string, };
