// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One volume.
 */
export type VolumeRow = { name: string, driver: string, 
/**
 * Where the daemon keeps it. On a remote or virtualised daemon this is a path **on that
 * machine**, which is worth remembering before offering to open it — cide does not.
 */
mountpoint: string, 
/**
 * The compose project that created it, from `com.docker.compose.project`.
 */
project?: string, 
/**
 * How many containers reference it, or `None` where the daemon did not say.
 *
 * `None` and `Some(0)` are different claims and must not draw alike: only the second means
 * "nothing would break if you removed this".
 */
inUseBy?: bigint, };
