// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatchBackend } from "./WatchBackend";

/**
 * How the watcher is watching, and why.
 *
 * `Polling` is a degraded mode with a visible cost — a change can take a whole poll
 * interval to be noticed — so the reason is carried to the UI rather than logged. A user
 * whose inotify limit is exhausted can raise `fs.inotify.max_user_watches`; a user who is
 * told nothing just thinks the file tree is broken.
 */
export type WatchStatus = { backend: WatchBackend, 
/**
 * Set only when `backend` is `polling`. A sentence, meant for a banner.
 */
reason: string | null, 
/**
 * Directories under an explicit watch. Zero in polling mode, which watches roots
 * recursively instead.
 */
watchedDirs: number, };
