// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the app is laid out across OS windows.
 */
export type WindowMode = "stacked" | "perProject";
