// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneId } from "./PaneId";
import type { ProjectId } from "./ProjectId";
import type { TabId } from "./TabId";

/**
 * What an OS window is showing.
 *
 * The `Stacked` and `PerProject` window modes are nothing more than two different
 * mappings from `ProjectId` to `WindowRole::Shell` over identical state — which is why
 * flipping the setting touches no project, tab, pane or session.
 */
export type WindowRole = { "kind": "shell", projects: Array<ProjectId>, active: ProjectId | null, } | { "kind": "detachedPane", project: ProjectId, tab: TabId, pane: PaneId, } | { "kind": "detachedTab", project: ProjectId, tab: TabId, };
