[package]
name = "cide-fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cide-ipc = { workspace = true }
ignore = { workspace = true }
globset = { workspace = true }
notify = { workspace = true }
notify-debouncer-full = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
rayon = { workspace = true }
