// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One keystroke: a set of modifiers plus a key name.
 *
 * A binding's `key` is a sequence of these — `ctrl+k ctrl+s` is two chords — because the
 * frontend needs the strokes separately to run its prefix state machine.
 */
export type Chord = { ctrl: boolean, alt: boolean, shift: boolean, meta: boolean, 
/**
 * Lowercased key name, e.g. `p`, `right`, `comma`, `` ` ``. Never empty in anything
 * [`parse_chord`] returns; the derived `Default` and the public fields do not enforce
 * it, so a hand-built `Chord` with an empty key renders as a bare modifier string.
 */
key: string, };
