// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something wrong with a binding that resolution recovered from rather than rejecting.
 *
 * Resolution deliberately never fails: one bad line in `keymap.json` must not cost the
 * user every other binding in the file. But recovering silently is how this module's
 * stated failure mode — "my keybinding does nothing, with no visible cause" — happens, so
 * each recovery is reported instead.
 */
export type KeymapDiagnostic = { "kind": "unparseableKey", key: string, command: string, reason: string, } | { "kind": "removalMatchedNothing", key: string, command: string, };
