/**
 * Which language a path is, and how to load it.
 *
 * # One registry, two sources
 *
 * Until M22 this file *was* the registry: a closed `LanguageId` union, a `REGISTRY` of loaders, a
 * `BY_EXTENSION` table, an exhaustive `Record<LanguageId, FoldSpec>` and a `SCRATCH_TYPES` array,
 * all written here and all closed to anything outside the build.
 *
 * Now the tables come from [`BUILTIN_LANGUAGES`] — generated by `cargo xtask codegen` from
 * `cide_ipc::lang::builtins()`, which is the single place a language's *routing* is written down —
 * and an extension's languages are merged into them by [`registerLanguages`]. Two tables would let
 * a language be highlightable but unfoldable, or foldable under a name the status bar does not
 * use, and both would drift in silence; that is the same argument `cide-core::commands` makes for
 * commands and keys being one table, and it is why an extension goes through this door rather than
 * a second one beside it.
 *
 * What stays here is the half that cannot be data: [`BUILTIN_GRAMMARS`], one dynamic `import()` per
 * builtin language. That is still the whole point of the dynamic import — Vite emits one chunk per
 * module, and opening a `.toml` never downloads or parses the Rust keyword table — and it is why a
 * builtin's tokenizer could not move into the generated table with the rest of it: `rust.ts`'s hook
 * is a *function*. A contributed language has no module and no hook; its tokenizer is built from
 * the data in its manifest, with `grammarRules.ts` compiling its rules into the one hook slot.
 *
 * `languageName` is separated from `loadLanguage` for the reason it always was: the status bar has
 * to say `Rust` the moment the buffer appears — before the chunk has resolved, and still for a file
 * too large to highlight at all.
 */
import { StreamLanguage } from '@codemirror/language'
import type { Extension } from '@codemirror/state'

import type { FoldSpecDto, GrammarSpecDto, LanguageDef } from '../ipc/generated'
import { BUILTIN_LANGUAGES } from './builtinLanguages'
import type { FoldSpec } from './foldRanges'
import { compileRules } from './grammarRules'
import { tagsFor } from './highlight'
import { type Grammar, type GrammarSpec, grammar } from './streamGrammar'

/**
 * A registry identifier, not a user-visible name.
 *
 * A `string` since M22, where it was a closed union of eleven members. The union was never buying
 * type safety over anything that mattered — every table it made exhaustive is now a list — and it
 * cannot survive a set that is not known until an extension is enabled.
 */
export type LanguageId = string

/**
 * The builtin tokenizers, behind their dynamic imports.
 *
 * Keyed by the ids in [`BUILTIN_LANGUAGES`], and pinned to them by `check-editor.mjs`: a builtin
 * with no loader would resolve, name itself in the status bar, and paint in one colour.
 *
 * The registry holds the *grammar* and [`loadLanguage`] wraps it, rather than each entry building
 * its own `StreamLanguage`. Two callers need the two different things: the buffer wants a
 * CodeMirror extension, and `editor/markdown/fenceTokens.ts` wants the parser itself, because it
 * colours a fenced code block with no `EditorView` anywhere near it and `StreamLanguage` does not
 * expose the parser it was defined from.
 */
const BUILTIN_GRAMMARS: Readonly<Record<string, () => Promise<Grammar>>> = {
  rust: async () => (await import('./languages/rust')).spec,
  go: async () => (await import('./languages/go')).spec,
  typescript: async () => (await import('./languages/typescript')).spec,
  python: async () => (await import('./languages/python')).spec,
  clike: async () => (await import('./languages/clike')).spec,
  shell: async () => (await import('./languages/shell')).spec,
  json: async () => (await import('./languages/data')).json,
  toml: async () => (await import('./languages/data')).toml,
  yaml: async () => (await import('./languages/data')).yaml,
  markdown: async () => (await import('./languages/markdown')).spec,
  sql: async () => (await import('./languages/sql')).spec,
}

/** A row the *New scratch file…* picker offers. */
export interface ScratchType {
  /** The row's label, and what the status bar will say once the file is open. */
  readonly label: string
  /** The extension, without the dot. Lowercase letters and digits; Rust refuses anything else. */
  readonly ext: string
}

/**
 * The `.txt` row, which is the picker's one deliberate exception.
 *
 * It is **not** in any language's extension list and must not be added to one — that would be a
 * language with no grammar — so it resolves to `Plain Text` by the same fallback every unknown
 * extension takes, and `check-editor.mjs` special-cases exactly that. Always last, because it is
 * what a person picks when none of the others is what they meant.
 */
const PLAIN_TEXT: ScratchType = { label: 'Plain Text', ext: 'txt' }

interface Resolved {
  readonly id: LanguageId
  readonly label: string
}

/** The live table. Replaced wholesale by [`registerLanguages`]; never mutated in place. */
let LANGUAGES: readonly LanguageDef[] = BUILTIN_LANGUAGES

let byExtension = new Map<string, Resolved>()
let byName = new Map<string, Resolved>()
let folds = new Map<LanguageId, FoldSpec>()
let labels = new Map<LanguageId, string>()
let fenceWords = new Map<string, LanguageId>()
/** Tokenizers built from manifest data, for languages with no module to import. */
let contributed = new Map<LanguageId, GrammarSpec>()

/**
 * The rows the scratch picker offers, in the order it lists them.
 *
 * `let` and not `const` because the set is not known until the resolved language list arrives, and
 * an exported `let` is a live binding — every importer sees the current array without any of them
 * having to learn that this is now a function. `matchCounter(shown.length, SCRATCH_TYPES.length)`
 * in `overlays/ScratchType.tsx` reads exactly as it did before.
 *
 * Safe to read at any time because [`registerLanguages`] runs once, from the bootstrap payload,
 * before the first editor mounts and long before an overlay can be opened — and because the picker
 * is built fresh on every open, so a later re-registration is picked up rather than stale.
 */
export let SCRATCH_TYPES: readonly ScratchType[] = []

/**
 * Drop what a DTO spells out and a spec leaves absent.
 *
 * `null` and empty arrays always go: the wire says `"filenames": []` where the TypeScript shape
 * says nothing, and the two mean the same thing.
 *
 * `false` is the interesting one, and the two callers want opposite answers — which is why this
 * takes a flag rather than guessing. See [`foldSpecFrom`] and [`grammarFrom`].
 */
function prune<T extends object>(dto: T, dropFalse: boolean): Record<string, unknown> {
  const out: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(dto)) {
    if (value === null || value === undefined) continue
    if (value === false && dropFalse && key !== 'escapes') continue
    if (Array.isArray(value) && value.length === 0) continue
    out[key] = value
  }
  return out
}

/**
 * A fold spec keeps every value it was given, `false` included.
 *
 * `FoldSpecDto`'s three mirrored flags — `nestedComments`, `tripleQuotes`, `escapes` — are
 * `Option<bool>` in Rust and omitted from the JSON when unstated, so a `false` that survives to
 * here is a *stated* one and dropping it would be losing a fact. That distinction is not
 * decorative: `check-editor.mjs` asserts a fold spec's mirrored fields **equal** the grammar's, Go
 * and SQL write `nestedComments: false` in their grammars on purpose, and JSON writes nothing —
 * `undefined !== false`, so collapsing the two states breaks the mirror for one of them whichever
 * way the collapse goes.
 */
function foldSpecFrom(dto: FoldSpecDto): FoldSpec {
  return prune(dto, false) as FoldSpec
}

/**
 * Build a tokenizer for a language that has no module.
 *
 * Returns null when the definition carries no rules *and* no tables — which is exactly what a
 * builtin's generated entry looks like, and is how [`loadGrammar`] tells *"import the module"*
 * from *"build it from this"*.
 */
function grammarFrom(dto: GrammarSpecDto): GrammarSpec | null {
  // `false` is dropped here, unlike in a fold spec: `GrammarSpecDto`'s flags are plain `bool`, so
  // every one of them is present in the JSON and a `false` carries no information — except
  // `escapes`, which defaults to *true* in the tokenizer and where `false` is SQL saying a
  // backslash is an ordinary character.
  const spec = prune(dto, true) as unknown as GrammarSpec & { rules?: unknown }
  const rules = dto.rules ?? []
  const bare =
    rules.length === 0 &&
    dto.keywords.length === 0 &&
    dto.types.length === 0 &&
    dto.atoms.length === 0 &&
    dto.builtins.length === 0 &&
    dto.lineComment === undefined &&
    dto.blockComment === undefined
  if (bare) return null
  delete spec.rules
  const compiled = compileRules(rules)
  if (compiled.hook !== null) spec.hook = compiled.hook
  return spec
}

/**
 * Replace the language table with the resolved set from `Bootstrap`.
 *
 * Returns what it could not use, one sentence each, for the Extensions panel to draw. Nothing here
 * throws: a contributed language with a broken rule costs that language its colour and costs the
 * rest of the table nothing, which is the same bargain `cide-agents` strikes with a malformed role.
 *
 * Later entries win, which is what makes an extension supersede a builtin — the resolved list
 * arrives with builtins first and extensions after, in install order, and `cide-ext::contribute`
 * has already reported every displacement.
 */
export function registerLanguages(defs: readonly LanguageDef[]): string[] {
  LANGUAGES = defs
  return rebuild()
}

function rebuild(): string[] {
  const problems: string[] = []
  byExtension = new Map()
  byName = new Map()
  folds = new Map()
  labels = new Map()
  fenceWords = new Map()
  contributed = new Map()
  const scratch: ScratchType[] = []

  for (const def of LANGUAGES) {
    labels.set(def.id, def.label)
    folds.set(def.id, foldSpecFrom(def.fold))
    const built = grammarFrom(def.grammar)
    if (built !== null) contributed.set(def.id, built)
    if (built === null && BUILTIN_GRAMMARS[def.id] === undefined) {
      problems.push(`${def.label} has no tokenizer, so its files open with no highlighting.`)
    }
    for (const rule of def.grammar.rules ?? []) {
      // Validated here rather than in Rust, against the same `tagsFor` the buffer and the minimap
      // resolve names through. A list of legal names copied into `cide-ipc` would be a second
      // authority that could disagree with the first, and the disagreement shows as a token that
      // parses, matches, and paints in no colour at all.
      if (tagIsUnknown(rule.tag)) {
        problems.push(`${def.label}: \`${rule.tag}\` is not a token name cide can colour.`)
      }
    }
    for (const ext of def.extensions) {
      byExtension.set(ext.ext.toLowerCase(), { id: def.id, label: ext.label ?? def.label })
    }
    for (const name of def.filenames) {
      byName.set(name.toLowerCase(), { id: def.id, label: def.label })
    }
    for (const word of def.fenceAliases) fenceWords.set(word.toLowerCase(), def.id)
    scratch.push(...def.scratch)
  }

  SCRATCH_TYPES = [...scratch, PLAIN_TEXT]
  return problems
}

/**
 * What the scratch picker and the fence lookup are keyed on, for callers outside this file.
 *
 * `fenceLanguage` used to carry its own `FENCE_ALIASES` table mapping a fence word to an
 * *extension*, so the word routed through the same lookup a file path does. That indirection is
 * gone: a language names its own aliases, and this answers with the id directly.
 */
export function fenceAlias(word: string): LanguageId | null {
  return fenceWords.get(word.toLowerCase()) ?? null
}

// The builtins, at module load. Without this the tables are empty until `Bootstrap` arrives, and
// the window's first paint — a tab strip labelling files, a status bar naming a language, a fold
// gutter — would happen against a registry that knows no languages at all. `registerLanguages`
// replaces this the moment the bootstrap payload lands, with the same builtins plus whatever the
// enabled extensions contribute.
rebuild()

/**
 * What a buffer with no known language folds by.
 *
 * Brackets and indentation, and **no string or comment awareness at all** — guessing that `"`
 * opens a string in a file that might be prose would let one apostrophe hide every brace on its
 * line. A `.txt` file with an indented block still folds, which is more than IDEA offers.
 *
 * It is also why this is a value rather than a `null`: every buffer gets a fold gutter, so the
 * gutter reservation in `EditorSurface.module.css` is one constant width instead of a layout that
 * shifts when you switch from a `.rs` tab to a `.txt` one.
 */
export const DEFAULT_FOLD_SPEC: FoldSpec = { quotes: '', indentBlocks: true }

/**
 * How to fold this path. Never null — see [`DEFAULT_FOLD_SPEC`].
 *
 * Synchronous, and that is a requirement rather than a convenience: fold restore runs inside the
 * editor's **mount dispatch**, because the remembered scroll position is a line number and
 * applying it against unfolded heights and then folding a tick later lands the reader somewhere
 * they did not leave. That is why the resolved language set rides `Bootstrap` instead of being
 * fetched after the window opens — see `cide_ipc::lang::FoldSpecDto`.
 */
export function foldSpecFor(path: string): FoldSpec {
  const found = lookup(path)
  if (found === null) return DEFAULT_FOLD_SPEC
  return folds.get(found.id) ?? DEFAULT_FOLD_SPEC
}

/** Testing seam: the fold table, for the check that pins it against the grammars. */
export function foldSpecs(): Readonly<Record<string, FoldSpec>> {
  return Object.fromEntries(folds)
}

/**
 * The rows [`SCRATCH_TYPES`] offers for a typed query, best first.
 *
 * # Why the picker gained a filter at all
 *
 * `ScratchType.tsx` used to argue, in its header, that "there is nothing worth fuzzy-matching
 * in `Rust`, `Go`, `JSON`". That was true of thirteen rows read as a list and false of the
 * gesture: reaching SQL from the top of the list is five Down presses, while `sql` is three
 * characters and lands on it. This reverses that decision, and the header there is rewritten
 * rather than left standing.
 *
 * # Ranked, not plain-substring
 *
 * A bare `label.includes(q)` answers `js` with **JSON** — `J`… no, with nothing, and `s` with
 * *TypeScript, JavaScript, JSON, Shell, SQL* in list order, so the top row for `s` is whichever
 * happens to be highest rather than the one whose name starts that way. So: five tiers, exact
 * extension first, and list order inside a tier.
 *
 *   1. the extension exactly — `sql` is SQL, `md` is Markdown, `c` is C and not C++
 *   2. the extension by prefix — `ja` reaches nothing, `j` reaches JavaScript and JSON
 *   3. the label by prefix — `ru` is Rust, `ty` is TypeScript
 *   4. the label by substring — `script` reaches TypeScript and JavaScript
 *   5. the extension by substring — the long tail
 *
 * Case-insensitive throughout, because the labels are capitalised and the extensions are not,
 * and nobody types `SQL` looking for `.sql`.
 *
 * # Why here and not in the overlay
 *
 * The same argument [`SCRATCH_TYPES`] makes above: this file is the thing the picker must not
 * disagree with, and a filter beside the list it filters cannot drift from it. It is also what
 * makes the rule *drivable* — `check-editor.mjs` already requires the compiled `languages.js`,
 * so this needs no new plumbing to be tested, where a predicate inside the component would have
 * needed a DOM.
 *
 * An empty query is every row, in list order — which is what makes the popup's initial state
 * the same list it has always shown.
 */
export function filterScratchTypes(query: string): readonly ScratchType[] {
  const q = query.trim().toLowerCase()
  if (q === '') return SCRATCH_TYPES
  const tier = (type: ScratchType): number => {
    const ext = type.ext.toLowerCase()
    const label = type.label.toLowerCase()
    if (ext === q) return 0
    if (ext.startsWith(q)) return 1
    if (label.startsWith(q)) return 2
    if (label.includes(q)) return 3
    if (ext.includes(q)) return 4
    return 5
  }
  return SCRATCH_TYPES.map((type, index) => ({ type, index, tier: tier(type) }))
    .filter((row) => row.tier < 5)
    // Ties by list order, so the ordering is total and the top row for a given query never
    // depends on `Array.prototype.sort`'s stability guarantees for a comparator that returned 0.
    .sort((a, b) => a.tier - b.tier || a.index - b.index)
    .map((row) => row.type)
}

/**
 * Which row the type picker opens on, given the file the user is looking at.
 *
 * The language of the focused editor's file when it is one of the offered types, else the first
 * row. IDEA preselects nothing and makes every scratch a two-decision gesture; preselecting
 * makes the common case — *another one of these* — two keystrokes, and costs nothing when the
 * guess is wrong because the list is right there.
 *
 * Matched through [`lookup`] rather than on the extension string, in two passes, because the
 * extension the user is looking at is usually **not** one of the offered ones:
 *
 *   1. the *label* — so `.mjs` preselects `JavaScript` rather than `TypeScript`, even though
 *      both load the same module;
 *   2. failing that, the *grammar* — so `.tsx` preselects `TypeScript` and `.java` preselects
 *      `C`, which is the offered row that loads the same table. A one-row-off guess on a
 *      language nobody offers beats falling back to Rust because the list happens to start
 *      there.
 *
 * A file whose extension resolves to nothing preselects the row that also resolves to nothing,
 * which is `Plain Text` — the same fallback, arrived at the same way, rather than a second rule
 * naming `'txt'`.
 *
 * Pure and index-returning rather than a `ScratchType`, because the overlay's selection state is
 * an index: handing it a value it would then have to `indexOf` is two representations of one
 * fact. Never out of range — [`SCRATCH_TYPES`] is non-empty and `0` is the fallback.
 */
export function defaultScratchType(path: string | null): number {
  if (path === null) return 0
  const found = lookup(path)
  const at = SCRATCH_TYPES.findIndex((type) => {
    const offered = lookup(`scratch.${type.ext}`)
    if (found === null) return offered === null
    return offered !== null && offered.label === found.label
  })
  if (at >= 0) return at
  if (found === null) return 0
  const sameGrammar = SCRATCH_TYPES.findIndex(
    (type) => lookup(`scratch.${type.ext}`)?.id === found.id,
  )
  return sameGrammar < 0 ? 0 : sameGrammar
}

export function basename(path: string): string {
  const cut = Math.max(path.lastIndexOf('/'), path.lastIndexOf('\\'))
  return path.slice(cut + 1)
}

function lookup(path: string): Resolved | null {
  const name = basename(path).toLowerCase()
  const whole = byName.get(name)
  if (whole !== undefined) return whole

  const dot = name.lastIndexOf('.')
  // `> 0` rather than `>= 0`: a leading dot makes a hidden file, not an extension, so
  // `.gitignore` is not looked up as a `gitignore` language.
  const ext = dot > 0 ? name.slice(dot + 1) : ''
  return byExtension.get(ext) ?? null
}

/** What the status bar calls this file's language. `Plain Text` when nothing matches. */
export function languageName(path: string): string {
  return lookup(path)?.label ?? 'Plain Text'
}

/**
 * Which grammar a path resolves to, or null. (M20)
 *
 * The *id*, where [`languageName`] gives the label, and the difference matters to any caller
 * asking a question about the language rather than displaying it. Six extensions share the
 * `clike` grammar under six different labels, and `md` and `markdown` share one under one — so
 * `languageName(path) === 'Markdown'` happens to work today and is a string comparison against a
 * user-facing caption, which is the kind of test that stops being true the day somebody
 * capitalises it differently.
 *
 * Added for `editor/markdown/`, which has to know whether a pane may be previewed at all.
 */
export function languageIdFor(path: string): LanguageId | null {
  return lookup(path)?.id ?? null
}

/** Is this a file the markdown preview can render? (M20) */
export function isMarkdownPath(path: string): boolean {
  return languageIdFor(path) === 'markdown'
}

/**
 * The highlighting extension for a path, or null if there is none.
 *
 * Resolves to null rather than rejecting when the chunk fails to load: a network hiccup
 * behind the dev server, or a corrupted asset in a packaged build, should cost colour and
 * nothing else. An uncaught rejection here would leave the buffer permanently blank.
 */
export async function loadLanguage(path: string): Promise<Extension | null> {
  const found = lookup(path)
  if (!found) return null
  const spec = await loadGrammar(found.id)
  return spec === null ? null : StreamLanguage.define(spec)
}

/**
 * The tokenizer for a language id, or null if its chunk will not load. (M20)
 *
 * The half of [`loadLanguage`] that is not about CodeMirror. Both swallow a failed import for
 * the same reason: a network hiccup behind the dev server, or a corrupted asset in a packaged
 * build, should cost colour and nothing else, and an uncaught rejection out of a dynamic import
 * inside a React render leaves the surface permanently blank.
 */
export async function loadGrammar(id: LanguageId): Promise<Grammar | null> {
  // A contributed language first, so an extension that supersedes a builtin supersedes its
  // tokenizer too — which is the whole of what installing one is for.
  const data = contributed.get(id)
  if (data !== undefined) return grammar(data)
  const load = BUILTIN_GRAMMARS[id]
  if (load === undefined) return null
  try {
    return await load()
  } catch (error) {
    console.error(`[cide] could not load the ${labels.get(id) ?? id} grammar`, error)
    return null
  }
}

/**
 * Whether a stream-parser token name resolves to a `Tag` cide has a colour for.
 *
 * `tagsFor` and not a list of legal names copied into `cide-ipc`: it is the same function the
 * buffer and the minimap resolve names through, and a second authority beside it could disagree
 * with it — the disagreement showing as a token that parses, matches, and paints in no colour at
 * all, which is the hardest kind of wrong to look at and diagnose.
 */
function tagIsUnknown(name: string): boolean {
  return name === '' || tagsFor(name).length === 0
}
