//! Repository automation. Run as `cargo xtask <task>`.
//!
//! The tasks that matter are the CI gates:
//!
//! * `codegen [--check]`  — regenerate `ui/src/ipc/generated.ts` from the `cide-ipc` DTOs.
//!   With `--check` it fails when the checked-in output is stale, so a Rust field rename
//!   turns into a red build rather than a runtime `undefined` in the webview.
//! * `contract-check`     — reflect over the registered commands and events and diff them
//!   against `contract/{commands,events}.json`, so adding a command is a deliberate
//!   three-file change that a reviewer can see.
//! * `bench-ipc`          — measure the PTY transport. See `BENCH.md`; this is the M0
//!   GO/NO-GO gate.
//! * `package`            — preflight the Linux packaging and print the plan; `--write`
//!   regenerates the Flatpak files and `--check` gates them. It builds nothing unless asked
//!   with `--run`. See `package.rs` and `docs/adr/0007`.
//!
//! Both gates are line-oriented lints over source text rather than macro reflection or a
//! linked-in `cide-app`. That is a deliberate trade: `generate_handler!` expands inside a
//! crate that links a webview, and building it to ask it what it registered would make the
//! cheapest check in CI the most expensive. A text lint is readable by anyone reviewing
//! this file, and its failure mode is a false positive that a human clears in one command
//! (`cargo xtask contract-check --write`) rather than a wrong answer nobody notices.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode, Stdio};

use anyhow::{Context, Result, bail};

mod package;

const USAGE: &str = "\
cargo xtask <task>

Tasks:
  codegen [--check]        regenerate ui/src/ipc/generated.ts from cide-ipc
  contract-check [--write] diff the live command/event surface against contract/*.json
  bench-ipc                measure IPC throughput (M0 GO/NO-GO gate)
  package [targets] [...]  preflight the Linux packaging and print the plan
                             targets: --appimage --deb --flatpak (default: all)
                             --write  regenerate packaging/flatpak/*
                             --check  fail if those files are stale (CI gate)
                             --run    actually build; otherwise nothing is built
  help                     show this message
";

/// Where `ts-rs` drops one `.ts` file per exported type when `cide-ipc`'s tests run.
const BINDINGS_DIR: &str = "crates/cide-ipc/bindings";

/// The single file the frontend imports. Nothing else in `ui/` may import from
/// `bindings/`, which is why that directory stays out of the Vite root.
const GENERATED_TS: &str = "ui/src/ipc/generated.ts";

/// The header `ts-rs` puts at the top of every file it writes. Kept verbatim during
/// concatenation, which makes it a dependable block delimiter — that is what lets
/// `--check` name the types that drifted instead of printing a line offset.
const TS_RS_BANNER: &str = "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.";

const HANDLER_SRC: &str = "crates/cide-app/src/lib.rs";
const EMIT_SRC: &str = "crates/cide-app/src/emit.rs";
const COMMANDS_JSON: &str = "contract/commands.json";
const EVENTS_JSON: &str = "contract/events.json";

const BANNER: &str = "\
// GENERATED FILE — DO NOT EDIT.
//
// Every type below comes from a `#[derive(TS)]` type in `crates/cide-ipc`, concatenated in
// type-name order. Regenerate with `cargo xtask codegen`.
//
// CI runs `cargo xtask codegen --check`, so a Rust field rename that never reached this
// file fails the build instead of surfacing as an `undefined` in the webview at runtime.
";

fn main() -> ExitCode {
    let task = std::env::args().nth(1).unwrap_or_else(|| "help".into());
    let rest: Vec<String> = std::env::args().skip(2).collect();

    let result = match task.as_str() {
        "codegen" => flags(&rest, &["--check"]).and_then(|f| codegen(f.contains("--check"))),
        "contract-check" => {
            flags(&rest, &["--write"]).and_then(|f| contract_check(f.contains("--write")))
        }
        "bench-ipc" => bench_ipc(),
        "package" => flags(
            &rest,
            &[
                "--appimage",
                "--deb",
                "--flatpak",
                "--write",
                "--check",
                "--run",
            ],
        )
        .and_then(|f| {
            // Naming no target means all of them, which is what someone typing `package`
            // to see the state of things wants. Naming one means only that one.
            let named = f.contains("--appimage") || f.contains("--deb") || f.contains("--flatpak");
            let targets = if named {
                package::Targets {
                    appimage: f.contains("--appimage"),
                    deb: f.contains("--deb"),
                    flatpak: f.contains("--flatpak"),
                }
            } else {
                package::Targets::ALL
            };
            let root = workspace_root()?;
            package::package(
                &root,
                package::Options {
                    targets,
                    write: f.contains("--write"),
                    check: f.contains("--check"),
                    run: f.contains("--run"),
                },
            )
        }),
        "help" | "-h" | "--help" => {
            print!("{USAGE}");
            Ok(())
        }
        other => {
            eprintln!("unknown task: {other}\n\n{USAGE}");
            return ExitCode::from(2);
        }
    };

    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("xtask: {e:#}");
            ExitCode::FAILURE
        }
    }
}

/// Accept only the flags a task knows about.
///
/// A typo in a CI script is otherwise silent: `--wrtie` would leave `contract-check`
/// reporting drift it was asked to accept.
fn flags<'a>(args: &[String], allowed: &[&'a str]) -> Result<BTreeSet<&'a str>> {
    let mut seen = BTreeSet::new();
    for arg in args {
        let Some(flag) = allowed.iter().find(|a| **a == arg.as_str()) else {
            bail!("unexpected argument `{arg}`\n\n{USAGE}");
        };
        seen.insert(*flag);
    }
    Ok(seen)
}

fn workspace_root() -> Result<PathBuf> {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let Some(root) = manifest.parent() else {
        bail!(
            "xtask manifest has no parent directory: {}",
            manifest.display()
        );
    };
    Ok(root.to_path_buf())
}

// --- codegen ---------------------------------------------------------------------------

/// One exported type: its name, and its `.ts` text with sibling imports removed.
struct Block {
    name: String,
    body: String,
}

fn codegen(check: bool) -> Result<()> {
    let root = workspace_root()?;
    let bindings = root.join(BINDINGS_DIR);
    let target = root.join(GENERATED_TS);

    refresh_bindings(&root, &bindings)?;
    let blocks = read_blocks(&bindings)?;
    if blocks.is_empty() {
        bail!(
            "no bindings in {} — did the `export_bindings_*` tests run?",
            bindings.display()
        );
    }
    let expected = render(&blocks);

    if check {
        let current = match fs::read_to_string(&target) {
            Ok(text) => text,
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                bail!("{GENERATED_TS} is missing — run `cargo xtask codegen`");
            }
            Err(e) => return Err(e).context(format!("reading {}", target.display())),
        };
        if current != expected {
            bail!(
                "{GENERATED_TS} is stale — run `cargo xtask codegen`\n{}",
                describe_drift(&current, &expected)
            );
        }
        return Ok(());
    }

    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent).context(format!("creating {}", parent.display()))?;
    }
    fs::write(&target, &expected).context(format!("writing {}", target.display()))?;
    println!("codegen: wrote {GENERATED_TS} ({} types)", blocks.len());
    Ok(())
}

/// Re-run the `ts-rs` exporters, having first cleared the output directory.
///
/// The clear is the point: `ts-rs` only ever writes, so a DTO deleted from `cide-ipc`
/// would otherwise leave its `.ts` file behind and the generated bundle would keep
/// exporting a type that no longer exists on the wire.
///
/// The cleared files are held in memory and put back if the test run fails, so a `cide-ipc`
/// that does not compile costs a red exit and nothing else. Without that, `codegen --check`
/// — a task whose whole contract is that it only reads — would strip the bindings directory
/// on its way out and leave the next `--check` complaining about a file it destroyed.
fn refresh_bindings(root: &Path, bindings: &Path) -> Result<()> {
    let mut cleared: Vec<(PathBuf, String)> = Vec::new();
    if bindings.is_dir() {
        for entry in fs::read_dir(bindings).context(format!("reading {}", bindings.display()))? {
            let path = entry?.path();
            if path.extension().is_some_and(|e| e == "ts") {
                let text =
                    fs::read_to_string(&path).context(format!("reading {}", path.display()))?;
                fs::remove_file(&path).context(format!("removing {}", path.display()))?;
                cleared.push((path, text));
            }
        }
    }

    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let status = Command::new(&cargo)
        .args(["test", "-p", "cide-ipc"])
        .current_dir(root)
        // Test-harness chatter goes to stdout and says nothing useful here; cargo's
        // progress — including "Blocking waiting for file lock" — goes to stderr and is
        // exactly what a developer needs to see while this waits.
        .stdout(Stdio::null())
        .status()
        .context("running `cargo test -p cide-ipc`")?;
    if !status.success() {
        for (path, text) in &cleared {
            fs::write(path, text).context(format!("restoring {}", path.display()))?;
        }
        bail!("`cargo test -p cide-ipc` failed; the bindings were not regenerated");
    }
    Ok(())
}

/// Read every `.ts` file in `bindings`, sorted by type name so the output is byte-stable
/// regardless of directory iteration order.
fn read_blocks(bindings: &Path) -> Result<Vec<Block>> {
    let paths: Vec<PathBuf> = fs::read_dir(bindings)
        .context(format!("reading {}", bindings.display()))?
        .map(|e| e.map(|e| e.path()))
        .collect::<std::io::Result<Vec<_>>>()?
        .into_iter()
        .filter(|p| p.extension().is_some_and(|e| e == "ts"))
        .collect();

    let names: BTreeSet<String> = paths
        .iter()
        .filter_map(|p| p.file_stem().map(|s| s.to_string_lossy().into_owned()))
        .collect();

    let mut blocks = Vec::with_capacity(paths.len());
    for path in &paths {
        let text = fs::read_to_string(path).context(format!("reading {}", path.display()))?;
        let Some(name) = path.file_stem().map(|s| s.to_string_lossy().into_owned()) else {
            continue;
        };
        blocks.push(Block {
            name,
            body: strip_sibling_imports(&text, &names),
        });
    }
    blocks.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(blocks)
}

/// Drop the `import type { X } from "./X";` lines, which are meaningless once every type
/// shares one file.
///
/// Only imports naming a type we actually generated are removed. Anything else — a future
/// `ts-rs` emitting an import from a real npm package, say — is kept verbatim, so the
/// failure is a TypeScript error somebody reads rather than a silently dangling reference.
fn strip_sibling_imports(text: &str, generated: &BTreeSet<String>) -> String {
    let kept: Vec<&str> = text
        .lines()
        .filter(|line| !sibling_import_of(line).is_some_and(|m| generated.contains(m)))
        .collect();
    kept.join("\n").trim_end().to_string()
}

/// The module name of a relative `import type ... from "./Name";` line, if that is what
/// this line is.
fn sibling_import_of(line: &str) -> Option<&str> {
    let line = line.trim();
    if !line.starts_with("import ") {
        return None;
    }
    let rest = line.split_once("from \"./")?.1;
    Some(rest.split_once('"')?.0)
}

/// Join the blocks under the banner: one blank line between blocks, exactly one trailing
/// newline, no other whitespace variation. A no-op run has to be byte-identical or the
/// `--check` gate cries wolf.
fn render(blocks: &[Block]) -> String {
    let mut out = String::from(BANNER);
    for block in blocks {
        out.push('\n');
        out.push_str(&block.body);
        out.push('\n');
    }
    out
}

/// Split a rendered file back into per-type bodies, keyed by exported type name.
fn parse_blocks(text: &str) -> BTreeMap<String, &str> {
    text.split(TS_RS_BANNER)
        .skip(1)
        .filter_map(|chunk| Some((exported_name(chunk)?.to_string(), chunk.trim())))
        .collect()
}

/// The identifier in the block's `export type <Name> = ...` line.
fn exported_name(chunk: &str) -> Option<&str> {
    let decl = chunk
        .lines()
        .find_map(|line| line.trim_start().strip_prefix("export type "))?;
    let end = decl
        .find(|c: char| !c.is_alphanumeric() && c != '_')
        .unwrap_or(decl.len());
    Some(&decl[..end])
}

/// A per-type summary of how the file on disk differs from what codegen would write.
///
/// Line offsets would be useless here: one added field near the top of a 40-type bundle
/// shifts every line after it. Naming the types is what tells a reviewer whether the diff
/// is the change they made.
fn describe_drift(current: &str, expected: &str) -> String {
    let (current, expected) = (parse_blocks(current), parse_blocks(expected));
    let mut out = String::new();
    for name in expected.keys().filter(|n| !current.contains_key(*n)) {
        out.push_str(&format!("  new      {name}\n"));
    }
    for name in current.keys().filter(|n| !expected.contains_key(*n)) {
        out.push_str(&format!("  removed  {name}\n"));
    }
    for (name, body) in &expected {
        if current.get(name).is_some_and(|c| c != body) {
            out.push_str(&format!("  changed  {name}\n"));
        }
    }
    if out.is_empty() {
        out.push_str("  no type differs; the banner or the spacing between blocks does\n");
    }
    out
}

// --- contract-check --------------------------------------------------------------------

fn contract_check(write: bool) -> Result<()> {
    let root = workspace_root()?;
    let commands = scan_commands(&root.join(HANDLER_SRC))?;
    let events = scan_events(&root.join(EMIT_SRC))?;

    if write {
        write_contract(&root.join(COMMANDS_JSON), &commands)?;
        write_contract(&root.join(EVENTS_JSON), &events)?;
        println!(
            "contract-check: wrote {} commands, {} events",
            commands.len(),
            events.len()
        );
        return Ok(());
    }

    let mut report = String::new();
    report.push_str(&compare(
        COMMANDS_JSON,
        &read_contract(&root.join(COMMANDS_JSON))?,
        &commands,
    ));
    report.push_str(&compare(
        EVENTS_JSON,
        &read_contract(&root.join(EVENTS_JSON))?,
        &events,
    ));

    if !report.is_empty() {
        bail!(
            "the command surface has drifted from the checked-in contract\n{report}\n\
             Accept it with `cargo xtask contract-check --write`, and make sure the \
             frontend client in ui/src/ipc/client.ts moved with it."
        );
    }
    println!(
        "contract-check: {} commands, {} events — in sync",
        commands.len(),
        events.len()
    );
    Ok(())
}

/// Additions and removals, reported separately: an addition is usually intentional and an
/// removal usually breaks a caller, and a reviewer wants to see which one happened.
fn compare(what: &str, contract: &BTreeSet<String>, live: &BTreeSet<String>) -> String {
    let mut out = String::new();
    for name in live.difference(contract) {
        out.push_str(&format!("  {what}: + {name}\n"));
    }
    for name in contract.difference(live) {
        out.push_str(&format!("  {what}: - {name}\n"));
    }
    out
}

/// Read a contract file, treating absence as an empty set so that seeding a new contract
/// is one `--write` away rather than an error about a file the task is about to create.
fn read_contract(path: &Path) -> Result<BTreeSet<String>> {
    let text = match fs::read_to_string(path) {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(BTreeSet::new()),
        Err(e) => return Err(e).context(format!("reading {}", path.display())),
    };
    let names: Vec<String> = serde_json::from_str(&text)
        .context(format!("{} is not a JSON array of strings", path.display()))?;
    Ok(names.into_iter().collect())
}

fn write_contract(path: &Path, names: &BTreeSet<String>) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).context(format!("creating {}", parent.display()))?;
    }
    let names: Vec<&String> = names.iter().collect();
    let mut json = serde_json::to_string_pretty(&names)?;
    json.push('\n');
    fs::write(path, json).context(format!("writing {}", path.display()))
}

/// Pull the command names out of the single `tauri::generate_handler![...]` list.
///
/// Tauri derives a command's name from its function name, so the last path segment of each
/// entry is the string the frontend invokes: `cmd::session::session_attach` is
/// `session_attach`.
fn scan_commands(path: &Path) -> Result<BTreeSet<String>> {
    let text = fs::read_to_string(path).context(format!("reading {}", path.display()))?;
    let code = strip_line_comments(&text);
    let Some(after) = code.split_once("generate_handler!") else {
        bail!(
            "no `generate_handler!` in {} — the command surface cannot be read",
            path.display()
        );
    };
    let list = bracketed(after.1).with_context(|| {
        format!(
            "`generate_handler!` in {} is not followed by a closed `[...]` list",
            path.display()
        )
    })?;

    let mut names = BTreeSet::new();
    for entry in list.split(',') {
        let entry = entry.trim();
        if entry.is_empty() {
            continue;
        }
        let name = entry.rsplit("::").next().unwrap_or(entry);
        // The whole entry is checked, not only the segment after the last `::`. A block
        // comment around an entry (`/* cmd::app::app_quit */`) still ends in a plausible
        // name, so validating the tail alone would register a handler that is commented
        // out — the exact mistake this gate exists to catch.
        let path_shaped = entry
            .chars()
            .all(|c| c.is_alphanumeric() || c == '_' || c == ':');
        let name_shaped = !name.is_empty() && name.chars().all(|c| c.is_alphanumeric() || c == '_');
        if !path_shaped || !name_shaped {
            bail!(
                "cannot read `{entry}` in the `generate_handler!` list of {} as a command \
                 name; this lint parses source text, so keep the list one plain path per \
                 entry",
                path.display()
            );
        }
        names.insert(name.to_string());
    }
    Ok(names)
}

/// Blank out `//` comments, preserving line structure.
///
/// This runs over the whole file before anything else looks at it, and the order is
/// load-bearing in two directions. Stripping after the search would let a doc comment that
/// mentions `generate_handler!` win the search and silently reduce the command surface to
/// whatever brackets follow it. Stripping after splitting the list on commas would let a
/// comma inside a comment cut one entry in two, leaving a tail that reads as a command name
/// nobody registered.
///
/// String literals are not respected, so a `//` inside one is cut as well. Nothing between
/// `generate_handler!` and its closing bracket is a string literal, and this function's only
/// caller never reads past that point.
fn strip_line_comments(text: &str) -> String {
    text.lines()
        .map(|line| line.split_once("//").map_or(line, |(code, _)| code))
        .collect::<Vec<_>>()
        .join("\n")
}

/// The contents of the first `[...]` in `text`, respecting nesting.
fn bracketed(text: &str) -> Option<&str> {
    let start = text.find('[')?;
    let mut depth = 0usize;
    for (i, c) in text[start..].char_indices() {
        match c {
            '[' => depth += 1,
            ']' => {
                depth -= 1;
                if depth == 0 {
                    return Some(&text[start + 1..start + i]);
                }
            }
            _ => {}
        }
    }
    None
}

/// Collect the `cide://...` event names emitted by the app.
///
/// `emit.rs` arrives in a later milestone. Its absence is an empty event surface, not a
/// failure: the gate has to be green on a tree that has not grown events yet.
fn scan_events(path: &Path) -> Result<BTreeSet<String>> {
    let text = match fs::read_to_string(path) {
        Ok(text) => text,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(BTreeSet::new()),
        Err(e) => return Err(e).context(format!("reading {}", path.display())),
    };

    // A whole-line comment is not an emit site, and event names get discussed in doc
    // comments more than most strings do. Trailing comments are deliberately left in
    // place: `//` also occurs inside the literal being searched for, so cutting each line
    // at its first `//` would truncate every event name to `cide:`.
    let code: String = text
        .lines()
        .filter(|line| !line.trim_start().starts_with("//"))
        .collect::<Vec<_>>()
        .join("\n");

    let mut names = BTreeSet::new();
    let mut rest = code.as_str();
    while let Some(open) = rest.find("\"cide://") {
        let literal = &rest[open + 1..];
        let Some(end) = literal.find('"') else {
            bail!(
                "unterminated `cide://` string literal in {}",
                path.display()
            );
        };
        names.insert(literal[..end].to_string());
        rest = &literal[end + 1..];
    }
    Ok(names)
}

// --- bench-ipc -------------------------------------------------------------------------

fn bench_ipc() -> anyhow::Result<()> {
    // Deliberately an instruction rather than a spawn. The measurement only means anything
    // when it runs through a real webview on a real compositor, and BENCH.md is where the
    // numbers and the GO/NO-GO floor are recorded.
    anyhow::bail!(
        "run `cargo build -p cide-app && CIDE_BENCH=1 ./target/debug/cide` — see BENCH.md"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn set(names: &[&str]) -> BTreeSet<String> {
        names.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn sibling_imports_are_dropped_and_other_lines_survive() {
        let names = set(&["SessionId"]);
        let text = "// banner\nimport type { SessionId } from \"./SessionId\";\n\nexport type A = SessionId;\n";
        assert_eq!(
            strip_sibling_imports(text, &names),
            "// banner\n\nexport type A = SessionId;"
        );
    }

    #[test]
    fn an_import_of_a_type_we_did_not_generate_is_kept() {
        let text = "import type { Foo } from \"./Foo\";\nexport type A = Foo;\n";
        assert_eq!(
            strip_sibling_imports(text, &BTreeSet::new()),
            text.trim_end()
        );
    }

    #[test]
    fn a_package_import_is_not_mistaken_for_a_sibling() {
        assert_eq!(sibling_import_of("import type { X } from \"zod\";"), None);
        assert_eq!(
            sibling_import_of("import type { X } from \"./X\";"),
            Some("X")
        );
    }

    #[test]
    fn rendering_is_stable_across_runs() {
        let blocks = vec![
            Block {
                name: "A".into(),
                body: format!("{TS_RS_BANNER}\n\nexport type A = string;"),
            },
            Block {
                name: "B".into(),
                body: format!("{TS_RS_BANNER}\n\nexport type B = number;"),
            },
        ];
        let once = render(&blocks);
        assert_eq!(once, render(&blocks));
        assert!(once.ends_with("export type B = number;\n"));
        assert!(!once.ends_with("\n\n"));
    }

    #[test]
    fn drift_is_reported_per_type() {
        let old = render(&[Block {
            name: "A".into(),
            body: format!("{TS_RS_BANNER}\n\nexport type A = string;"),
        }]);
        let new = render(&[
            Block {
                name: "A".into(),
                body: format!("{TS_RS_BANNER}\n\nexport type A = number;"),
            },
            Block {
                name: "B".into(),
                body: format!("{TS_RS_BANNER}\n\nexport type B = number;"),
            },
        ]);
        let report = describe_drift(&old, &new);
        assert!(report.contains("new      B"), "{report}");
        assert!(report.contains("changed  A"), "{report}");
        assert!(!report.contains("removed"), "{report}");
    }

    #[test]
    fn identical_types_with_a_different_banner_still_report_something() {
        let block = Block {
            name: "A".into(),
            body: format!("{TS_RS_BANNER}\n\nexport type A = string;"),
        };
        let rendered = render(std::slice::from_ref(&block));
        let report = describe_drift(
            &rendered.replace("GENERATED FILE", "generated file"),
            &rendered,
        );
        assert!(report.contains("banner"), "{report}");
    }

    #[test]
    fn handler_entries_reduce_to_their_last_path_segment() {
        let src =
            "tauri::generate_handler![\n  cmd::app::app_ready,\n  cmd::session::session_attach,\n]";
        let path = scratch("handler.rs", src);
        assert_eq!(
            scan_commands(&path).unwrap(),
            set(&["app_ready", "session_attach"])
        );
    }

    #[test]
    fn a_commented_out_handler_is_not_part_of_the_surface() {
        let src = "generate_handler![\n  cmd::app::app_ready,\n  // cmd::app::app_quit,\n]";
        let path = scratch("commented.rs", src);
        assert_eq!(scan_commands(&path).unwrap(), set(&["app_ready"]));
    }

    #[test]
    fn a_comma_inside_a_comment_does_not_invent_a_command() {
        let src =
            "generate_handler![\n  cmd::app::app_ready,\n  // TODO: add app_quit, app_reload\n]";
        let path = scratch("comma-in-comment.rs", src);
        assert_eq!(scan_commands(&path).unwrap(), set(&["app_ready"]));
    }

    #[test]
    fn a_comment_naming_the_macro_does_not_win_the_search() {
        let src = "//! The surface is the `generate_handler![app_ready]` list below.\n\
                   tauri::generate_handler![\n  cmd::app::app_ready,\n  cmd::session::session_kill,\n]";
        let path = scratch("macro-in-doc.rs", src);
        assert_eq!(
            scan_commands(&path).unwrap(),
            set(&["app_ready", "session_kill"])
        );
    }

    #[test]
    fn a_block_commented_entry_is_rejected_rather_than_registered() {
        let src = "generate_handler![\n  cmd::app::app_ready,\n  /* cmd::app::app_quit */\n]";
        let path = scratch("block-comment.rs", src);
        assert!(scan_commands(&path).is_err());
    }

    #[test]
    fn a_handler_list_that_cannot_be_parsed_fails_loudly() {
        let src = "generate_handler![ cmd::app::app_ready(), ]";
        let path = scratch("weird.rs", src);
        assert!(scan_commands(&path).is_err());
    }

    #[test]
    fn a_missing_generate_handler_is_an_error_not_an_empty_surface() {
        let path = scratch("empty.rs", "fn main() {}");
        assert!(scan_commands(&path).is_err());
    }

    #[test]
    fn events_are_collected_from_string_literals() {
        let src = "emit(\"cide://workspace/changed\");\nemit(\"cide://session/state\");\nlet _ = \"not an event\";";
        let path = scratch("emit.rs", src);
        assert_eq!(
            scan_events(&path).unwrap(),
            set(&["cide://workspace/changed", "cide://session/state"])
        );
    }

    #[test]
    fn an_event_named_in_a_comment_is_not_part_of_the_surface() {
        let src = "/// Pairs with `\"cide://session/state\"`.\nemit(\"cide://session/exit\");";
        let path = scratch("documented-emit.rs", src);
        assert_eq!(scan_events(&path).unwrap(), set(&["cide://session/exit"]));
    }

    #[test]
    fn a_missing_emit_module_is_an_empty_event_surface() {
        let path = scratch_dir().join("no-such-emit.rs");
        assert!(!path.exists());
        assert_eq!(scan_events(&path).unwrap(), BTreeSet::new());
    }

    #[test]
    fn comparison_separates_additions_from_removals() {
        let report = compare("x.json", &set(&["a", "b"]), &set(&["b", "c"]));
        assert!(report.contains("+ c"), "{report}");
        assert!(report.contains("- a"), "{report}");
        assert!(compare("x.json", &set(&["a"]), &set(&["a"])).is_empty());
    }

    #[test]
    fn unknown_flags_are_rejected() {
        assert!(flags(&["--check".into()], &["--check"]).is_ok());
        assert!(flags(&["--wrtie".into()], &["--write"]).is_err());
    }

    #[test]
    fn nested_brackets_do_not_end_the_handler_list() {
        assert_eq!(bracketed(" [a, b[0], c]"), Some("a, b[0], c"));
        assert_eq!(bracketed("[unclosed"), None);
    }

    /// A scratch directory outside the repository, so no test can scribble on a real
    /// source file. Scoped to the process: a fixed name under a shared `/tmp` belongs to
    /// whoever ran the tests first, and every later user gets a permission denial instead
    /// of a test result.
    fn scratch_dir() -> PathBuf {
        std::env::temp_dir().join(format!("cide-xtask-{}", std::process::id()))
    }

    fn scratch(name: &str, contents: &str) -> PathBuf {
        let dir = scratch_dir();
        fs::create_dir_all(&dir).unwrap();
        let path = dir.join(name);
        fs::write(&path, contents).unwrap();
        path
    }
}
