//! Writes the test vectors the companion application checks its own crypto against. (M72)
//!
//! `crates/cide-remote/src/seal.rs` and `cide-mobile`'s `src/crypto/seal.ts` are two
//! implementations of one thing, and **none of the ways they can disagree produce an error that
//! says so**: a wrong HKDF label, a byte order, a swapped direction — each of them derives a
//! perfectly good channel that the other end cannot read. The symptom is a socket that opens and
//! then goes quiet, which is also what a bad network looks like.
//!
//! So this emits the ground truth, tracked in `contract/seal-vectors.json` beside the protocol it
//! belongs to:
//!
//! ```sh
//! cargo test -p cide-remote --test vectors -- --ignored
//! ```
//!
//! It is `#[ignore]`d because it *writes a tracked file*, which is not a thing an ordinary test
//! run should do — and because regenerating it is a deliberate act: a vector that changed is a
//! wire that changed, and every paired device is about to stop working.
//!
//! The private keys in it are minted here and used for nothing. They are in the file because a
//! vector without them cannot be checked by an implementation that has to *derive*.

use std::path::PathBuf;

use cide_remote::seal::{self, Handshake, Mode, StaticKey};

/// Where the vectors live. Beside `protocol.ts`, because they are the same kind of thing: a
/// promise about the wire this repository makes and another one reads.
fn vectors_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("contract/seal-vectors.json")
}

#[test]
#[ignore = "writes a tracked file; run deliberately when the transport changes"]
fn write_cross_language_vectors() {
    let mut cases = Vec::new();

    for (mode, device, psk) in [
        (Mode::Pair, "", Vec::new()),
        (
            Mode::Resume,
            "d-11111111-2222-3333-4444-555555555555",
            vec![7u8; 32],
        ),
        (Mode::Resume, "d-abc", (0..32u8).collect::<Vec<u8>>()),
    ] {
        let statik = StaticKey::ephemeral();
        let (handshake, ephemeral) = seal::client_handshake(mode, device);
        let server = seal::derive(&statik, &handshake, &psk, true);
        let sas = server.sas;
        let (mut server_open, mut server_seal) = (server.opener, server.sealer);
        let mut client_seal =
            seal::derive_client(&ephemeral, &statik.public_bytes(), &handshake, &psk).sealer;

        // Four frames each way. The first is the one a transposed direction still gets right by
        // luck; the fourth is one a counter bug has certainly reached.
        let mut client_to_server = Vec::new();
        let mut server_to_client = Vec::new();
        for n in 0..4u8 {
            let plaintext = format!(r#"{{"id":{n},"body":{{"t":"ping"}}}}"#);
            let sealed = client_seal.seal(plaintext.as_bytes()).expect("seals");
            // Proved against this end before it is written down, so a vector can never record
            // something this implementation would itself refuse.
            assert_eq!(
                server_open.open(&sealed).expect("opens"),
                plaintext.as_bytes()
            );
            client_to_server.push(serde_json::json!({
                "plaintext": plaintext,
                "sealed": hex(&sealed),
            }));

            let reply = format!(r#"{{"id":{n},"body":{{"t":"pong"}}}}"#);
            let sealed = server_seal.seal(reply.as_bytes()).expect("seals");
            server_to_client.push(serde_json::json!({
                "plaintext": reply,
                "sealed": hex(&sealed),
            }));
        }

        cases.push(serde_json::json!({
            "mode": match mode { Mode::Pair => "pair", Mode::Resume => "resume" },
            "device": device,
            "psk": hex(&psk),
            "serverStaticPublic": hex(&statik.public_bytes()),
            "clientEphemeralSecret": hex(&ephemeral.to_bytes()),
            "clientEphemeralPublic": hex(&handshake.ephemeral),
            "handshake": hex(&handshake.encode()),
            // The six digits both ends must agree on. Pinned here because the whole typed
            // pairing road rests on two *different implementations* deriving the same number
            // from the same exchange, and a divergence would not break a connection or fail a
            // test on either side — it would show two numbers to a person who would correctly
            // conclude they were being attacked, and give up.
            "sas": sas.digits(),
            "clientToServer": client_to_server,
            "serverToClient": server_to_client,
        }));
    }

    let document = serde_json::json!({
        "note": "Generated by `cargo test -p cide-remote --test vectors -- --ignored`. Ground \
                 truth for any second implementation of cide's sealed transport. The keys here \
                 are minted for these vectors and used for nothing.",
        "sealVersion": seal::SEAL_VERSION,
        "cases": cases,
    });

    let path = vectors_path();
    std::fs::write(
        &path,
        format!(
            "{}\n",
            serde_json::to_string_pretty(&document).expect("serialises")
        ),
    )
    .expect("writes the vectors");
    println!("wrote {}", path.display());
}

/// The handshake decodes to what was encoded.
///
/// Checked here as well as in the unit tests because *this* file is what another implementation
/// reads: the bytes it records have to round-trip through the shape it claims they are.
#[test]
fn the_recorded_handshake_shape_round_trips() {
    let (handshake, _) = seal::client_handshake(Mode::Resume, "d-abc");
    let bytes = handshake.encode();
    assert_eq!(Handshake::decode(&bytes).expect("decodes"), handshake);
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}
